-- Normalize legacy-news media display filenames. Generated by scripts/build_legacy_news_seed.py.
SET NAMES utf8mb4;
START TRANSACTION;

UPDATE media_asset SET original_filename = '外墙隔热保温改造完成，奥飞气凝胶涂料显著提升节能性能-视频-1.mp4' WHERE sha256 = '2f41fc38696f7f3c7a8ddf7b590e79b2c5e9a77fb2d528015036592994691fcc'
AND original_filename <> '外墙隔热保温改造完成，奥飞气凝胶涂料显著提升节能性能-视频-1.mp4';

UPDATE media_asset SET original_filename = '长沙屋顶隔热保温望城区山与墅项目圆满完工，奥飞涂料助力清凉过夏-视频-1.mp4' WHERE sha256 = '981448f2b52ae4642b5ac325fa8bb515655192c1ccee0f71cab9e33f85f227f7'
AND original_filename <> '长沙屋顶隔热保温望城区山与墅项目圆满完工，奥飞涂料助力清凉过夏-视频-1.mp4';

UPDATE media_asset SET original_filename = '为迎接93大阅兵，停工半日，邀请全员工停下脚步，缅怀历史-视频-1.mp4' WHERE sha256 = 'ae0e98eda3e42b1cb798dd76b0cb16364079ec1aaab009458f2cc434d7b285cd'
AND original_filename <> '为迎接93大阅兵，停工半日，邀请全员工停下脚步，缅怀历史-视频-1.mp4';

UPDATE media_asset SET original_filename = '0b9021d5dd0dfa3360eaa5e43bad9156901eda7c.jpg' WHERE sha256 = '4c81252b7c535b2760eeb7d4656e42de3078cb99ddc394d35ee4a7d12a76de2b'
AND original_filename <> '0b9021d5dd0dfa3360eaa5e43bad9156901eda7c.jpg';

UPDATE media_asset SET original_filename = '83e512af155972c417b3321062ca485c0cf56069.jpg' WHERE sha256 = '8d357c9b181fa398e839bbe312ab1d35a69d70d3e5f41055edf5e674bed09755'
AND original_filename <> '83e512af155972c417b3321062ca485c0cf56069.jpg';

UPDATE media_asset SET original_filename = 'f6caf76a93de0b04ed06b0b4a2f2e5cc5ff02508.jpg' WHERE sha256 = '80153eab04f13ec7fa411df83572338c9671f16ddc54375c71ea4ba1f484077f'
AND original_filename <> 'f6caf76a93de0b04ed06b0b4a2f2e5cc5ff02508.jpg';

UPDATE media_asset SET original_filename = 'ab3984a75e99c000f653c3a570836161eaaebaa6.jpg' WHERE sha256 = 'caed9aebcce512c2ebfcd83d8a9bf146899817ff7e0be9e0c9786fef0f6e5625'
AND original_filename <> 'ab3984a75e99c000f653c3a570836161eaaebaa6.jpg';

UPDATE media_asset SET original_filename = '13b680626be9df00a9ae58cf38449d9159130342.jpg' WHERE sha256 = '9efdfef4d48b13084250f75d33b16d41ae072eb717787783f8561edf4fd9f793'
AND original_filename <> '13b680626be9df00a9ae58cf38449d9159130342.jpg';

UPDATE media_asset SET original_filename = 'd712420f7b720490fd327effdc017aa06744549f.jpg' WHERE sha256 = '3b6608077d06aa72b9da2c52092344be794acbc191063e0b62dc925aea07475b'
AND original_filename <> 'd712420f7b720490fd327effdc017aa06744549f.jpg';

UPDATE media_asset SET original_filename = '67b3e1023d338655ab999e61522f6d8feb5238cc.jpg' WHERE sha256 = 'c92d58ee914d0100519eeec8c9c852144f03a2d03525a6aa7c99635163c5cede'
AND original_filename <> '67b3e1023d338655ab999e61522f6d8feb5238cc.jpg';

UPDATE media_asset SET original_filename = '6f843a9ee4681fd353e0f73181eb4c4e242ee27f.jpg' WHERE sha256 = '08d386558b565fdcfb2027d9762cf1622d34e48c34ff645a51bd27b4935af732'
AND original_filename <> '6f843a9ee4681fd353e0f73181eb4c4e242ee27f.jpg';

UPDATE media_asset SET original_filename = 'fe3d61dc5d6651dfc6a7648735d2fc7d41b13f56.jpg' WHERE sha256 = '4147e12059d04af84878a7bb1cfa8bc1479a247e61ed4b108dd3e14e88ab7508'
AND original_filename <> 'fe3d61dc5d6651dfc6a7648735d2fc7d41b13f56.jpg';

UPDATE media_asset SET original_filename = '1a05c677d328ee19ec506239ff6c20ac6fc91828.jpg' WHERE sha256 = 'cb37cbda5504b2c19d50259d6a79e2740aa07a17b0d238465e0050329442c3b9'
AND original_filename <> '1a05c677d328ee19ec506239ff6c20ac6fc91828.jpg';

UPDATE media_asset SET original_filename = 'f70ee622944c8cadd20cb8cc363f8986128780a4.jpg' WHERE sha256 = '5081b594ad156f5fe220e5884319a014d457bc339b79e51985ea1deb8dc2ba34'
AND original_filename <> 'f70ee622944c8cadd20cb8cc363f8986128780a4.jpg';

UPDATE media_asset SET original_filename = '09854c1b7c199e7cef26537b53ccd6bffd77d5fb.jpg' WHERE sha256 = '7dc6bcd540264bd1aa3afa6a290874b52bd103aa68126392c08fffcfb637a935'
AND original_filename <> '09854c1b7c199e7cef26537b53ccd6bffd77d5fb.jpg';

UPDATE media_asset SET original_filename = '6a80de6f056a1942c852c623f49c0024a3ee5ffa.jpg' WHERE sha256 = '88ebd0b3c1b36f7edec6d9101afbc606758a00efc9d8fb95e4880013bc3e9710'
AND original_filename <> '6a80de6f056a1942c852c623f49c0024a3ee5ffa.jpg';

UPDATE media_asset SET original_filename = 'e41125af2a46f1b194df84ee15b179c4cfc1028b.jpg' WHERE sha256 = '6d106efb6b1eb70d28b7c8c835cf5b5c3627e533dde126173302f006a24b18b5'
AND original_filename <> 'e41125af2a46f1b194df84ee15b179c4cfc1028b.jpg';

UPDATE media_asset SET original_filename = 'f0fa4516300e5295052bb9e5b6ebe28a3bdddd6e.jpg' WHERE sha256 = '9a1fe5b7e2ece8b7ca6032208980e026a38af41c8976d82c1b8bf346962428e0'
AND original_filename <> 'f0fa4516300e5295052bb9e5b6ebe28a3bdddd6e.jpg';

UPDATE media_asset SET original_filename = '16b22119fc669bee4f9dba0a91eef5ac82a6cc36.jpg' WHERE sha256 = '04e633ca88a7aec6ba1b81f384670cb552c0c5a270eefd26711e201c47a49441'
AND original_filename <> '16b22119fc669bee4f9dba0a91eef5ac82a6cc36.jpg';

UPDATE media_asset SET original_filename = '4667e1f61cd228a9975afdd6c70c1c86d8d56a9b.jpg' WHERE sha256 = 'bf56adf56022a8653b9464431ab319eeb0d1ff87c15cff5e5e06bd4dc9a412e5'
AND original_filename <> '4667e1f61cd228a9975afdd6c70c1c86d8d56a9b.jpg';

UPDATE media_asset SET original_filename = '525bf5df8b8990ac9d32925c2399bca6d7892f56.jpg' WHERE sha256 = '98d5611875a71a58030cceb6d7109e99435f7deb24748b82a49388898aaa22ae'
AND original_filename <> '525bf5df8b8990ac9d32925c2399bca6d7892f56.jpg';

UPDATE media_asset SET original_filename = '5857201de8b1492c4f72079bda93a94390d6c2b6.jpg' WHERE sha256 = '39f3ecf508092d208da622c6462231f8c98e16c48c65f9071aa381cbf6105042'
AND original_filename <> '5857201de8b1492c4f72079bda93a94390d6c2b6.jpg';

UPDATE media_asset SET original_filename = 'aa81f3e17f8da078901e6fcbbfe698db32f969c3.jpg' WHERE sha256 = '8144562611f4f88a6875d5dfbbd6443c06a295087669d3bb31ff73301800954e'
AND original_filename <> 'aa81f3e17f8da078901e6fcbbfe698db32f969c3.jpg';

UPDATE media_asset SET original_filename = '为迎接93大阅兵，停工半日，邀请全员工停下脚步，缅怀历史-图片-1.webp' WHERE sha256 = '92dc806c820fa9204db68c200635641c2657e207336a2b103dac56d9ec99bc5e'
AND original_filename <> '为迎接93大阅兵，停工半日，邀请全员工停下脚步，缅怀历史-图片-1.webp';

UPDATE media_asset SET original_filename = '为迎接93大阅兵，停工半日，邀请全员工停下脚步，缅怀历史-图片-1.webp' WHERE sha256 = '179e1e7a06ffdc1956618130dc2be4b1fb82e5c10914514ecb0dc45ededef472'
AND original_filename <> '为迎接93大阅兵，停工半日，邀请全员工停下脚步，缅怀历史-图片-1.webp';

UPDATE media_asset SET original_filename = '为迎接93大阅兵，停工半日，邀请全员工停下脚步，缅怀历史-图片-1.webp' WHERE sha256 = 'f12f3af66d2b494b3b25347440803ed71cd0aa15436b4ebf2371661a9066b1b9'
AND original_filename <> '为迎接93大阅兵，停工半日，邀请全员工停下脚步，缅怀历史-图片-1.webp';

UPDATE media_asset SET original_filename = '0dc754ea93decd11f298f1ae1af330c61f29675e.jpg' WHERE sha256 = '9a5044ffcc80fda8e9c5a1c9b527a9ac86f950b0aa5e159c8c5d476255db7994'
AND original_filename <> '0dc754ea93decd11f298f1ae1af330c61f29675e.jpg';

UPDATE media_asset SET original_filename = '4f8fab343315e5d1bf914bde2dcbcc2baad1b6ca.jpg' WHERE sha256 = 'a88e74443e8d2ef593915e286fe6e9d062ea040b622dda6daed375b2762e134f'
AND original_filename <> '4f8fab343315e5d1bf914bde2dcbcc2baad1b6ca.jpg';

UPDATE media_asset SET original_filename = '35266f8821ccd738080016b29c8c559727d7c425.jpg' WHERE sha256 = '162eff092bb955bdaa72b96038e77e57d493b32ad38c1ea556eaa909bab833c4'
AND original_filename <> '35266f8821ccd738080016b29c8c559727d7c425.jpg';

UPDATE media_asset SET original_filename = '172a7bb4322c89aca0f09560aea1d87caa72833a.jpg' WHERE sha256 = '6f4b5e0c898c931a1aeee9ca56dc412da869d40f827b943b184036533f256778'
AND original_filename <> '172a7bb4322c89aca0f09560aea1d87caa72833a.jpg';

UPDATE media_asset SET original_filename = '95f45e18dd83eeb0f531521d76591572e0121da3.jpg' WHERE sha256 = 'b36f8de1b138080f1b4643fba1bfbe542c6b69420bd09294ebb101e6aa333bd0'
AND original_filename <> '95f45e18dd83eeb0f531521d76591572e0121da3.jpg';

UPDATE media_asset SET original_filename = 'a5d8d8ecdc7f5a25be71fe234c4b829b17a41212.jpg' WHERE sha256 = '40719704d453e4866752edece0ced389882742491b0125736310786dbd6cb9cd'
AND original_filename <> 'a5d8d8ecdc7f5a25be71fe234c4b829b17a41212.jpg';

UPDATE media_asset SET original_filename = '64396fab0776febddb7d35121ad61086084cfb56.jpg' WHERE sha256 = '63b9188a6cf11da6d6fea9d5775e75d6ecfc0b8114f14313f70be16274619fdb'
AND original_filename <> '64396fab0776febddb7d35121ad61086084cfb56.jpg';

UPDATE media_asset SET original_filename = '2e12edcebe09eaf4cdf7ed0abacc3025fa7b8f32.jpg' WHERE sha256 = '8116d998386e6e1611f0a87388b40592c3a215e3380194055b2e89795a6e99ee'
AND original_filename <> '2e12edcebe09eaf4cdf7ed0abacc3025fa7b8f32.jpg';

UPDATE media_asset SET original_filename = '630bc624b5a631fa9f07b48cb854af44bf8893d6.jpg' WHERE sha256 = '13d782f5ab0475069c511580291aa742ea8513abb319d40c2b06c0b7f09201d6'
AND original_filename <> '630bc624b5a631fa9f07b48cb854af44bf8893d6.jpg';

UPDATE media_asset SET original_filename = '59d954f396cee6b5a60428294b1e1ef8659c8946.jpg' WHERE sha256 = '9885ea9580c93ddc6417dfb754da7aa456acc31cd54446db3b76e192a278c2e0'
AND original_filename <> '59d954f396cee6b5a60428294b1e1ef8659c8946.jpg';

UPDATE media_asset SET original_filename = '8568e9f647d6ab9da558c90e9ee8658757b8126e.jpg' WHERE sha256 = '76052bf8b6173514e21c5d67f5bb27cc8d1d0adfa70cdf7a37d7abd4a0e529c6'
AND original_filename <> '8568e9f647d6ab9da558c90e9ee8658757b8126e.jpg';

UPDATE media_asset SET original_filename = '79a4cc97cc3928f9607add0d54300b71b632944f.jpg' WHERE sha256 = 'cf042c0caacd5141c0f4240cfef2fa2da3e35dfd903116cd536fbe4a1b9fb18e'
AND original_filename <> '79a4cc97cc3928f9607add0d54300b71b632944f.jpg';

UPDATE media_asset SET original_filename = '6afed9a77b469c2f525444dfa38f85b7fe591ed4.jpg' WHERE sha256 = '3e44e75465ab6f1108018cbdac493f49aecc958cba1a2c251d5a7f0adcb6d873'
AND original_filename <> '6afed9a77b469c2f525444dfa38f85b7fe591ed4.jpg';

UPDATE media_asset SET original_filename = 'efaa30d11166ca503de07f69dddc397094de73ab.jpg' WHERE sha256 = '54188c152ecfd61f2821d95ad6da946f2e02d89bddcd963c3071079772c9e501'
AND original_filename <> 'efaa30d11166ca503de07f69dddc397094de73ab.jpg';

UPDATE media_asset SET original_filename = '0eb11bc03922499f553dbb8a9930ad35401db75b.jpg' WHERE sha256 = '22d5fe340efac51b3abb5edfd002e58ef7424abc4da85c3476e423c9efa2e7eb'
AND original_filename <> '0eb11bc03922499f553dbb8a9930ad35401db75b.jpg';

UPDATE media_asset SET original_filename = '7c0d93e3dd98ba5d02f1f6d73920ee4fe26bed09.jpg' WHERE sha256 = 'e3031aecc7d6a4cd49b59ae390b21a333b0c3e038111fe1a57dc20d4c44e55c4'
AND original_filename <> '7c0d93e3dd98ba5d02f1f6d73920ee4fe26bed09.jpg';

UPDATE media_asset SET original_filename = '824598756e3471a30dc4e1d3c5b994d33c4b0c93.jpg' WHERE sha256 = '8db0ada5a32ea82e30ae92f52951de37c563484b6a0febcb4961526ea158384c'
AND original_filename <> '824598756e3471a30dc4e1d3c5b994d33c4b0c93.jpg';

UPDATE media_asset SET original_filename = 'f24906851d48b9fefc3f79e5bc5cf006b0d1027c.jpg' WHERE sha256 = 'e831bf2a320799c8cfa1ab21cfdaefd4f12638c4e255da563f92dd83edde2829'
AND original_filename <> 'f24906851d48b9fefc3f79e5bc5cf006b0d1027c.jpg';

UPDATE media_asset SET original_filename = 'bdc2c2e7c0323364fd848701dad7ce7cf4631f3d.jpg' WHERE sha256 = '02a81b767e7dacdc93dc6a7ed183079edc624afc538e4191de70c14303a344d3'
AND original_filename <> 'bdc2c2e7c0323364fd848701dad7ce7cf4631f3d.jpg';

UPDATE media_asset SET original_filename = '5573cdf084e1f7985d0507d268cd91ce3820dfce.jpg' WHERE sha256 = 'b15d11a0665253237f85b500e1c0abf39fae40fcc2628ee7432d3accd5ecbad8'
AND original_filename <> '5573cdf084e1f7985d0507d268cd91ce3820dfce.jpg';

UPDATE media_asset SET original_filename = 'ed32b0458e938236f45ab1af4111f3eb0c6b673d.jpg' WHERE sha256 = 'c33981e96e6a73ea9bbc9a6c0466171f8db3e7e9fac80c81bb8595dad3128a80'
AND original_filename <> 'ed32b0458e938236f45ab1af4111f3eb0c6b673d.jpg';

UPDATE media_asset SET original_filename = '6f5c7031d5577558ea1d868b1d52f9fc2342a206.jpg' WHERE sha256 = 'ff2ea9c9eb697bbaf7c04d59638fa720ff9d8feae6ca16b4854af25f3d45b682'
AND original_filename <> '6f5c7031d5577558ea1d868b1d52f9fc2342a206.jpg';

UPDATE media_asset SET original_filename = '3df9560d2570259d1a507890760054be2737b5dd.jpg' WHERE sha256 = '571c747b44691cb6136be03c1047d10e99c16c76d4c7e262e960aa29a8f155ef'
AND original_filename <> '3df9560d2570259d1a507890760054be2737b5dd.jpg';

UPDATE media_asset SET original_filename = '35261389a5c1477633d1ca3bf07fdc7a41c82ac8.jpg' WHERE sha256 = '3867ea32342d804f49b9ebad6c76d83b7e48781027e12a173c7120e9218b2fbe'
AND original_filename <> '35261389a5c1477633d1ca3bf07fdc7a41c82ac8.jpg';

UPDATE media_asset SET original_filename = '62c550d90009417ef45ae6e394e3569d88f1e552.jpg' WHERE sha256 = '3bbfd92f9c79e0479eb0cf15b2b3b1c6a9b3a9b259e8f3c5e4d6a7433d5568f5'
AND original_filename <> '62c550d90009417ef45ae6e394e3569d88f1e552.jpg';

UPDATE media_asset SET original_filename = 'ca9f186ed299b193f9f23b4a4f8a25923747b591.jpg' WHERE sha256 = 'a54e35c5aed01bc5464ab1e5243055ad8d7c5bf0ea6f07464fe8e75cad1eeae2'
AND original_filename <> 'ca9f186ed299b193f9f23b4a4f8a25923747b591.jpg';

UPDATE media_asset SET original_filename = '08d95af8fe188456c75b5aeebacfca865a9633b8.jpg' WHERE sha256 = '20a7a7218a6a9993a6b537d0268f40738ed4e9c1069e2f36714d2fe301d1980c'
AND original_filename <> '08d95af8fe188456c75b5aeebacfca865a9633b8.jpg';

UPDATE media_asset SET original_filename = 'fde7d0167eb5e453d2528dfeb8b5affd0d642214.jpg' WHERE sha256 = '6f2930b1badf2b02eec34500ca11320c08d95b4e1c260281409f661bb4d2de70'
AND original_filename <> 'fde7d0167eb5e453d2528dfeb8b5affd0d642214.jpg';

UPDATE media_asset SET original_filename = 'c27f49a0c262fff16c247a1d19de36da591a59a9.jpg' WHERE sha256 = 'cfb4d2d7e2cba96f1a844a2070ecb03f37f42c22d6330c6145f4e3cec15ce55d'
AND original_filename <> 'c27f49a0c262fff16c247a1d19de36da591a59a9.jpg';

UPDATE media_asset SET original_filename = '9dffaa25e5c8f7d680189439ea6a0aacc6b98aeb.jpg' WHERE sha256 = '240327f0701a173d042f3e6bf688ad250c40a0d7f65015e6b93718c07d91bd82'
AND original_filename <> '9dffaa25e5c8f7d680189439ea6a0aacc6b98aeb.jpg';

UPDATE media_asset SET original_filename = '08a92d71654c24237f1be38f6e100d36125bf382.jpg' WHERE sha256 = 'de17c7ce84d40d2b98fe2185031303981cc5deb8e8dbda493ea8cd172d3a9703'
AND original_filename <> '08a92d71654c24237f1be38f6e100d36125bf382.jpg';

UPDATE media_asset SET original_filename = '13b961ad3ffb7fa5ea58aa98c08af5d852dad943.jpg' WHERE sha256 = '50ef60e4bd151be342a13c39867b3bba438e2d7e9b860f744c66b4f873c50f7f'
AND original_filename <> '13b961ad3ffb7fa5ea58aa98c08af5d852dad943.jpg';

UPDATE media_asset SET original_filename = '3cd708b601fd7c11973771f0a8226a5192d55895.jpg' WHERE sha256 = '41e69929821a034ebf01ef8352a307cd308e8aa3799bffae46efec98713a9b5c'
AND original_filename <> '3cd708b601fd7c11973771f0a8226a5192d55895.jpg';

UPDATE media_asset SET original_filename = '1cc064d81db1ac320706bf3cbd0b37fbd2ad9490.jpg' WHERE sha256 = 'de8d83c2ad31f6b920f2b9e8759785433fd26fd578abaec5e5b8be2198980408'
AND original_filename <> '1cc064d81db1ac320706bf3cbd0b37fbd2ad9490.jpg';

UPDATE media_asset SET original_filename = '789bdf09ba90f91b2ce277bffe75760f2285e42b.jpg' WHERE sha256 = '8418a050bbc0d7c6b5a346a23a2d2dc88e6ce5ff0e7aca7133f6090c7649f4c3'
AND original_filename <> '789bdf09ba90f91b2ce277bffe75760f2285e42b.jpg';

UPDATE media_asset SET original_filename = '2f2a2e91fc92be639c3633e1ce9b74a1a86f6146.jpg' WHERE sha256 = '6aac77bd0615ad2fe68dbd5a47e85add894591f8f4a54cbc7ac1782c0b9628a6'
AND original_filename <> '2f2a2e91fc92be639c3633e1ce9b74a1a86f6146.jpg';

UPDATE media_asset SET original_filename = 'e2f307a316eb544a286ce5bf06ac39095281e743.jpg' WHERE sha256 = 'fb580cce639fa0ec2890bb98431c08f5b8138c19ec4cd44f58240faa74b988c4'
AND original_filename <> 'e2f307a316eb544a286ce5bf06ac39095281e743.jpg';

UPDATE media_asset SET original_filename = '8bc82eb734393612ba767380042db3308c535bf8.jpg' WHERE sha256 = '0967948faa2dd2db272dfd38a257aab293fadf9d0437acf23ceabc087db3e033'
AND original_filename <> '8bc82eb734393612ba767380042db3308c535bf8.jpg';

UPDATE media_asset SET original_filename = '92011ebcd34073e82a418b647e4e9a98c2436eaa.jpg' WHERE sha256 = '0e7aa80a83cd56c14f8dc8819e6e5912c8ad824aad0eb513cc7d63b6266f929d'
AND original_filename <> '92011ebcd34073e82a418b647e4e9a98c2436eaa.jpg';

UPDATE media_asset SET original_filename = 'c5700e44cdd6d147a9fc1de968c9ce53a8905462.jpg' WHERE sha256 = '22347afe66acc3f2a3970b2197611a51a1ddd1373dddd39dce1b9cd964183c85'
AND original_filename <> 'c5700e44cdd6d147a9fc1de968c9ce53a8905462.jpg';

UPDATE media_asset SET original_filename = 'd31c98d95dc31fa9a81c657855590438fb858447.jpg' WHERE sha256 = 'b222718ee8eb4bf50ce3e4045c766d2f20fe487288d9c51e5b2576f2c46f3a8e'
AND original_filename <> 'd31c98d95dc31fa9a81c657855590438fb858447.jpg';

UPDATE media_asset SET original_filename = '8c165e99151c393b4bfb3eefd0841005b2647643.jpg' WHERE sha256 = '35be60653a1a8c11de7a79225f20bc6808fbbd2d2c2c357982acc3cd7aea912f'
AND original_filename <> '8c165e99151c393b4bfb3eefd0841005b2647643.jpg';

UPDATE media_asset SET original_filename = 'f7da869f053626ed74be7491107177160aae9755.jpg' WHERE sha256 = 'd3960254f6f14b7a6a1833d2d916173519c5a36fba90d56ed03b81e25c9796ac'
AND original_filename <> 'f7da869f053626ed74be7491107177160aae9755.jpg';

UPDATE media_asset SET original_filename = '73675c6cd76a92bae16a06b03804b8db6e1ea8e4.jpg' WHERE sha256 = '2caa863d178b2f72535819c830117d4614f69901482e9b907102dcf33f213db4'
AND original_filename <> '73675c6cd76a92bae16a06b03804b8db6e1ea8e4.jpg';

UPDATE media_asset SET original_filename = '4e1889cf3110b8e812182f81671e70f97cb85f1a.jpg' WHERE sha256 = '40578a6d973dd49361dcc8e5ae4585220439d4652d7aa774d50a64a2b4e2654b'
AND original_filename <> '4e1889cf3110b8e812182f81671e70f97cb85f1a.jpg';

UPDATE media_asset SET original_filename = 'f1a1e01fea5135c6a217afed593675be4ae90c78.jpg' WHERE sha256 = '596d986bad092e0f5668d0818886f86bdbe55cd6bf8f43e3046ae47e33145cf3'
AND original_filename <> 'f1a1e01fea5135c6a217afed593675be4ae90c78.jpg';

UPDATE media_asset SET original_filename = '022b9c4acb5775dfdf02d5822fda6ad375fdcb21.jpg' WHERE sha256 = '2fa658386565db34d45fa26798ed5c9dc1a260c05b22282ba215ceacbae797aa'
AND original_filename <> '022b9c4acb5775dfdf02d5822fda6ad375fdcb21.jpg';

UPDATE media_asset SET original_filename = '0686ac74eff6b847ca6c5973ba26b591d2d57b83.jpg' WHERE sha256 = 'db2c29022a773680202c0709342373eed298b02359ebb0a38d2bbc929ade88fd'
AND original_filename <> '0686ac74eff6b847ca6c5973ba26b591d2d57b83.jpg';

UPDATE media_asset SET original_filename = 'f5090f36652953519e279a8df9575c176419e7c7.jpg' WHERE sha256 = '84f5799c042bd025fd2ff1b512f19caea799eedab9c81a0fc1ca44467e34d14f'
AND original_filename <> 'f5090f36652953519e279a8df9575c176419e7c7.jpg';

UPDATE media_asset SET original_filename = '8837e289703d1c1cd0e13057b11cf9ab8206f51c.jpg' WHERE sha256 = '2b9e65f83cf1244db1cb43cdd66b2a73ced7c356e68137c918ed6272c28ac34a'
AND original_filename <> '8837e289703d1c1cd0e13057b11cf9ab8206f51c.jpg';

UPDATE media_asset SET original_filename = '452d0d320d552a40cf34295dfb7acf8d0683ec30.jpg' WHERE sha256 = '0ae35d38ad61929290854a5139c5d1c118a4392bcca3e8c5197bbfd09948dab0'
AND original_filename <> '452d0d320d552a40cf34295dfb7acf8d0683ec30.jpg';

UPDATE media_asset SET original_filename = '9e7e35565056cfa57888a6b0f28b6fbfbdd78b81.jpg' WHERE sha256 = '3ab0c2c4276bed949121b5524f52797f19996dc0aa5de1bbad0a0dd462a3440f'
AND original_filename <> '9e7e35565056cfa57888a6b0f28b6fbfbdd78b81.jpg';

UPDATE media_asset SET original_filename = 'f627daa370ea0420003b8b3735300d693f6848fb.jpg' WHERE sha256 = '94a34b95caff1b763254ed4ae7d493b0eea0164c83b8278d01268b571f5e2dd3'
AND original_filename <> 'f627daa370ea0420003b8b3735300d693f6848fb.jpg';

UPDATE media_asset SET original_filename = 'fc532ecd67e4ea35438e1dd3274efcd64905d18c.jpg' WHERE sha256 = '329e160e75b91b9eb2aa4cfd9ae36ba3e7b213ec7fae325b06cdbb153c803be5'
AND original_filename <> 'fc532ecd67e4ea35438e1dd3274efcd64905d18c.jpg';

UPDATE media_asset SET original_filename = 'b19d7629c71ce775a4bcb46fd11d5cb79d50e69f.jpg' WHERE sha256 = '7d2e67eb730d476f5e4dabeb8e133afc645655e06a30193017a5c8430c47e774'
AND original_filename <> 'b19d7629c71ce775a4bcb46fd11d5cb79d50e69f.jpg';

UPDATE media_asset SET original_filename = '931815b9f5d950b7b12d662b328406f5bb4e7bd2.jpg' WHERE sha256 = 'ac1f5256f68fba13981237b8cff4940025e945df4143bd9101d6430d722e12d8'
AND original_filename <> '931815b9f5d950b7b12d662b328406f5bb4e7bd2.jpg';

UPDATE media_asset SET original_filename = '996869be01c5b779109dff90f5548e0087548a5d.jpg' WHERE sha256 = '612846ae45a345062e38f2381a022c7935cddde722549692a8b59b159e6a7ef5'
AND original_filename <> '996869be01c5b779109dff90f5548e0087548a5d.jpg';

UPDATE media_asset SET original_filename = 'eea6eb62271f1ce6a0a321b85da057e7bcdd0df8.jpg' WHERE sha256 = '69164e7c01be9da3161263f1e276c4c94be4df6e3656ce985f5d1f3333aaf93d'
AND original_filename <> 'eea6eb62271f1ce6a0a321b85da057e7bcdd0df8.jpg';

UPDATE media_asset SET original_filename = '76aec4f71139b4066b6b9a403e8a88a96a19c087.jpg' WHERE sha256 = '813c22954c4ce7876d86ab7fa8ed31a8712381620ae0d8a2bc969b43a76d67bd'
AND original_filename <> '76aec4f71139b4066b6b9a403e8a88a96a19c087.jpg';

UPDATE media_asset SET original_filename = 'fe51517a3154db2252277bcabc469aa2f09d8618.jpg' WHERE sha256 = 'f6ea61d4949c9c4f91720871df89b8cee4911e5b71242e8a3892628b3a526714'
AND original_filename <> 'fe51517a3154db2252277bcabc469aa2f09d8618.jpg';

UPDATE media_asset SET original_filename = 'ce95f3db57de4dd29fa3b38159644ff8eed1ac01.jpg' WHERE sha256 = 'b87e26308c1748d67c235fa6d87dc9f1abfc5d8d1035fb6af7221a89a592d65d'
AND original_filename <> 'ce95f3db57de4dd29fa3b38159644ff8eed1ac01.jpg';

UPDATE media_asset SET original_filename = '1b6c58f059df6b4236f57f2d72f2b265dd3edf13.jpg' WHERE sha256 = '982291b9eb1ae67c0f1599db194bfa0168b19d6a18cfbb1ea16c43f1c8af6cd2'
AND original_filename <> '1b6c58f059df6b4236f57f2d72f2b265dd3edf13.jpg';

UPDATE media_asset SET original_filename = '74dc8ba9bdf13d23c0728cb3a2da823f9395847a.jpg' WHERE sha256 = 'b303e6124ce25850cf7559081a30988f5e783b72ccfe2f8d27e9ab4a6c932b2c'
AND original_filename <> '74dc8ba9bdf13d23c0728cb3a2da823f9395847a.jpg';

UPDATE media_asset SET original_filename = '6d4c66ffb7351213e652a7a0f7bcfbd813caf891.jpg' WHERE sha256 = '605f907c146bc64e24b6f9675c58e5c02018404c06bb94e4a27f6f697e2bf12b'
AND original_filename <> '6d4c66ffb7351213e652a7a0f7bcfbd813caf891.jpg';

UPDATE media_asset SET original_filename = '53f379a54ea39a9cd0c807d388d707c5bc32330a.jpg' WHERE sha256 = 'e34b735886a91e4275d5eddc41f19fb864a2ae55b82ae7f9975f36bcd5c80cba'
AND original_filename <> '53f379a54ea39a9cd0c807d388d707c5bc32330a.jpg';

UPDATE media_asset SET original_filename = '18e8616f4a3767c7b510b3569b3b5a6dfdeccbb0.jpg' WHERE sha256 = '1903a369877ab932e2850ebe8494396b8c581ce4c743f69fbbadc71a0b82470a'
AND original_filename <> '18e8616f4a3767c7b510b3569b3b5a6dfdeccbb0.jpg';

UPDATE media_asset SET original_filename = 'a8cb06cee6a6a23ac0b5c4ef3e153c43fb601240.jpg' WHERE sha256 = '5a3d553817300d429c8973551f512c0b9896bc8938dccf434a1071b7323e1391'
AND original_filename <> 'a8cb06cee6a6a23ac0b5c4ef3e153c43fb601240.jpg';

UPDATE media_asset SET original_filename = 'db2fc241f02a365024a99f6adb9793cb5de3821f.jpg' WHERE sha256 = '02ecba2bb5bd94f8cc0afb473edfe1a4b7281bc57eb6e3357c3b6d5967733cbe'
AND original_filename <> 'db2fc241f02a365024a99f6adb9793cb5de3821f.jpg';

UPDATE media_asset SET original_filename = '646ceebe0c57b1c3a2dc12195f46717e01bf43bd.jpg' WHERE sha256 = 'f07701c47084bb445e0445296fbc9b0385d88bd83e6315ca74e1d0d3f657a39c'
AND original_filename <> '646ceebe0c57b1c3a2dc12195f46717e01bf43bd.jpg';

UPDATE media_asset SET original_filename = 'a3f3091c677c7f091fdba652ace58a77cf1962f2.jpg' WHERE sha256 = '67dc4507e1d0ef398fb66adce2d947191242801d399b1a710f60d975b81637c7'
AND original_filename <> 'a3f3091c677c7f091fdba652ace58a77cf1962f2.jpg';

UPDATE media_asset SET original_filename = '9f5c759c02e1bcc2baf31faeed02ea933e7fa9f5.jpg' WHERE sha256 = 'fb7ae9ccef8d7e800dc516e05c386010e402c4e1f066d20ba8686bfe8ea01df8'
AND original_filename <> '9f5c759c02e1bcc2baf31faeed02ea933e7fa9f5.jpg';

UPDATE media_asset SET original_filename = 'ab131e1209fddbfdd958aa6a5e7779bb01100a44.jpg' WHERE sha256 = 'e558b8b006dcaaff65147b76b077a829767e841963f81a49b672958bbc7e4d3b'
AND original_filename <> 'ab131e1209fddbfdd958aa6a5e7779bb01100a44.jpg';

UPDATE media_asset SET original_filename = 'a3ced8a7e1000c34e89668f46256068862444fdb.jpg' WHERE sha256 = '5a0f1b22815c4255eabdf39c276cc61d6065acb08322e59db90df67c8cfbc458'
AND original_filename <> 'a3ced8a7e1000c34e89668f46256068862444fdb.jpg';

UPDATE media_asset SET original_filename = 'a096c8aac5ffc5e1235e94636791bc3ac265b2af.jpg' WHERE sha256 = 'b8f12b8db5202222d4cffa7c94916bbbfb07dc1a9ef48887e1bb999977c88f5e'
AND original_filename <> 'a096c8aac5ffc5e1235e94636791bc3ac265b2af.jpg';

UPDATE media_asset SET original_filename = '40a62e42cd2277bc9cfeccbc893a6c6dfe69a69c.jpg' WHERE sha256 = 'e67746bbf7927ea30285986f5779c32e1ef276a630d5db6a14d10f47630500ab'
AND original_filename <> '40a62e42cd2277bc9cfeccbc893a6c6dfe69a69c.jpg';

UPDATE media_asset SET original_filename = '24b5ffaed5908d44ca10597ce308faddcbe389bc.jpg' WHERE sha256 = 'f78cd1e55842942b40ff9e465a9cf7b21fb8822184f8c1efeb75858f89274b74'
AND original_filename <> '24b5ffaed5908d44ca10597ce308faddcbe389bc.jpg';

UPDATE media_asset SET original_filename = 'ec42905662e9373ef60472774ef408aa09017d26.jpg' WHERE sha256 = 'cd3960c6d00acc4e657328b3351a4c079a06cd3245ba704c0f7b87de715dc50b'
AND original_filename <> 'ec42905662e9373ef60472774ef408aa09017d26.jpg';

UPDATE media_asset SET original_filename = 'c6eb9b6066c06c593b86dfa6daac5f40fdec7388.jpg' WHERE sha256 = '386df77f066d206150f46909f8a6e8f5895d79555f218ab5316d43c5d777d7b6'
AND original_filename <> 'c6eb9b6066c06c593b86dfa6daac5f40fdec7388.jpg';

UPDATE media_asset SET original_filename = 'fb22e84a6fbb39d8891d57ca43e553ed96b563d6.jpg' WHERE sha256 = '0fe5240cfa27b1345f3ceb0fd86b5bd5449189df14cd031d350561ee60f154db'
AND original_filename <> 'fb22e84a6fbb39d8891d57ca43e553ed96b563d6.jpg';

UPDATE media_asset SET original_filename = '743928550fd5640d9134ed535e348cd716f0efee.jpg' WHERE sha256 = '69d36d5afdb8fb591920428faae86410ecd35b7e6af8373869d0c461ccb4de28'
AND original_filename <> '743928550fd5640d9134ed535e348cd716f0efee.jpg';

UPDATE media_asset SET original_filename = '85fdb634556d79f2a47cce4a5ae34c4d2215299b.jpg' WHERE sha256 = '0c3ab5ac28dae3568bbb82114ae22cbc88fb24f4e4114ecd994565390262a9f9'
AND original_filename <> '85fdb634556d79f2a47cce4a5ae34c4d2215299b.jpg';

UPDATE media_asset SET original_filename = '1cfaddc961f5f6ff7981a27dec441d4b65d9d2e2.jpg' WHERE sha256 = 'adaeabf73cbaaec23155f6a4e50cbe06fa22e25e62a42b2a62611410809b35cd'
AND original_filename <> '1cfaddc961f5f6ff7981a27dec441d4b65d9d2e2.jpg';

UPDATE media_asset SET original_filename = '4d69c4a3dc57503e08b76c774135bfe83e8b1f51.jpg' WHERE sha256 = '1f026beb67630abcdbc341651b1c17591aa76261296a9fb118793765964eb4e9'
AND original_filename <> '4d69c4a3dc57503e08b76c774135bfe83e8b1f51.jpg';

UPDATE media_asset SET original_filename = 'b793d0e210e99c9b3c1b2d08b41e404bb0da0d6a.jpg' WHERE sha256 = '8f3e1ed0c50094e78b87910e5652f2d456d17e3a62b1fa049d9db4989c957f65'
AND original_filename <> 'b793d0e210e99c9b3c1b2d08b41e404bb0da0d6a.jpg';

UPDATE media_asset SET original_filename = '0310db58ae88d05e673f251788805cf6f0f38a57.jpg' WHERE sha256 = '2cd037cce2c3c16c3d33b1fbe4d9d46206633af2f8b4e082cea209c56a3e8b56'
AND original_filename <> '0310db58ae88d05e673f251788805cf6f0f38a57.jpg';

UPDATE media_asset SET original_filename = 'd20c0ae7c223c38c6587635f8cee465e78f458da.jpg' WHERE sha256 = 'edbe15f5bc4fc31b2dcf407c850c2c7fdd1d5338a3483c0094d5a98f35bcb402'
AND original_filename <> 'd20c0ae7c223c38c6587635f8cee465e78f458da.jpg';

UPDATE media_asset SET original_filename = 'e8775505ba0fe3eb97e7e4abc6b317e13fff57c6.jpg' WHERE sha256 = '65f60ba3af5e4009b04894590f1d6b6658ac444836607498d89992faef4a7f68'
AND original_filename <> 'e8775505ba0fe3eb97e7e4abc6b317e13fff57c6.jpg';

UPDATE media_asset SET original_filename = '8807e88c7bec2a3e6ca54896fc392d7fe5530b47.jpg' WHERE sha256 = '01d2f7ab2f35448805f23bd66b325233013dd63613e87c02085484865b4c0336'
AND original_filename <> '8807e88c7bec2a3e6ca54896fc392d7fe5530b47.jpg';

UPDATE media_asset SET original_filename = 'dea5736bedba81a1c731120b2f14e6e335e7d182.jpg' WHERE sha256 = '3297621019cd796a57722fa84454ca0ec599d798d59aeb6fddea441e4ea383d3'
AND original_filename <> 'dea5736bedba81a1c731120b2f14e6e335e7d182.jpg';

UPDATE media_asset SET original_filename = '576ba8f31f0278da0425bf3cf1d26bdaff5f5ba3.jpg' WHERE sha256 = '40afb25449cd6f45d113468d70d29209972fbcfa89e2a1e372b0ee927e9e6149'
AND original_filename <> '576ba8f31f0278da0425bf3cf1d26bdaff5f5ba3.jpg';

UPDATE media_asset SET original_filename = '2bbc478cba7cac7cc346862093538a2699c2bba8.jpg' WHERE sha256 = '2a82a2852b4b13a9d538747686c8da31bbf771717dd3fbc75b5687acf1a16c04'
AND original_filename <> '2bbc478cba7cac7cc346862093538a2699c2bba8.jpg';

UPDATE media_asset SET original_filename = '33b12e865f05b0f08b7cad4fef8fd7ee15fb7e92.jpg' WHERE sha256 = '8c75f56dc1f65d0704363df110e8988e950020ad68ff611b28d83e6af5c5bf50'
AND original_filename <> '33b12e865f05b0f08b7cad4fef8fd7ee15fb7e92.jpg';

UPDATE media_asset SET original_filename = '684e9294516c41eeee824dbda8d4b5e3c5aa12be.jpg' WHERE sha256 = '2950bdcf4d25b081dc6e32f20ca3e63a30013d0ea3f29ebe9d318a7a273732ae'
AND original_filename <> '684e9294516c41eeee824dbda8d4b5e3c5aa12be.jpg';

UPDATE media_asset SET original_filename = '962b2ec43913f605c3ea71499ef751368edd5092.jpg' WHERE sha256 = 'b5f6e946a4739632c3ff6fa5601b41944d9f2e3e37e69f0c548e98c36518cfc8'
AND original_filename <> '962b2ec43913f605c3ea71499ef751368edd5092.jpg';

UPDATE media_asset SET original_filename = 'b8b56c6c59f0d65b876c4d55e316df8d39196ad4.jpg' WHERE sha256 = 'be3509872165de3ed4ce52d53ea2e8d29791582a5c9243a3612dd723537d7634'
AND original_filename <> 'b8b56c6c59f0d65b876c4d55e316df8d39196ad4.jpg';

UPDATE media_asset SET original_filename = '727d7f94c54b49954f308ef2958c90c106f7dd15.jpg' WHERE sha256 = '6d41c48f0f2f76a61dab2ebb8178802403264904c2b732d0df8e13de9ae6c90f'
AND original_filename <> '727d7f94c54b49954f308ef2958c90c106f7dd15.jpg';

UPDATE media_asset SET original_filename = 'fcd72a2b3f44a66af242aef8655a6b659b57a066.jpg' WHERE sha256 = '1cb42714f8e63a830f7438e74e1fb3e15d0cf71158b96a04e85e253c45d61679'
AND original_filename <> 'fcd72a2b3f44a66af242aef8655a6b659b57a066.jpg';

UPDATE media_asset SET original_filename = 'a093a625dea832bc6144b5257db0b598363ed3d7.jpg' WHERE sha256 = '503f8da4bac1eff068fd94cc423320fb476d0219e617fcaf3316d2cc3b681d72'
AND original_filename <> 'a093a625dea832bc6144b5257db0b598363ed3d7.jpg';

UPDATE media_asset SET original_filename = 'c2423646bae9e71ba2f79d4fe53ab09fdc02549b.jpg' WHERE sha256 = '570116b43db3d19af81e3fe901ff1f074273ec3d767ed5d2e0c19ed33b211bf4'
AND original_filename <> 'c2423646bae9e71ba2f79d4fe53ab09fdc02549b.jpg';

UPDATE media_asset SET original_filename = '290c379cfc286a67f7c07a4a1bc49d82e5d43d17.jpg' WHERE sha256 = 'da689db6c1b672e61a9043aced0c245acce1025220b1b924782b4e4c0105e177'
AND original_filename <> '290c379cfc286a67f7c07a4a1bc49d82e5d43d17.jpg';

UPDATE media_asset SET original_filename = '529da750704ecfba4da177bb5f0e4ba9111c85b4.jpg' WHERE sha256 = 'a2813608280549205e99877d4aae63a3ad673d28329fad8cf8fc299fd58d8ea0'
AND original_filename <> '529da750704ecfba4da177bb5f0e4ba9111c85b4.jpg';

UPDATE media_asset SET original_filename = '0ba1b8810bd2b6f653ff89f59f7ed247a7c951f0.jpg' WHERE sha256 = 'c1537f3ce97b47a9ad281091248476b917ad113a6098be790d0a933ef4d24c93'
AND original_filename <> '0ba1b8810bd2b6f653ff89f59f7ed247a7c951f0.jpg';

UPDATE media_asset SET original_filename = 'e2eb523a2a3778e4340b8f434acedfaca1e0fc48.jpg' WHERE sha256 = '95f29c0a4d96b96a58212016a46d8698016d3c8ccbea92ca72ac4e94c52f49d4'
AND original_filename <> 'e2eb523a2a3778e4340b8f434acedfaca1e0fc48.jpg';

UPDATE media_asset SET original_filename = '1a9cbb439a4a3d5c45df0481cbd79df762f16c92.jpg' WHERE sha256 = 'b68af51de145c200d9e63a74b5a142efd5205f57f452b4873f8e95cdac4abaa2'
AND original_filename <> '1a9cbb439a4a3d5c45df0481cbd79df762f16c92.jpg';

UPDATE media_asset SET original_filename = 'c15ea7ac9fab1ebe73029539dd613e06689ac836.jpg' WHERE sha256 = '2810636c5c549a6bbda70c5d60b4a75b7e84f2949be60703069fb04a65110da2'
AND original_filename <> 'c15ea7ac9fab1ebe73029539dd613e06689ac836.jpg';

UPDATE media_asset SET original_filename = 'cb96e67c4be50b25a4aeb467d0b1b8b1fed31703.jpg' WHERE sha256 = '34db8330ecf6852dfb0020789cba46f647255388ffa4644c498934b2067e4e74'
AND original_filename <> 'cb96e67c4be50b25a4aeb467d0b1b8b1fed31703.jpg';

UPDATE media_asset SET original_filename = 'fcb03ef38f26f89294a6bd7fbd285ae11a3d41e6.jpg' WHERE sha256 = 'dee57025a7319a6f776a8c4ae7aec5ac45f92df199e6a37fd27693bb6bbe80ac'
AND original_filename <> 'fcb03ef38f26f89294a6bd7fbd285ae11a3d41e6.jpg';

UPDATE media_asset SET original_filename = '8defb3eed4b6649bb285a08cd02e7ead3a60893e.jpg' WHERE sha256 = '0f651b80cce969ca62ed7c9744e4cafacffa9c23fb5ffe690f09d59b0e3ae6fb'
AND original_filename <> '8defb3eed4b6649bb285a08cd02e7ead3a60893e.jpg';

UPDATE media_asset SET original_filename = '52e475421c0fee781008faf8cc96a1ca97daf9e1.jpg' WHERE sha256 = '15d8c1dfbcc99f4c3d708037c2c7702e3b786919134208921cb6ef024b4df127'
AND original_filename <> '52e475421c0fee781008faf8cc96a1ca97daf9e1.jpg';

UPDATE media_asset SET original_filename = 'f5559314d9b3ce04305d8a1d915e370540dc2fcd.jpg' WHERE sha256 = 'efa453189b974e5d7ad6ae483e92e6d58f890470c6fb4f32825adaeb8f31beec'
AND original_filename <> 'f5559314d9b3ce04305d8a1d915e370540dc2fcd.jpg';

UPDATE media_asset SET original_filename = '18618aae038a0ff0eff78e9322e17ef7d4d9aca0.jpg' WHERE sha256 = '6641b97ba65050a0fcda40921c60c4248f5c32a0d1748936d500eebedc72d794'
AND original_filename <> '18618aae038a0ff0eff78e9322e17ef7d4d9aca0.jpg';

UPDATE media_asset SET original_filename = '2a225d5102860818e4e5658e83ef5cccfc34fa96.jpg' WHERE sha256 = 'cd97208cd397799fc961c721b3a4c64ed7e894a524be4722e7023268373dd478'
AND original_filename <> '2a225d5102860818e4e5658e83ef5cccfc34fa96.jpg';

UPDATE media_asset SET original_filename = 'f56f13804a5dc5fde6cec4837edd3505b8e9fc83.jpg' WHERE sha256 = '8a4aebde9ac405f4ade0644d94c16530a7067201ec9fe8d0d656f5b7cddcdf76'
AND original_filename <> 'f56f13804a5dc5fde6cec4837edd3505b8e9fc83.jpg';

UPDATE media_asset SET original_filename = '5f18bcdeb95a43db2617b06e120bb7af487b4d1f.jpg' WHERE sha256 = 'b6c4a852ee76a57c0b4406b428cfe60b48d0eb5ed83a769fd17310b57ec0d85c'
AND original_filename <> '5f18bcdeb95a43db2617b06e120bb7af487b4d1f.jpg';

UPDATE media_asset SET original_filename = '105de3f6fb760e17f8bd20787708353cae7838b4.jpg' WHERE sha256 = '67333e01eb22054a6577f383b5575965065bb867bc9e1ca6fe00e4dc6b67c731'
AND original_filename <> '105de3f6fb760e17f8bd20787708353cae7838b4.jpg';

UPDATE media_asset SET original_filename = '2f5f3ea254ae796e419acaf3387905f89b8042aa.jpg' WHERE sha256 = '8e51654699db0544b721eaf58621d1cc335601aad8c556fc416c51fd0f56800d'
AND original_filename <> '2f5f3ea254ae796e419acaf3387905f89b8042aa.jpg';

UPDATE media_asset SET original_filename = '4e821048a78b915211a1af65183a73fb61fe4a1b.jpg' WHERE sha256 = '65f4575674b4608ee269612765597e212ebe8420f60a157101762c9998ef7daa'
AND original_filename <> '4e821048a78b915211a1af65183a73fb61fe4a1b.jpg';

UPDATE media_asset SET original_filename = '8ed66bb6ef4a5187d67e378ffa6250d0b58579c2.jpg' WHERE sha256 = '4c10fc60cf3fb832b63800717a700ca6601a3021d4bb118be10505d99c50f958'
AND original_filename <> '8ed66bb6ef4a5187d67e378ffa6250d0b58579c2.jpg';

UPDATE media_asset SET original_filename = '54e263a110cfd39033b6cb2ecf2818c4cae79890.jpg' WHERE sha256 = '57e164fae66a6d6aa514873b61870bd64313223f9163288f3f354251e0938562'
AND original_filename <> '54e263a110cfd39033b6cb2ecf2818c4cae79890.jpg';

UPDATE media_asset SET original_filename = 'c24e65e022e688649b8cff71f8d203842224ee20.jpg' WHERE sha256 = 'a0c5ae262c74094bad472e61f976b08a065f3ff85cf1a28a54167a6d2e000cc4'
AND original_filename <> 'c24e65e022e688649b8cff71f8d203842224ee20.jpg';

UPDATE media_asset SET original_filename = 'e16291546616ceee07543cf89927b3adbe8a3780.jpg' WHERE sha256 = '6885322521f8e09cda920a5bbcd247c76a8afc1f71a86fe25bb49da0f66ef916'
AND original_filename <> 'e16291546616ceee07543cf89927b3adbe8a3780.jpg';

UPDATE media_asset SET original_filename = '1c698e560aac279d9258466624dca95dedd98fde.jpg' WHERE sha256 = '272dba75b520ee21a0ccf2b7dc3c60d6b4a304aeb6d6f8a51018092d4c76ae71'
AND original_filename <> '1c698e560aac279d9258466624dca95dedd98fde.jpg';

UPDATE media_asset SET original_filename = '5d6da34129ac213136b5c5ec4130d62c6716ea66.jpg' WHERE sha256 = '576616aeb78f1f5e2bc15525f2809021d3299b44ea9a023d5b35e76c06da6903'
AND original_filename <> '5d6da34129ac213136b5c5ec4130d62c6716ea66.jpg';

UPDATE media_asset SET original_filename = '2cc0fe3975317e22e075d0ae48bbbd3581e29fcb.jpg' WHERE sha256 = '0e35ea8e416a23e58067156345f94c173f15a056d8bcdace4e598505a494f960'
AND original_filename <> '2cc0fe3975317e22e075d0ae48bbbd3581e29fcb.jpg';

UPDATE media_asset SET original_filename = 'a456f304f3466dddba08db1db0728d5a8e737959.jpg' WHERE sha256 = '0ed274f765b09c382ff3c0ba44fd7a9c5c17ecea74538ed4a570aa8b457d709d'
AND original_filename <> 'a456f304f3466dddba08db1db0728d5a8e737959.jpg';

UPDATE media_asset SET original_filename = 'acb6f6334047a70689b4c75fdb1b9a5d2997a443.jpg' WHERE sha256 = '07bded19b59021c7e09f6aca19d81e4eb10fe125619323417478cc218d1b47fc'
AND original_filename <> 'acb6f6334047a70689b4c75fdb1b9a5d2997a443.jpg';

UPDATE media_asset SET original_filename = '352323833e7a554af0f37e6c86faec3fc8168059.jpg' WHERE sha256 = '4f0c9457fd6298ea4c217c1b4395574e679c3f17d7a49de8d806644a56749983'
AND original_filename <> '352323833e7a554af0f37e6c86faec3fc8168059.jpg';

UPDATE media_asset SET original_filename = '41cdd2deba7b1b9bbf3016606bef7b5e647460bd.jpg' WHERE sha256 = '832ff496b5d738b4bca460f893d4fa998a8b7705b7e00fc4e4a246c7172f9f9d'
AND original_filename <> '41cdd2deba7b1b9bbf3016606bef7b5e647460bd.jpg';

UPDATE media_asset SET original_filename = 'ba4264441c1368cc5188f731b0cc0c35419ac98e.jpg' WHERE sha256 = 'dd3417ff41824dd61b8d1e9d416cbcc4ee78879b6102d7c6b06e15ac2bee4524'
AND original_filename <> 'ba4264441c1368cc5188f731b0cc0c35419ac98e.jpg';

UPDATE media_asset SET original_filename = 'eda653f5087bc54b6fa952baa52693aa403a86ac.jpg' WHERE sha256 = '6420c158445c3f125c28e939709986f44d559f0808830cd2e1b8b6d12f726718'
AND original_filename <> 'eda653f5087bc54b6fa952baa52693aa403a86ac.jpg';

UPDATE media_asset SET original_filename = 'bf88d38db0e08043e9e8c574d5e9e5f7405a942e.jpg' WHERE sha256 = 'e7004cbdc2d4dcb64c5d8e5a08596469db1df527030149983e28dd819556b2e5'
AND original_filename <> 'bf88d38db0e08043e9e8c574d5e9e5f7405a942e.jpg';

UPDATE media_asset SET original_filename = 'd1ab666f14998cd13d2d3c1fdbd703ef2260bd39.jpg' WHERE sha256 = 'b167c26557bdfb73f3f8a675c68c5fd2ac76f19d93173ea0ff1ef83239fc9943'
AND original_filename <> 'd1ab666f14998cd13d2d3c1fdbd703ef2260bd39.jpg';

UPDATE media_asset SET original_filename = 'df8d5c65f8c371a160541f211d90023b9ecbfc47.jpg' WHERE sha256 = '0e71a82093433dc2bf4ac5691d0796f9addd14d0f2dfffa8e6eccf4145800756'
AND original_filename <> 'df8d5c65f8c371a160541f211d90023b9ecbfc47.jpg';

UPDATE media_asset SET original_filename = '2c52e5451a96457509255a4d5678b23221b6d39b.jpg' WHERE sha256 = 'df43b79ebfe6c51f36a451a12cadf57c63bc011b9b25c45a9411b28179d428af'
AND original_filename <> '2c52e5451a96457509255a4d5678b23221b6d39b.jpg';

UPDATE media_asset SET original_filename = '231ac3a799bd2f43e9ba4631cf5cfde35c947268.jpg' WHERE sha256 = '7d851d4b879e60d9d0bb91f67cf8c430107f2b34c683b53ec2b818ed8c5ecbc8'
AND original_filename <> '231ac3a799bd2f43e9ba4631cf5cfde35c947268.jpg';

UPDATE media_asset SET original_filename = 'f39440e71bff5aa439d1cc38acbd3c066907f7df.jpg' WHERE sha256 = '60b0b77dc5d657deffe5c9cf6c69440e8e5bdc8f99350160975eada6d659bf4d'
AND original_filename <> 'f39440e71bff5aa439d1cc38acbd3c066907f7df.jpg';

UPDATE media_asset SET original_filename = 'eef50e7f36570b2d0113af8fc139e9a31309174b.jpg' WHERE sha256 = '4d36c83b39673e6fcf32c98b4d39defe05d7e8c6a94560a1f4da64e5124ef000'
AND original_filename <> 'eef50e7f36570b2d0113af8fc139e9a31309174b.jpg';

UPDATE media_asset SET original_filename = 'e76104a3739ced90ffa6961ebe070723a52921fd.jpg' WHERE sha256 = '7f656d32c8c84488b96a047f9c004c3735d94deab97d05dc250988a459c4bae0'
AND original_filename <> 'e76104a3739ced90ffa6961ebe070723a52921fd.jpg';

UPDATE media_asset SET original_filename = '088a59cc3132e5efffab80ca920ef6ccdabfcd3d.jpg' WHERE sha256 = 'c12e9d17354ef683fe90a62944a8810eea629b3e6412a72d4480a02c7f6548b4'
AND original_filename <> '088a59cc3132e5efffab80ca920ef6ccdabfcd3d.jpg';

UPDATE media_asset SET original_filename = 'cd4b18300d68b084dc91694a89c1da5992f259cd.jpg' WHERE sha256 = '6b888a94a6c2d65de193771f8582f348305a330de81d89ce03b49cb77ff933fe'
AND original_filename <> 'cd4b18300d68b084dc91694a89c1da5992f259cd.jpg';

UPDATE media_asset SET original_filename = '3ce41e0c7a966d6903b3924a6a03b42f0009a084.jpg' WHERE sha256 = '6901371be338f0d95b33898576b86c0bfb63ad80fc2f26800d351b4ae0be20c6'
AND original_filename <> '3ce41e0c7a966d6903b3924a6a03b42f0009a084.jpg';

UPDATE media_asset SET original_filename = '8836255de9460307408ff7a914eff39ce9cc7679.jpg' WHERE sha256 = 'fc28b92248bebf01a53e3abec338cf8e1925f019dda63f9172b4e81a615e5f0c'
AND original_filename <> '8836255de9460307408ff7a914eff39ce9cc7679.jpg';

UPDATE media_asset SET original_filename = '2722612a46806abf6ddd41d67357b78b187290be.jpg' WHERE sha256 = 'b4d857438b1dea381361ad32d245a7c2fc79c6fbd28495494a45caa2dd387f7c'
AND original_filename <> '2722612a46806abf6ddd41d67357b78b187290be.jpg';

UPDATE media_asset SET original_filename = '46cc4e4d8ea5d11fc7aeaa5decc87cff59d121ef.jpg' WHERE sha256 = '4b358431828e78d547f8c39684e1c20aa899d660ad0eb03b8dc923cc55e7d98e'
AND original_filename <> '46cc4e4d8ea5d11fc7aeaa5decc87cff59d121ef.jpg';

UPDATE media_asset SET original_filename = 'c1661a4b1941d130adcb76deea9140d5cb26943d.jpg' WHERE sha256 = '7c77c37ce1fba5eb82397fe418ebfb57ddb8718b0122b7fa3e55da86109f22f4'
AND original_filename <> 'c1661a4b1941d130adcb76deea9140d5cb26943d.jpg';

UPDATE media_asset SET original_filename = '4cbb1e1784ad735ac4f0616c8b1f1d231255bdd2.jpg' WHERE sha256 = '5350c394bc8859eabf63c374938ec2ec6e08cf26b833be4f28a50b0e12a3c963'
AND original_filename <> '4cbb1e1784ad735ac4f0616c8b1f1d231255bdd2.jpg';

UPDATE media_asset SET original_filename = '43fe23121d13f43259d4bb22590821905e60b19a.jpg' WHERE sha256 = '3d23bb67745d4f7e565dd00897154a5e4df1040931918b3872bc6d51833f950d'
AND original_filename <> '43fe23121d13f43259d4bb22590821905e60b19a.jpg';

UPDATE media_asset SET original_filename = '730353492529a317bc420cce0fce6d97b6571d4c.jpg' WHERE sha256 = 'b0bdfaf2bed52f0c6bb954295e453ea5e057a5668621f5d26d1b68dafa0dca73'
AND original_filename <> '730353492529a317bc420cce0fce6d97b6571d4c.jpg';

UPDATE media_asset SET original_filename = 'c243b24c01411df9bfe54cd1e6f05db0aaa2eb94.jpg' WHERE sha256 = '685211e588da57d3ec3606fa48c68a7321670ae55f4657434a7187575570ca7e'
AND original_filename <> 'c243b24c01411df9bfe54cd1e6f05db0aaa2eb94.jpg';

UPDATE media_asset SET original_filename = 'ef7702327333cfc86befe255f192cefddfa94923.jpg' WHERE sha256 = 'ab967b9e70d9fe5f3737ea96e37a6f3a9925f166af8f8fbd402bc907d0358fa1'
AND original_filename <> 'ef7702327333cfc86befe255f192cefddfa94923.jpg';

UPDATE media_asset SET original_filename = '5cbe7ab11bdf2f6783cf6abef566f895c62ce7ad.jpg' WHERE sha256 = 'c3a6329733d0cc53cc0104bae7506a77a80d671f3c8953f3f5b1120af26c0015'
AND original_filename <> '5cbe7ab11bdf2f6783cf6abef566f895c62ce7ad.jpg';

UPDATE media_asset SET original_filename = '652998973a293cb8087141a47dff48a0e3c0ae10.jpg' WHERE sha256 = 'bb1790bbb629b092ec881aabbdaed3438789e2100af38f5fe5b01aa8f4297880'
AND original_filename <> '652998973a293cb8087141a47dff48a0e3c0ae10.jpg';

UPDATE media_asset SET original_filename = 'f0b5eb33f654ae4a1c9c32d1a7e218a22dfc758b.jpg' WHERE sha256 = '1a5853b0e1fd0d044461f6766f21209d2ef0950595461cee083ba47fe07970d8'
AND original_filename <> 'f0b5eb33f654ae4a1c9c32d1a7e218a22dfc758b.jpg';

UPDATE media_asset SET original_filename = '0b26f65fbacb0f6a71c7399b1b75affa9c7e026c.jpg' WHERE sha256 = '83e6e1d8c6a4f5469f49f51d5b018aa67bc4f7e90094377f3d6a08905f65e2d7'
AND original_filename <> '0b26f65fbacb0f6a71c7399b1b75affa9c7e026c.jpg';

UPDATE media_asset SET original_filename = 'b90387e5f8b8402c2df5fc0823d995bb976c5389.jpg' WHERE sha256 = 'ceac23b459a816475f7ae60257e6e76b768682fbcc4ee48475583c48a15d17ed'
AND original_filename <> 'b90387e5f8b8402c2df5fc0823d995bb976c5389.jpg';

UPDATE media_asset SET original_filename = '90480a6d4ea312119fd7e32ca4afa673b6a9437b.jpg' WHERE sha256 = 'f406e835dd0badd3b51140c08a958e5afa4b9a7a815223d452fee795638c0d9f'
AND original_filename <> '90480a6d4ea312119fd7e32ca4afa673b6a9437b.jpg';

UPDATE media_asset SET original_filename = '98a52347c3fd59d96d269c08a9c262bcc30a6f55.jpg' WHERE sha256 = 'a94adf464c1c4d1fc166fb9f82128fa82f797e438bd3786e2e0d7ef9b82dd3e0'
AND original_filename <> '98a52347c3fd59d96d269c08a9c262bcc30a6f55.jpg';

UPDATE media_asset SET original_filename = '7719a001f5e270862d96690eb7d65f8698027084.jpg' WHERE sha256 = 'd624dda298b1286e84586ffb04c5a14759ae24c3a8a73d9db24048edc6dba14c'
AND original_filename <> '7719a001f5e270862d96690eb7d65f8698027084.jpg';

UPDATE media_asset SET original_filename = '7ca3d3ba6a3de0a3fcfb5368247013f2d2552f5f.jpg' WHERE sha256 = '789e224f0a9433a6433b10c3501507c6b0dba510603485546e774a83c595f195'
AND original_filename <> '7ca3d3ba6a3de0a3fcfb5368247013f2d2552f5f.jpg';

UPDATE media_asset SET original_filename = '5db95f592e3e294945fe4752d4cee8a3936f4220.jpg' WHERE sha256 = '11a40459b0c9cbd19e2ff3b839b99cd71d6970824cd2498fcd429a79f2523c6a'
AND original_filename <> '5db95f592e3e294945fe4752d4cee8a3936f4220.jpg';

UPDATE media_asset SET original_filename = '7d36dfa1eda75e7a8971906f7df1bb3042ec85b0.jpg' WHERE sha256 = 'db0816f2ef782c7acb638c79f26be2c95a4f763782809afa70f0cfc7f52da388'
AND original_filename <> '7d36dfa1eda75e7a8971906f7df1bb3042ec85b0.jpg';

UPDATE media_asset SET original_filename = '830b99dbb404ba97682425185fdbbd820ea27cb6.jpg' WHERE sha256 = '643ee781568dcfd81c421dbcde890011267b84082aa336f99773c39712f07059'
AND original_filename <> '830b99dbb404ba97682425185fdbbd820ea27cb6.jpg';

UPDATE media_asset SET original_filename = '5593032db1dccacbed0e85053ee3b9e30cad0066.jpg' WHERE sha256 = 'b736b935b1bed76ad67120d9016b16cb64cc64272e166588e212f57e69fcb786'
AND original_filename <> '5593032db1dccacbed0e85053ee3b9e30cad0066.jpg';

UPDATE media_asset SET original_filename = 'f10eb9661b028fead08aec88c02a7786b919db27.jpg' WHERE sha256 = 'f56a948551e9fce925e0aff59fbbbfcf125592c37327e24a246ac52817206e9f'
AND original_filename <> 'f10eb9661b028fead08aec88c02a7786b919db27.jpg';

UPDATE media_asset SET original_filename = '0d73164b8ce2164e226b79e328f3edf3446c1492.jpg' WHERE sha256 = 'edf775df0b2e571107c69c2da1acc65a82e94522de55ae789b82e45d4f6ff2ab'
AND original_filename <> '0d73164b8ce2164e226b79e328f3edf3446c1492.jpg';

UPDATE media_asset SET original_filename = 'a68ea2c3450b86c73634ab22e1e09182ad7a696c.jpg' WHERE sha256 = '34ca672ca52a14ba646e3ad96dcf712aa1188a6198fdbbc20e51304d7f06ff18'
AND original_filename <> 'a68ea2c3450b86c73634ab22e1e09182ad7a696c.jpg';

UPDATE media_asset SET original_filename = '05e0b7fdf462b5ea7a969b5a39c97a4c9bea9535.jpg' WHERE sha256 = 'a93b03d1bebc140793e0a4ab46c3dbb3acbf1fe04406667643f94ed55ff7f932'
AND original_filename <> '05e0b7fdf462b5ea7a969b5a39c97a4c9bea9535.jpg';

UPDATE media_asset SET original_filename = 'c25d72db33a321587cb4c6ad2cf097fcc84e28b9.jpg' WHERE sha256 = 'e3c7875dfc0213d88b3a19b4c9cf3be100275fa59e1484bfbf1a77c358cd91a3'
AND original_filename <> 'c25d72db33a321587cb4c6ad2cf097fcc84e28b9.jpg';

UPDATE media_asset SET original_filename = '7e117467a10989fffd2d386648c8009cac2ec822.jpg' WHERE sha256 = 'b84b7bbe2e9ef55dffc71776d917d9dab03431e31a5df0b3c69e15de5e17a233'
AND original_filename <> '7e117467a10989fffd2d386648c8009cac2ec822.jpg';

UPDATE media_asset SET original_filename = 'd08820059adabe4fa8987159f86cd44e9626fadd.jpg' WHERE sha256 = '48c39a003074c77571b855480e05afb1cbbb4d0f98b4faecf863484cfe6395c0'
AND original_filename <> 'd08820059adabe4fa8987159f86cd44e9626fadd.jpg';

UPDATE media_asset SET original_filename = '876478a244ef29c9cdcc56e79c2fe81f28c41355.jpg' WHERE sha256 = 'bb969d941cb48b7fc24b169c7830b066cb434bd912592cd50786dc314d31eba1'
AND original_filename <> '876478a244ef29c9cdcc56e79c2fe81f28c41355.jpg';

UPDATE media_asset SET original_filename = 'fe3ff54bb9224ccf722df88d14d9c0c1cfddc0c3.jpg' WHERE sha256 = '7d17dad30e42df6f6370703ff6acf823a957ccd27c212c6992315277b9f8b7f1'
AND original_filename <> 'fe3ff54bb9224ccf722df88d14d9c0c1cfddc0c3.jpg';

UPDATE media_asset SET original_filename = 'd00c1177ac03007a1d8021f8f63747666f91d453.jpg' WHERE sha256 = '5e5944e5aabbdc1f2d9475ffc754ed4656fefdda602c7f9c018d49f8551196d0'
AND original_filename <> 'd00c1177ac03007a1d8021f8f63747666f91d453.jpg';

UPDATE media_asset SET original_filename = 'fd3fab6fe3ce58b0ddc50f1f52dd31f87d2632ea.jpg' WHERE sha256 = '383a664d04f2cda6d250ccfde778a8250aef5a8d6064a4e84804991d82e97094'
AND original_filename <> 'fd3fab6fe3ce58b0ddc50f1f52dd31f87d2632ea.jpg';

UPDATE media_asset SET original_filename = '3427c580cf3384cbdf8c08e5ef00ee8f246e2075.jpg' WHERE sha256 = '7f8a7e222122dee385f12108ac9eec8ed2a52fb947b7f57ec5ee7e9bc9707d8f'
AND original_filename <> '3427c580cf3384cbdf8c08e5ef00ee8f246e2075.jpg';

UPDATE media_asset SET original_filename = 'ac856d1351c2d40fe53a86bc32ae00cde4a683f2.jpg' WHERE sha256 = 'abfb05a5f788de10c2f441f17556adc37ea3dc7738b0d2aac4f946476e2dbb49'
AND original_filename <> 'ac856d1351c2d40fe53a86bc32ae00cde4a683f2.jpg';

UPDATE media_asset SET original_filename = '5232e0ede66a42f2c57d67aa9905fcaf57196b2f.jpg' WHERE sha256 = '3a383586cfcc8e8db21d78c44232bee301d56109f3917371e3a1c4320d5db879'
AND original_filename <> '5232e0ede66a42f2c57d67aa9905fcaf57196b2f.jpg';

UPDATE media_asset SET original_filename = '3818a3fb1c0a15e7b839be196478ee0d7775fae9.jpg' WHERE sha256 = '4e012ec9ab9255ae369afb465b3145bc9ac1dac41153f3b00dfe5a54c790d4a1'
AND original_filename <> '3818a3fb1c0a15e7b839be196478ee0d7775fae9.jpg';

UPDATE media_asset SET original_filename = 'a46b6a9469dce318f70b028dcf64d875f8068371.jpg' WHERE sha256 = '4cf16a59f462fb36c4bebab3fefca3d5352fcd2df369b11523317b925a9040d3'
AND original_filename <> 'a46b6a9469dce318f70b028dcf64d875f8068371.jpg';

UPDATE media_asset SET original_filename = '9f132a542ac6dd1a907fca27676881036e607795.jpg' WHERE sha256 = '4b6b0233ce8c8823b3cbfec4f2d78b34eb995e8ded5008f3eae1f1b736b7c014'
AND original_filename <> '9f132a542ac6dd1a907fca27676881036e607795.jpg';

UPDATE media_asset SET original_filename = 'eb03ab3a48b307162b8d329f665a3c708359e2b9.jpg' WHERE sha256 = '3b38c4392cd04969434eed331994d610d1dce408c1c9d831733516ff5fc13f39'
AND original_filename <> 'eb03ab3a48b307162b8d329f665a3c708359e2b9.jpg';

UPDATE media_asset SET original_filename = 'd9790323931adfef903458bc5d86e2eadc8d3e26.jpg' WHERE sha256 = 'e2b1637b7012788b80888fcec309a25c92f2c9ac39ea07c43d68cecfadc59dde'
AND original_filename <> 'd9790323931adfef903458bc5d86e2eadc8d3e26.jpg';

UPDATE media_asset SET original_filename = 'e23939584cebacc3e4d7e2a26bb51c0f1afb1b84.jpg' WHERE sha256 = 'bf696819b108daa06623f18a966892446178cfd0d2d47a54c8987c179122de8e'
AND original_filename <> 'e23939584cebacc3e4d7e2a26bb51c0f1afb1b84.jpg';

UPDATE media_asset SET original_filename = '37810f861c58038aa8110aed52e34145a570e141.jpg' WHERE sha256 = '5489d96b61292163e6c97c94eb0bfa56848d971853eb74b11fee4383eb3e94ac'
AND original_filename <> '37810f861c58038aa8110aed52e34145a570e141.jpg';

UPDATE media_asset SET original_filename = '0249ac95fd097508fba79123a60c82f5b01326f8.jpg' WHERE sha256 = 'c329709d7cd9f8e26cf32ee716fa16737caf77cf269857a5acdd28e3d31e9992'
AND original_filename <> '0249ac95fd097508fba79123a60c82f5b01326f8.jpg';

UPDATE media_asset SET original_filename = '4ccef3ccf0fb1fde3f2e881f6def7b02c1c8ef27.jpg' WHERE sha256 = 'd249b7258e37d5d6a865a08a9fa95638e99fe2309874dcc211e09b2d375a99e6'
AND original_filename <> '4ccef3ccf0fb1fde3f2e881f6def7b02c1c8ef27.jpg';

UPDATE media_asset SET original_filename = 'a1fb6de91dcd1b75db13fedf32a27d8f8db25c70.jpg' WHERE sha256 = '769b77decbfe54c4ef0416bc9f5c2c3661c9cb544a39a57142b6745424126e48'
AND original_filename <> 'a1fb6de91dcd1b75db13fedf32a27d8f8db25c70.jpg';

UPDATE media_asset SET original_filename = 'd9bca7cec76282c4e2e09073d793f768b143ee26.jpg' WHERE sha256 = '0fa34da0c47716fdb5d13c793cbb8e2a521c92e5aadc19b046fee01c24f34075'
AND original_filename <> 'd9bca7cec76282c4e2e09073d793f768b143ee26.jpg';

UPDATE media_asset SET original_filename = 'abb935f7a23bd2026fad9ada603fe87990bb8b1c.jpg' WHERE sha256 = 'c7df782e2eb2ecc26c55f4784a203628d9195b7c3be72de7ab65455a8b30240f'
AND original_filename <> 'abb935f7a23bd2026fad9ada603fe87990bb8b1c.jpg';

UPDATE media_asset SET original_filename = 'a92c110c8f651ff1d4f17371f75ea1129a96f0a1.jpg' WHERE sha256 = '6339709215be5a1bcd3ab01c27a9b5d737841905a007be40fdbe979a390a81da'
AND original_filename <> 'a92c110c8f651ff1d4f17371f75ea1129a96f0a1.jpg';

UPDATE media_asset SET original_filename = 'c0fd0f778827187e261817b16f87d724f5d2a805.jpg' WHERE sha256 = 'f2a1b0452bb181c73f3356f31bebc3fa7c8ecf0b978afd1bb6cc792367e43f7a'
AND original_filename <> 'c0fd0f778827187e261817b16f87d724f5d2a805.jpg';

UPDATE media_asset SET original_filename = '1e090f9832ae6f16a6b07ab4f965f80fafcd60fa.jpg' WHERE sha256 = '561195bdddf55d63f67f35ef52ff07f487aa46d2672075e46398297710b3c0d0'
AND original_filename <> '1e090f9832ae6f16a6b07ab4f965f80fafcd60fa.jpg';

UPDATE media_asset SET original_filename = '0c251a2703467c51c008f501727ab4948e720ea2.jpg' WHERE sha256 = 'e472b24c3b5d03263bcb5a270b6e7a8d9bf5766410e1e9b403fb0a1debb4cb05'
AND original_filename <> '0c251a2703467c51c008f501727ab4948e720ea2.jpg';

UPDATE media_asset SET original_filename = 'aebf8301943b0106b58a580f00f66464c2d09ff6.jpg' WHERE sha256 = 'efc80ffd0f0da39044655158c2de4238305abb2262eea0e5513941d015e5b4ae'
AND original_filename <> 'aebf8301943b0106b58a580f00f66464c2d09ff6.jpg';

UPDATE media_asset SET original_filename = 'b5f6d584136eb082bcf2aefdb7784df3647d7b09.jpg' WHERE sha256 = '30edfc51773ca59a6874178e3af3717ba4d8db00cabc79d14823d9c648ff98f0'
AND original_filename <> 'b5f6d584136eb082bcf2aefdb7784df3647d7b09.jpg';

UPDATE media_asset SET original_filename = 'b537fc25b1981818a122236799f8b99fdc073e63.jpg' WHERE sha256 = '00e798e4ac8fc8495adf3cee47a97f019644d489c1eebdd29f6235fce081c17d'
AND original_filename <> 'b537fc25b1981818a122236799f8b99fdc073e63.jpg';

UPDATE media_asset SET original_filename = 'd007029e4e464d21344eb687226d0cf8e7ba3f07.jpg' WHERE sha256 = '81e5e66804ba725ab4521831e2b142baa9cff8995f53933a36e673065e2a4e99'
AND original_filename <> 'd007029e4e464d21344eb687226d0cf8e7ba3f07.jpg';

UPDATE media_asset SET original_filename = 'e592801e858911e437365908ac9777c7cc6f01fc.jpg' WHERE sha256 = '9e211700ee87d2c25637f0c25e949652c76420bb8a9d22abeaf3ba03ed25447a'
AND original_filename <> 'e592801e858911e437365908ac9777c7cc6f01fc.jpg';

UPDATE media_asset SET original_filename = 'd8fa6affdc0503b816d8c9f4142b605d51735727.jpg' WHERE sha256 = 'c2ce8508cd946518ed9a326b07b585180bf3b1d7b02ee1ea2343269184f408c1'
AND original_filename <> 'd8fa6affdc0503b816d8c9f4142b605d51735727.jpg';

UPDATE media_asset SET original_filename = '2fe382112792169dc3bcee3fd202a8f65e928738.jpg' WHERE sha256 = 'c499b6100730b856894d9f1e93dfa647792d071a94902a035a8712a7c8e10569'
AND original_filename <> '2fe382112792169dc3bcee3fd202a8f65e928738.jpg';

UPDATE media_asset SET original_filename = '5118ecb1f517ad51e8dac87cc10e41fae2ab667e.jpg' WHERE sha256 = '1e56c6d01ac9a285d705dc433d9ee3395fef226247ead3ed39063928466e4fb8'
AND original_filename <> '5118ecb1f517ad51e8dac87cc10e41fae2ab667e.jpg';

UPDATE media_asset SET original_filename = '5d8455b75b82abcca17934f6869d7b81a2990e6c.jpg' WHERE sha256 = '9990fb64d461fd9caada9b0e9bf12b13b6ab142f96a44d19feaa3c43888a3f22'
AND original_filename <> '5d8455b75b82abcca17934f6869d7b81a2990e6c.jpg';

UPDATE media_asset SET original_filename = 'fce6ec640f24d2c61f53a83a576f4ffea51a43d4.jpg' WHERE sha256 = '46652e8009a0c72c1bf3d845a367ccf26489cc4c5ac630922b77c3179138d0d9'
AND original_filename <> 'fce6ec640f24d2c61f53a83a576f4ffea51a43d4.jpg';

UPDATE media_asset SET original_filename = 'ef5c04f1652faa6ec6759dc53833c73b6112d577.jpg' WHERE sha256 = '57f2998ddf7ff76ed310b92d9b247a12d0604e682209a536a665a1f6c1d5949f'
AND original_filename <> 'ef5c04f1652faa6ec6759dc53833c73b6112d577.jpg';

UPDATE media_asset SET original_filename = 'ead2b2614fd3e1b8a9ae2f5806537884693cb4cd.jpg' WHERE sha256 = '6d769527df20283aa4723dadba1eb58c2f8b90acf84c4b70df0c99f786d6a375'
AND original_filename <> 'ead2b2614fd3e1b8a9ae2f5806537884693cb4cd.jpg';

UPDATE media_asset SET original_filename = '8258be73e17dc0180828f2f012304c38eb300acb.jpg' WHERE sha256 = 'fbc33a9e58a1fae94c815243735ea2bcd25e2ef9d9e68b54d3cd364314ba649c'
AND original_filename <> '8258be73e17dc0180828f2f012304c38eb300acb.jpg';

UPDATE media_asset SET original_filename = '882f13ff7e5c78c0d0c26c14da9c0321dd379039.jpg' WHERE sha256 = 'cbca691d8524631ea09afa0efe2a3ffcaf9f353b84b1688c374b181387b232fa'
AND original_filename <> '882f13ff7e5c78c0d0c26c14da9c0321dd379039.jpg';

UPDATE media_asset SET original_filename = 'ad68d1de803e7de3be064015c14ba02cfbb5a614.jpg' WHERE sha256 = '7768ae131d30a8e92049b8a9774c182ea30f519f42974af4bf9b17c4361c7b81'
AND original_filename <> 'ad68d1de803e7de3be064015c14ba02cfbb5a614.jpg';

UPDATE media_asset SET original_filename = 'a2b2f4e44dfc88707db0feeed186d70e250085df.jpg' WHERE sha256 = '63d4c0133d58598b61b0d998d4d2e5123e7ce6176c8b5097dbc7e520a17db36f'
AND original_filename <> 'a2b2f4e44dfc88707db0feeed186d70e250085df.jpg';

UPDATE media_asset SET original_filename = 'e72e4ed64b4cca2b58447b2cd0c44e7db3663e05.jpg' WHERE sha256 = 'a205612def04220f2cc40289eb8e471ec24b55aecd7204e213e8d3028db36911'
AND original_filename <> 'e72e4ed64b4cca2b58447b2cd0c44e7db3663e05.jpg';

UPDATE media_asset SET original_filename = 'cbb81417c78690b44ca1f72e99a89dd06a5faab6.jpg' WHERE sha256 = 'c74c98f7d509da283637f7ec76d1a308551484029ad1a1e14eb8281c5dbf235f'
AND original_filename <> 'cbb81417c78690b44ca1f72e99a89dd06a5faab6.jpg';

UPDATE media_asset SET original_filename = '38d3cb2d76dfb7e39564eb700efbeffe0020de74.jpg' WHERE sha256 = '1e96cf59ce431d2bfde2692756a849598187fe7a98f89ba1b806999d0022db37'
AND original_filename <> '38d3cb2d76dfb7e39564eb700efbeffe0020de74.jpg';

UPDATE media_asset SET original_filename = 'dcdc5208d7cdd76eb4e9de82400b32d44a5bd6c3.jpg' WHERE sha256 = 'ba081a06dc8ae1ac5efb440619a7752a86d0342eb3dec5d976e2c5f263a730d1'
AND original_filename <> 'dcdc5208d7cdd76eb4e9de82400b32d44a5bd6c3.jpg';

UPDATE media_asset SET original_filename = '940622c58ee43351c3c62e5f8b27eb83f6e68715.jpg' WHERE sha256 = 'f83c581c2941b65f70b624eb613509f68c9faf79ed14e5894c5ab39454f5d649'
AND original_filename <> '940622c58ee43351c3c62e5f8b27eb83f6e68715.jpg';

UPDATE media_asset SET original_filename = '67c9cef100a8f2b04e40337c040d4daa520aaa49.jpg' WHERE sha256 = 'c7f3e94682d34726b3543563a28beffe17c0a139b3d85ef0e16b569aad14b3e1'
AND original_filename <> '67c9cef100a8f2b04e40337c040d4daa520aaa49.jpg';

UPDATE media_asset SET original_filename = '506a3f573459494cbe3a48763471e54f087d3dfd.jpg' WHERE sha256 = '4002e4bec88c9885e47f9aa63e701a6309a1ff9a6a672f3f843fd0101dd714f7'
AND original_filename <> '506a3f573459494cbe3a48763471e54f087d3dfd.jpg';

UPDATE media_asset SET original_filename = '950a37c7fce2d955ada2c1b517321383e1775afb.jpg' WHERE sha256 = '4510b41ccfc2f52094209f1220d258ffb105d965e17aee95bbc2df371b95b2a5'
AND original_filename <> '950a37c7fce2d955ada2c1b517321383e1775afb.jpg';

UPDATE media_asset SET original_filename = '1772205bc391123e792ff686869eaee2fababee7.jpg' WHERE sha256 = 'a568840f654a247ae5fdbfb6b8de7ed6d6950f7286e290f68d1ad352836409c2'
AND original_filename <> '1772205bc391123e792ff686869eaee2fababee7.jpg';

UPDATE media_asset SET original_filename = '57bf439b15e39b70f59f374f6cda70b403e17e67.jpg' WHERE sha256 = '9ec35e46c27db799e43a08bd2a3c4353d51a0c037f8bdbbc63684f7fefbb0cc0'
AND original_filename <> '57bf439b15e39b70f59f374f6cda70b403e17e67.jpg';

UPDATE media_asset SET original_filename = 'c5ad60ddc0e1ddf9925e37f3c82d84ec462945f5.jpg' WHERE sha256 = 'e58ddc2d8362ab4ad1f925102971c34ca1df75c75a4c6823ca625d31def445f8'
AND original_filename <> 'c5ad60ddc0e1ddf9925e37f3c82d84ec462945f5.jpg';

UPDATE media_asset SET original_filename = '6bd13c3ba629e5f79d9ddf15cc79b7dc34729638.jpg' WHERE sha256 = 'd3a6d0c18f6887f771aa3cd51db375e7a9588e1af63801cc100cd9bcc5bccaac'
AND original_filename <> '6bd13c3ba629e5f79d9ddf15cc79b7dc34729638.jpg';

UPDATE media_asset SET original_filename = '3628ffc8c74b20e7588c537f0da8907546a986fa.jpg' WHERE sha256 = '98bf884f79a76a7028d252e63c5b93fea4b0d17ad276eaf0f2c8904cbd7f8189'
AND original_filename <> '3628ffc8c74b20e7588c537f0da8907546a986fa.jpg';

UPDATE media_asset SET original_filename = '6b905894a290c322c6f79845391fd6b7de9a67c1.jpg' WHERE sha256 = '277fded4030dbb69659d784418ef078f6c8045195dd136a51a1a7543be576c39'
AND original_filename <> '6b905894a290c322c6f79845391fd6b7de9a67c1.jpg';

UPDATE media_asset SET original_filename = '39a95c3ed4db5145bcb2f8d8596d38a914e3d83d.jpg' WHERE sha256 = 'ca9b0f28bc3efda8c4c0b2674389266af4d18561cd7660c048c941b20aeadbd7'
AND original_filename <> '39a95c3ed4db5145bcb2f8d8596d38a914e3d83d.jpg';

UPDATE media_asset SET original_filename = 'a1479d7d490350dd3585489a4da90ce2302a2ea5.jpg' WHERE sha256 = 'a49f167263951f5aae962ddcc400f73350e6ae8bdde8eb75e4047c9b9c7128c5'
AND original_filename <> 'a1479d7d490350dd3585489a4da90ce2302a2ea5.jpg';

UPDATE media_asset SET original_filename = '9c3ab33726c414c26890118c44fe8ae6152bdefb.jpg' WHERE sha256 = '98218f054e0f6bea9ada378e638c668fefc8fb5bbeec7c9a1de572baa8405c50'
AND original_filename <> '9c3ab33726c414c26890118c44fe8ae6152bdefb.jpg';

UPDATE media_asset SET original_filename = '1cf3453c6acaf4df21836b29150b13c4108196a2.jpg' WHERE sha256 = '6a0306f14f2da85a8fb4b02d38016d34d79e504cfcb2de83f2293cf60faaffb5'
AND original_filename <> '1cf3453c6acaf4df21836b29150b13c4108196a2.jpg';

UPDATE media_asset SET original_filename = 'ae71169dec6ae2d79ff7e6603e197bf0bb6cf29a.jpg' WHERE sha256 = '63e99c17b711978e9db3eb920cfeaca8a21d663cad8344a237f5a192b5b2dd06'
AND original_filename <> 'ae71169dec6ae2d79ff7e6603e197bf0bb6cf29a.jpg';

UPDATE media_asset SET original_filename = 'f68505a1bc30ecdb5cc24484bc3668275ffadf84.jpg' WHERE sha256 = '3a8c4b08755d83476e69afbccc9c593a86cda36baca18264f05d4bed84bfb177'
AND original_filename <> 'f68505a1bc30ecdb5cc24484bc3668275ffadf84.jpg';

UPDATE media_asset SET original_filename = '922ce6fc93d2910b8dfa1e593ce065c6b7ac2bda.jpg' WHERE sha256 = '89f00be3e14f084f8d355786968286ed400d41f7c6b5f617f1bcef9efc1c2c2b'
AND original_filename <> '922ce6fc93d2910b8dfa1e593ce065c6b7ac2bda.jpg';

UPDATE media_asset SET original_filename = '6b1cea6566daa6e2c6cd50549f763c312030b794.jpg' WHERE sha256 = '04bea55cb7f14f2b080140e8f677534baf9193a3d38331445de816de2ab2f04e'
AND original_filename <> '6b1cea6566daa6e2c6cd50549f763c312030b794.jpg';

UPDATE media_asset SET original_filename = '43392aed1e4cf12d3dd5d1f29cec52687937877d.jpg' WHERE sha256 = '59b14900dfd574736e775ff70ed47e3ba1c04808e6f978dbd8380f905d6b99b9'
AND original_filename <> '43392aed1e4cf12d3dd5d1f29cec52687937877d.jpg';

UPDATE media_asset SET original_filename = '93252b138ad698ba36bc659e5499619c6c53368f.jpg' WHERE sha256 = 'e05ed72cf8ec1b8223e259fe77cf218dc4c59072f37e700f49376e536aa0db4b'
AND original_filename <> '93252b138ad698ba36bc659e5499619c6c53368f.jpg';

UPDATE media_asset SET original_filename = '3390863558917c4ea5774309479f3822dc317b80.jpg' WHERE sha256 = '4280007539ccfd22758ef57c3c34c4acde14e1948fb79990b352981762cb8c49'
AND original_filename <> '3390863558917c4ea5774309479f3822dc317b80.jpg';

UPDATE media_asset SET original_filename = 'e7c44dd543f6825c54fbf0a3ed6b1f4641367dbf.jpg' WHERE sha256 = 'b7495d358f1180a0378ca594776e36addfe17880d97e5fa1cea471eaa7099c0d'
AND original_filename <> 'e7c44dd543f6825c54fbf0a3ed6b1f4641367dbf.jpg';

UPDATE media_asset SET original_filename = 'de50f79f83507cdbb5d38d5b108d8e195644790f.jpg' WHERE sha256 = '7a0cea632f2316f6dfa56ac75046d4109f3fc5845b664493855c0e4428154884'
AND original_filename <> 'de50f79f83507cdbb5d38d5b108d8e195644790f.jpg';

UPDATE media_asset SET original_filename = '1aee2be55bb4fb72beed41401010ffc2beed106c.jpg' WHERE sha256 = '7ea371bc8e6be007f373ca00a8da411e98d47e391ddfc272bb2fd29ea4f30bbe'
AND original_filename <> '1aee2be55bb4fb72beed41401010ffc2beed106c.jpg';

UPDATE media_asset SET original_filename = '45ee479726fd09afd76c6854f5e98a4d380a8898.jpg' WHERE sha256 = '499383b217427b3e0c79d8e69526fd4332481467e44c2f36f4eee0c3e82d5e0b'
AND original_filename <> '45ee479726fd09afd76c6854f5e98a4d380a8898.jpg';

UPDATE media_asset SET original_filename = '2ca45da2703d3802011a5b48fc93425d8c8666d9.jpg' WHERE sha256 = '713aa9160283096b30b85bfa869de44c855fd93e8c4a5cc7b856058fd94a55aa'
AND original_filename <> '2ca45da2703d3802011a5b48fc93425d8c8666d9.jpg';

UPDATE media_asset SET original_filename = '635557e24ada9066bba86f897c163cd18b83431e.jpg' WHERE sha256 = '7b35cfefbc475ff17a94c0ea83e3cc9a6ffc397aa32ea2fe43fadc9a4fe29ce0'
AND original_filename <> '635557e24ada9066bba86f897c163cd18b83431e.jpg';

UPDATE media_asset SET original_filename = '05a5e94b08c2e9cc4bf3747858d0bd0bb2737e6f.jpg' WHERE sha256 = '19d37bcfbada349f738d0c38993f83683c5bf7326a94df13a1b7cf7a644c7fd6'
AND original_filename <> '05a5e94b08c2e9cc4bf3747858d0bd0bb2737e6f.jpg';

UPDATE media_asset SET original_filename = 'e282b6abdbe5b3d558939ea35e3d5daa882bab40.jpg' WHERE sha256 = '194723f75d0b5f869c0519b3bdbfc51ed54fd9188cb7ee117bbd91e208c90d54'
AND original_filename <> 'e282b6abdbe5b3d558939ea35e3d5daa882bab40.jpg';

UPDATE media_asset SET original_filename = 'd59b7bb4577cb8fccad0860b5dcace596047a4e3.jpg' WHERE sha256 = '6c53afad043cb04553ec67e616042502081ec5647a5bc1dd361d36cbf44aa3bd'
AND original_filename <> 'd59b7bb4577cb8fccad0860b5dcace596047a4e3.jpg';

UPDATE media_asset SET original_filename = '5a1e43b0284d257345299c43c8a12099bfecbb10.jpg' WHERE sha256 = 'e6d787827c105d4b701cebc27d8cea662241f76bdc20e847c5b61e120cabb143'
AND original_filename <> '5a1e43b0284d257345299c43c8a12099bfecbb10.jpg';

UPDATE media_asset SET original_filename = '46f357c3ce807c5b4380fec03765a2bc90b49ec8.jpg' WHERE sha256 = '365602d08dbd2c6cae6f1bd1b6d04d82f45983c582625ffc043a0a285282cca6'
AND original_filename <> '46f357c3ce807c5b4380fec03765a2bc90b49ec8.jpg';

UPDATE media_asset SET original_filename = '6c22bb21f8a2e98e37f7a078fa942095ae2a5553.jpg' WHERE sha256 = 'edda64e2571ef6b9f47dd49f3e15e3230e6e8e7ac1e590a1ad26650dcce0b4fb'
AND original_filename <> '6c22bb21f8a2e98e37f7a078fa942095ae2a5553.jpg';

UPDATE media_asset SET original_filename = 'faebb0099e9366ab5fb93192591662931358d534.jpg' WHERE sha256 = '21fbc8c181391bc92805ca39a8ebc130bb19e7daec9a6a3bba31ba88fe79fea1'
AND original_filename <> 'faebb0099e9366ab5fb93192591662931358d534.jpg';

UPDATE media_asset SET original_filename = 'b771e5227b84889d1e84ca7150e3aaa1975fccef.jpg' WHERE sha256 = 'bfd40cbaf23118a85c82f6a61f9142f6451b9ddd86d378c837ef202972d9f2dc'
AND original_filename <> 'b771e5227b84889d1e84ca7150e3aaa1975fccef.jpg';

UPDATE media_asset SET original_filename = '0ecbea5dcdb8716712f20b70e6274d0e478019d4.jpg' WHERE sha256 = 'b221e6d4f762eaf71188f8db4ddb4ecaab33f08da0a4bb0d027339c853f3c5f4'
AND original_filename <> '0ecbea5dcdb8716712f20b70e6274d0e478019d4.jpg';

UPDATE media_asset SET original_filename = '9bab0f8d6b5e1873c0fcc9d2803668ff1ab7678c.jpg' WHERE sha256 = '7dd2b4e64e599e8d05f6d9866488d721643098e9f4640546294218bf276adac6'
AND original_filename <> '9bab0f8d6b5e1873c0fcc9d2803668ff1ab7678c.jpg';

UPDATE media_asset SET original_filename = '8a33d660f0a7683d67fb901f4d77511b36d91e8c.jpg' WHERE sha256 = 'bc58ebd3bb84bdf36c8cf64f28f83d59b9781d12322486894d8e296e2e4884a3'
AND original_filename <> '8a33d660f0a7683d67fb901f4d77511b36d91e8c.jpg';

UPDATE media_asset SET original_filename = '0389ea52353f45de216457d7999a2bb9b0e85709.jpg' WHERE sha256 = 'ecce2148f56c80e6bacfd48e9987eb6ae37b9a3b73ef801656af0d2d53fd6d7e'
AND original_filename <> '0389ea52353f45de216457d7999a2bb9b0e85709.jpg';

UPDATE media_asset SET original_filename = '6b720a03c66be2d4166ba485dc577f7717fe7fa0.jpg' WHERE sha256 = '2537868b5ed84b26b4abcd541664c26bdd7c5a12807b59bc16cd67ef4be4206c'
AND original_filename <> '6b720a03c66be2d4166ba485dc577f7717fe7fa0.jpg';

UPDATE media_asset SET original_filename = '2d23d4b734aa80164af3e88493a136e350757a02.jpg' WHERE sha256 = 'c41abb8a5bc366623622c8066a5730c0bda187a48c4afb63064db71db76da5be'
AND original_filename <> '2d23d4b734aa80164af3e88493a136e350757a02.jpg';

UPDATE media_asset SET original_filename = '327dcf315300b518d3711f65b7aa8b71da35240d.jpg' WHERE sha256 = 'acf4beb14a7981ecd93877dcf220e1d9beb5b615260e3b46c0e94a96f18a75f5'
AND original_filename <> '327dcf315300b518d3711f65b7aa8b71da35240d.jpg';

UPDATE media_asset SET original_filename = '679defa27f50e62099d0ed102cee41e823c9bf2a.jpg' WHERE sha256 = 'ccbb2baf7ad809024bc7a98aaa8e8ba3318cd383adf19e0ba403aa20bb8d9a96'
AND original_filename <> '679defa27f50e62099d0ed102cee41e823c9bf2a.jpg';

UPDATE media_asset SET original_filename = '9e7803f8dff0c3f592f29de72d5c0b97828347c0.jpg' WHERE sha256 = '1131b01c8bea8a680eaa6239d0c2fd6db4cbbac1f68e4bc0ed860e7a75a11087'
AND original_filename <> '9e7803f8dff0c3f592f29de72d5c0b97828347c0.jpg';

UPDATE media_asset SET original_filename = '806a35b587570143a5f310b40c9c508303658cd5.jpg' WHERE sha256 = '974fce087010d1ca96c9021b020aa6c1bb2376b13006987798dd9ab9c3cbd4ff'
AND original_filename <> '806a35b587570143a5f310b40c9c508303658cd5.jpg';

UPDATE media_asset SET original_filename = '629a1b484f4fccbc554b193944d4b51922c0d4e3.jpg' WHERE sha256 = '2d96d97a28052655dccfa1308ddbbe4452d754da97ba79a62bf6336f3c92fc4b'
AND original_filename <> '629a1b484f4fccbc554b193944d4b51922c0d4e3.jpg';

UPDATE media_asset SET original_filename = 'be96c7e2cc89995166349778bffb7ef86fd15869.jpg' WHERE sha256 = 'ee4cdf4ae46fd8b7da6546c33d8bedc6c4b0f94b8ebdbda1511c7552ec58c650'
AND original_filename <> 'be96c7e2cc89995166349778bffb7ef86fd15869.jpg';

UPDATE media_asset SET original_filename = 'd3efdb258a951a7e7e876ad433946469419b64c2.jpg' WHERE sha256 = '57766e14f96cf09e7dce178c1d0547219d4bba8d85031b50aa6350993f51481f'
AND original_filename <> 'd3efdb258a951a7e7e876ad433946469419b64c2.jpg';

UPDATE media_asset SET original_filename = '85707faa25ba5c19b22c20b7907c7e4b65160fdc.jpg' WHERE sha256 = 'd233e41f97c222e8f62a8dc17bd0c64d1a02f1d60f96c808ad7d2bbabd1ece8d'
AND original_filename <> '85707faa25ba5c19b22c20b7907c7e4b65160fdc.jpg';

UPDATE media_asset SET original_filename = 'fc955a9c52fbaafe13089bf8cd37fd129cbde5e7.jpg' WHERE sha256 = 'a6cdcc347ac2d85a2ed06e6d02ff8d5bd14144811906f2c2fa7b691ed2f70a28'
AND original_filename <> 'fc955a9c52fbaafe13089bf8cd37fd129cbde5e7.jpg';

UPDATE media_asset SET original_filename = '87584cdb26b84c4e3ff4cd6810f9b02cf664c711.jpg' WHERE sha256 = 'b17046a6024f4f42920b21eb9b29b92019c1125e715235141d267f57f5cf36d3'
AND original_filename <> '87584cdb26b84c4e3ff4cd6810f9b02cf664c711.jpg';

UPDATE media_asset SET original_filename = '54c508df3667402e3bb11fb4ce9f8e1e6d317fb7.jpg' WHERE sha256 = 'd80acc73cdf4ae7f4bdae9a31c5ceb9d76af9ee874fee3b7749d9eb0257a83f4'
AND original_filename <> '54c508df3667402e3bb11fb4ce9f8e1e6d317fb7.jpg';

UPDATE media_asset SET original_filename = '8488ae10e777e596d866c667d03bf22c66ee05fe.jpg' WHERE sha256 = '876839ac515c581fc8f37e3c0f4611054931c88b69e4786b034eaa6a9ad3dcdd'
AND original_filename <> '8488ae10e777e596d866c667d03bf22c66ee05fe.jpg';

UPDATE media_asset SET original_filename = '1a70721f7c7db6a9c6c96ec271feff408883f5d2.jpg' WHERE sha256 = '287b75062c9e078fb43b1634b69ff2d08fba58c12e722171d91769056ba7ffc7'
AND original_filename <> '1a70721f7c7db6a9c6c96ec271feff408883f5d2.jpg';

UPDATE media_asset SET original_filename = 'f340628e5db76c3445f2519252f1176d72e34826.jpg' WHERE sha256 = 'b471a736db91911199aaab9623d7660034ac5e0239ba25f06b7c55bbc3f3814d'
AND original_filename <> 'f340628e5db76c3445f2519252f1176d72e34826.jpg';

UPDATE media_asset SET original_filename = 'd57784be7987820438deefaf7217f44f70c400fc.jpg' WHERE sha256 = '2a4fcaebc582ebf936c9f629b7cca9d0bcd2fa0e5b21f31c856cb48653916b69'
AND original_filename <> 'd57784be7987820438deefaf7217f44f70c400fc.jpg';

UPDATE media_asset SET original_filename = 'ca000848af764aa73676ea1af0ee96f3ec4f9d22.jpg' WHERE sha256 = 'e3198357344bfc4e77fd254b1904d1822fe8895fcfc54181a1bfa677fa247ffd'
AND original_filename <> 'ca000848af764aa73676ea1af0ee96f3ec4f9d22.jpg';

UPDATE media_asset SET original_filename = '893acb5d07c3fe0a312a41d3e9d08aabbf3fe1d6.jpg' WHERE sha256 = '17b5348e73c7258b73f08a70ea69224574672078a2057e0f1bdc04ba99dc389e'
AND original_filename <> '893acb5d07c3fe0a312a41d3e9d08aabbf3fe1d6.jpg';

UPDATE media_asset SET original_filename = '46db46b2e09553056ce9844f13601565fc0a3b7e.jpg' WHERE sha256 = 'e50e20cf082da2c1589eaa430c74b3cb14fd6d5c4c11fd4bdba5827f4734e0d6'
AND original_filename <> '46db46b2e09553056ce9844f13601565fc0a3b7e.jpg';

UPDATE media_asset SET original_filename = '238f51598a9f59c78eba5b39396d84b09d1aa972.jpg' WHERE sha256 = 'ee0ca27945cde07551899a088436579e212a95cc40b7b93493f8856b16e17141'
AND original_filename <> '238f51598a9f59c78eba5b39396d84b09d1aa972.jpg';

UPDATE media_asset SET original_filename = '015b9a4e5b2c338304a938c7cab281ce6061d9a6.jpg' WHERE sha256 = '01d6f3359d256b5f0cbe0771dc59ef5dadc5d9066592102094359cbee43bf4d4'
AND original_filename <> '015b9a4e5b2c338304a938c7cab281ce6061d9a6.jpg';

UPDATE media_asset SET original_filename = 'd853c5152027046c24cb9e5af13f57ccdf1ae08d.jpg' WHERE sha256 = '30d56d79b014ddd3a43d6995ffc77235e0e1801ad9bd0aa1071eb8f1d57292cd'
AND original_filename <> 'd853c5152027046c24cb9e5af13f57ccdf1ae08d.jpg';

UPDATE media_asset SET original_filename = 'b2526262b26c4c14943f9c14baabc26cc6e8c2f2.jpg' WHERE sha256 = 'a0d5cb6b5ae9deed21b40a8c668c2443d5adbfa1614501f20f23229d418344b3'
AND original_filename <> 'b2526262b26c4c14943f9c14baabc26cc6e8c2f2.jpg';

UPDATE media_asset SET original_filename = 'b4964bc8f5c23889544d95f288cfd14fc5ed2610.jpg' WHERE sha256 = '09bf283bcf1090c00d369b7e14ebb4cc28377f1dad1601d1dd5cca1c7061bd37'
AND original_filename <> 'b4964bc8f5c23889544d95f288cfd14fc5ed2610.jpg';

UPDATE media_asset SET original_filename = 'f591debf2cb02a7e4ba1bd53192ae4e65985a4bc.jpg' WHERE sha256 = 'a2cfd0de987a93565f977dbdedde249ca5b2543ba7ff6c889f9a1572a35ffc3f'
AND original_filename <> 'f591debf2cb02a7e4ba1bd53192ae4e65985a4bc.jpg';

UPDATE media_asset SET original_filename = '85ea91b384b033785dfefc303568b07cd7b7ca7a.jpg' WHERE sha256 = '7a42933d45f3bda83b498d4ce8ec5ab49b7619f30753219605f2a5737d7bb1ea'
AND original_filename <> '85ea91b384b033785dfefc303568b07cd7b7ca7a.jpg';

UPDATE media_asset SET original_filename = '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-1.webp' WHERE sha256 = '88c948b04cd56882316b51ad18b00bb36108c7e4b446dd2f0e0fb15d2ed137ff'
AND original_filename <> '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-1.webp';

UPDATE media_asset SET original_filename = '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-2.webp' WHERE sha256 = '03e63e2b7a01b2ccc5e8a5ac6063e3bda7deca2cf44092e2e56084f6c2829dcc'
AND original_filename <> '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-2.webp';

UPDATE media_asset SET original_filename = '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-3.webp' WHERE sha256 = '8a4507b8f609b4100a1ae6fe11ce76ccc1c1f4814e8538252ae3ea2d7e33251f'
AND original_filename <> '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-3.webp';

UPDATE media_asset SET original_filename = '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-1.webp' WHERE sha256 = 'd2fc139dc0fe81f01b98e92a108b5ee3b4025ac131cd28e05a30432c80d5fbbd'
AND original_filename <> '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-1.webp';

UPDATE media_asset SET original_filename = '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-1.webp' WHERE sha256 = 'a2dec51fc17e11a9bc5a49be7a2cd278ee193b8a2fe0a28d3ac419d6a54c6d67'
AND original_filename <> '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-1.webp';

UPDATE media_asset SET original_filename = '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-1.webp' WHERE sha256 = '4058fbbc907d2d4468c1ad12b8dacebcb615538beef11579e28941067de911a1'
AND original_filename <> '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-1.webp';

UPDATE media_asset SET original_filename = '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-2.webp' WHERE sha256 = '736abbf22a9c9bce392a08c72602cd39b30fa28d42651a06fccd7e99288bb526'
AND original_filename <> '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-2.webp';

UPDATE media_asset SET original_filename = '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-3.webp' WHERE sha256 = '0928dbb1dcf0c0281bdae6a641aabfcc964a3ac5c9c88f2e79545435a33b43c2'
AND original_filename <> '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-3.webp';

UPDATE media_asset SET original_filename = '安徽某贡酒厂白酒提纯冷却管道防结露解决方案-图片-1.webp' WHERE sha256 = '2ed425714054202183fe8a886832ddb3d85e19b70d3d81da6a2867e50a4d5c6a'
AND original_filename <> '安徽某贡酒厂白酒提纯冷却管道防结露解决方案-图片-1.webp';

UPDATE media_asset SET original_filename = '安徽某贡酒厂白酒提纯冷却管道防结露解决方案-图片-1.webp' WHERE sha256 = '948276c6ec6dcf3e303bcbe9f2ac56ed564c766ae642e6b0dcf8d8bca1c47162'
AND original_filename <> '安徽某贡酒厂白酒提纯冷却管道防结露解决方案-图片-1.webp';

UPDATE media_asset SET original_filename = '安徽某贡酒厂白酒提纯冷却管道防结露解决方案-图片-1.webp' WHERE sha256 = '49a87123837a3a96b48d6b40b9bab94de4a11fd36ee28c516da05ea9fdc63d33'
AND original_filename <> '安徽某贡酒厂白酒提纯冷却管道防结露解决方案-图片-1.webp';

UPDATE media_asset SET original_filename = '安徽淮南国家电投湖面光伏变电房隔热改造项目-图片-1.webp' WHERE sha256 = '234ecf58935ab492ff69db43b354d99810ea1a44095046d2faef0ba6bacffcc3'
AND original_filename <> '安徽淮南国家电投湖面光伏变电房隔热改造项目-图片-1.webp';

UPDATE media_asset SET original_filename = '安徽淮南国家电投湖面光伏变电房隔热改造项目-图片-1.webp' WHERE sha256 = '4cd0dde96b80233e4e1b5ed8bc3fb0907e2eeb4005036b7ed3b99c35478cd5b3'
AND original_filename <> '安徽淮南国家电投湖面光伏变电房隔热改造项目-图片-1.webp';

UPDATE media_asset SET original_filename = '明和产业园新建建筑气凝胶外墙保温案例-图片-1.webp' WHERE sha256 = 'e0ae6b5823e81eeca65cf18f025ce9dfb92c806c594d40f2f3019df46561bc99'
AND original_filename <> '明和产业园新建建筑气凝胶外墙保温案例-图片-1.webp';

UPDATE media_asset SET original_filename = '某大坝碾压混凝土保温抗渗系统应用案例-图片-1.webp' WHERE sha256 = '1d051645aed356308a474f016215c245901e18de5d0d283f9c8e4fe829280c4f'
AND original_filename <> '某大坝碾压混凝土保温抗渗系统应用案例-图片-1.webp';

UPDATE media_asset SET original_filename = '某钢铁水罐车表面防腐及气凝胶节能防烫案例-图片-1.webp' WHERE sha256 = 'd4717899d12619bc1a9cf933fd597a21efa1bc7b803a11233fef7c9d2a4e79a5'
AND original_filename <> '某钢铁水罐车表面防腐及气凝胶节能防烫案例-图片-1.webp';

UPDATE media_asset SET original_filename = '某钢铁水罐车表面防腐及气凝胶节能防烫案例-图片-2.webp' WHERE sha256 = '1432a2c42eb0aa62cdd6ba2c417f41c549ec04f087aa6222aa0470b1ff0a058e'
AND original_filename <> '某钢铁水罐车表面防腐及气凝胶节能防烫案例-图片-2.webp';

UPDATE media_asset SET original_filename = '某陶瓷企业双孔窑炉节能改造案例-图片-1.webp' WHERE sha256 = 'd1dd14d740d027046e8acab4fdd588aefcb425ff9ae582890ea61aa8dab0fd00'
AND original_filename <> '某陶瓷企业双孔窑炉节能改造案例-图片-1.webp';

UPDATE media_asset SET original_filename = '某陶瓷企业双孔窑炉节能改造案例-图片-2.webp' WHERE sha256 = '954700af40b6515a3c19bbca4140587c8269fce8a2ac5197877964c1deb6218c'
AND original_filename <> '某陶瓷企业双孔窑炉节能改造案例-图片-2.webp';

UPDATE media_asset SET original_filename = '某陶瓷企业双孔窑炉节能改造案例-图片-3.webp' WHERE sha256 = 'c689633ceebf649dfaf4eea0c293228441ffe2e3ffb971cb623c0b88bc8ac7b1'
AND original_filename <> '某陶瓷企业双孔窑炉节能改造案例-图片-3.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-1.webp' WHERE sha256 = '71e9698a300a56e3e97c5e6b6ce5af97816b2f5becd4d66b1bc954c1fb9c874a'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-1.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-1.webp' WHERE sha256 = '3cdf4c4e43033ee50b478a2122db3d6bb39d75d064f03f1ef2f944d98a805a4e'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-1.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-1.webp' WHERE sha256 = '6269919c231b9f5e2008d42cdf00d69f686c72d212f7fdba9556796794563563'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-1.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-1.webp' WHERE sha256 = 'b87e4243bf90423913700580d38eba09196cab48bde5c422184fa988fbfc2e2c'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-1.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-2.webp' WHERE sha256 = '7ccb0677f492e97bfc1d93d5f5c92acca7f49a942c3929e5e64c87cb2504747f'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-2.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-3.webp' WHERE sha256 = 'f06ad6c833e1adf2a844bb9226fd741e3eaa9690de6fbfd184ca6735a5080f9f'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-3.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-1.webp' WHERE sha256 = '32206f27b9cbb1a4f3337440d5fc219e67f132227e7158685997c785f30d59bd'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-1.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-2.webp' WHERE sha256 = 'f24cd24b525cc024b906cdc67a8fdf6c7030cb304f2165abe0f8546db58715c1'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-2.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-3.webp' WHERE sha256 = '32924f7b84ec7639627cfc96a7771dc54a81d8a652da1093fa8f3de234de5a26'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-3.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-1.webp' WHERE sha256 = 'ba1b14ea308feaffb150d397dc8a87d26ba763a7515e68910d0b57ab558d35f5'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-1.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-1.webp' WHERE sha256 = 'fa4841c8c387d58f0f5460825fb0d9a4054aa1fa58c55baf74b028a50a11aa47'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-1.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-2.webp' WHERE sha256 = 'acd57c4ec60f9d155941a0fbe44acfb79fa7a1d1c187d551cd8ab279b747f699'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-2.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-3.webp' WHERE sha256 = 'f85b0ca5470b645b85a675a4f4b3b0645462e933d5aeabfe83aa204c5649426f'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-3.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-4.webp' WHERE sha256 = 'cb484b39220f83b9cc64181483e01a67bd7387733faaa7811a17744c043dbc04'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-4.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-5.webp' WHERE sha256 = '43b60801b2d298febe710b106de3b3df01112a45eb6c49d9bd862b3ec99d2dbb'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-5.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-6.webp' WHERE sha256 = '53ccff189d17806993eb61e78e7ea110c6caab2457b8039c282edf043d553907'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-6.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-7.webp' WHERE sha256 = '848271881a33d12a41341410a72688eb119a7f0d33fe6f4891e4677934254eef'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-7.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-8.webp' WHERE sha256 = '9aee615b6346432a6a5d6c1a2a15a89d838ff8e74c4a5cf2884cc5796dbe7ddb'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-8.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-9.webp' WHERE sha256 = 'b5e102918a9177056f0046ba60eafa424e933c4e00170f4a7ea28bf19f82e9fb'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-9.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-2.webp' WHERE sha256 = 'd8e9bca7ff3d49ceb9a2a40da47b3c3e169871b7544e7d4b0edade12ea2a0153'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-2.webp';

UPDATE media_asset SET original_filename = '气凝胶涂料在某新建染厂染缸系统中的应用案例-图片-1.webp' WHERE sha256 = '2e71cca1e78a78172904a676705c217fa6f09f674690ced9407574844fc9b3ad'
AND original_filename <> '气凝胶涂料在某新建染厂染缸系统中的应用案例-图片-1.webp';

UPDATE media_asset SET original_filename = '长沙屋顶隔热保温望城区山与墅项目圆满完工，奥飞涂料助力清凉过夏-图片-1.webp' WHERE sha256 = '31456a8bf43b02edcbe26435571fd4dfc3b67b9ce86035a29c25285bcb60fbbd'
AND original_filename <> '长沙屋顶隔热保温望城区山与墅项目圆满完工，奥飞涂料助力清凉过夏-图片-1.webp';

UPDATE media_asset SET original_filename = '长沙屋顶隔热保温望城区山与墅项目圆满完工，奥飞涂料助力清凉过夏-图片-2.webp' WHERE sha256 = '3d4e84f50b0866f8226b7ff8a56feb94321c3ba989ddc67b4c20f4471f69b9a5'
AND original_filename <> '长沙屋顶隔热保温望城区山与墅项目圆满完工，奥飞涂料助力清凉过夏-图片-2.webp';

UPDATE media_asset SET original_filename = '长沙屋顶隔热保温望城区山与墅项目圆满完工，奥飞涂料助力清凉过夏-图片-1.webp' WHERE sha256 = '7d72a62541c4a9ac8cd105d3196f86c4d38585a1db028f637e19beaaef1ca41c'
AND original_filename <> '长沙屋顶隔热保温望城区山与墅项目圆满完工，奥飞涂料助力清凉过夏-图片-1.webp';

UPDATE media_asset SET original_filename = '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-1.webp' WHERE sha256 = 'fe4985514248356206a07a8f4e26408c9384c5f0545c364a9988c903e5d185c7'
AND original_filename <> '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-1.webp';

UPDATE media_asset SET original_filename = '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-1.webp' WHERE sha256 = '97c1487169dd2e464e91e47032e6091f48bbeee318d46df78228ae08103d9183'
AND original_filename <> '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-1.webp';

UPDATE media_asset SET original_filename = '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-2.webp' WHERE sha256 = '4a1809dd9e9c112adc370773e4c36f390d3dd41343a3ee27470bc229f25d891d'
AND original_filename <> '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-2.webp';

UPDATE media_asset SET original_filename = '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-1.webp' WHERE sha256 = '6c5d8d0d2a50d46705ded07ecf71b27257059ceca43b55ad898b051c71f15701'
AND original_filename <> '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-1.webp';

UPDATE media_asset SET original_filename = '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-2.webp' WHERE sha256 = '78bedf7736b4352ed3ae875ad494c6e5ce3f470e0e6c8f3a87b83c77d4f640a7'
AND original_filename <> '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-2.webp';

UPDATE media_asset SET original_filename = '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-3.webp' WHERE sha256 = '847490d95458b17648eba5c5cc84ddbbeab72fd0ff888618d4e4def7166927c3'
AND original_filename <> '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-3.webp';

UPDATE media_asset SET original_filename = '长沙某公寓内墙气凝胶内墙涂料应用案例-图片-1.webp' WHERE sha256 = '8feacdc286b3cd3ea263dcca9f9ce9e4cba64d5ce90c6604baf471d6ae345f31'
AND original_filename <> '长沙某公寓内墙气凝胶内墙涂料应用案例-图片-1.webp';

UPDATE media_asset SET original_filename = '长沙某公寓内墙气凝胶内墙涂料应用案例-图片-1.webp' WHERE sha256 = 'e7cb8341f9eb73304ffbea9940ae79b892701cdd7d51e922fdf5726db9b94f9a'
AND original_filename <> '长沙某公寓内墙气凝胶内墙涂料应用案例-图片-1.webp';

UPDATE media_asset SET original_filename = '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-1.webp' WHERE sha256 = '615b9a98a14807e25d9be8d2ee81af31e7765763cdd17210c7ca18a8d9c28d1a'
AND original_filename <> '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-1.webp';

UPDATE media_asset SET original_filename = '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-1.webp' WHERE sha256 = 'a762a34450c80d839fb27047da7c32c4a829fb2bcabcbf8ee6a9c8f6983790d4'
AND original_filename <> '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-1.webp';

UPDATE media_asset SET original_filename = '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-2.webp' WHERE sha256 = '9a11076483e3110b9fb9164e9ed92542c7b3c3d583197d9bc38b38c2e71f7c15'
AND original_filename <> '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-2.webp';

UPDATE media_asset SET original_filename = '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-3.webp' WHERE sha256 = '083279e5f0e6f2a3a0c424d868f2fb93e7dd663fe3bac16546cad606b399b105'
AND original_filename <> '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-3.webp';

UPDATE media_asset SET original_filename = '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-1.webp' WHERE sha256 = 'e7ee90b6d5c64978e3db10bc0e449edbf9f5adef261196a17bf21af6986a6ed5'
AND original_filename <> '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-1.webp';

UPDATE media_asset SET original_filename = '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-2.webp' WHERE sha256 = '56830bb910f23e9dcda4d06a9c5134c4b7fd57e9dd5008756ade0fcf45dd4cfd'
AND original_filename <> '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-2.webp';

UPDATE media_asset SET original_filename = '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-1.webp' WHERE sha256 = 'f2e810cd73a143e232bfc85662a0ccc2cec1a2ff6d77f1bf259109d5c14eb0c1'
AND original_filename <> '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-1.webp';

UPDATE media_asset SET original_filename = '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-2.webp' WHERE sha256 = '5d33ff143abd783733846472cd1fea16b1b102288680dc98e5d0a61343a52cde'
AND original_filename <> '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-2.webp';

UPDATE media_asset SET original_filename = '074961550dd38945fd4e509be59497d13c790871.jpg' WHERE sha256 = '8c07c8785b15b9263e1cd0a91784aa2f4f66639dc8a8b1a36900448213e1193f'
AND original_filename <> '074961550dd38945fd4e509be59497d13c790871.jpg';

UPDATE media_asset SET original_filename = 'bca8dc1d4c24ec7c6d2233cb7d265dadfcb183f8.jpg' WHERE sha256 = '99df4641a00a428344d09a3236592718f3a3d2bbc688dd2b87a29f6116ea8313'
AND original_filename <> 'bca8dc1d4c24ec7c6d2233cb7d265dadfcb183f8.jpg';

UPDATE media_asset SET original_filename = '70147a1c7e76c0068f67bbecae89e48d06341e26.jpg' WHERE sha256 = '5de418c0c69454254a034f5b0375cc1ba5d77012e3df73187265c25db023bcdc'
AND original_filename <> '70147a1c7e76c0068f67bbecae89e48d06341e26.jpg';

UPDATE media_asset SET original_filename = 'cec2c1a269eb2c99839edc8add7069c9cfaec430.jpg' WHERE sha256 = '5e1bf69557f0cadc7e1ccc286e9307e51af3d7198a85bf44ff379fca849c025b'
AND original_filename <> 'cec2c1a269eb2c99839edc8add7069c9cfaec430.jpg';

UPDATE media_asset SET original_filename = '0824a3906db543b02288cc6f7206ab9e610d25b7.jpg' WHERE sha256 = '2259cdb4025c405ca9dc117fcd79844aff6a7213fdb7ee8385656c40e7832b8d'
AND original_filename <> '0824a3906db543b02288cc6f7206ab9e610d25b7.jpg';

UPDATE media_asset SET original_filename = 'f7e0d273f9b1a9a9ef2f2028faec0c19f400acad.jpg' WHERE sha256 = '700145a159397296945fdd69ef886020e7dde78afba1810fdd1daab9320507aa'
AND original_filename <> 'f7e0d273f9b1a9a9ef2f2028faec0c19f400acad.jpg';

UPDATE media_asset SET original_filename = '091bbf8ad5dd639415fefc20fa694a84feb125ea.jpg' WHERE sha256 = '421a33f92ddc4616cf2418944ad556c04f85e8196e46d892cc33050d4c845a5d'
AND original_filename <> '091bbf8ad5dd639415fefc20fa694a84feb125ea.jpg';

UPDATE media_asset SET original_filename = '55578854c56626cc4bd9a672dcd0efd73fe761ef.jpg' WHERE sha256 = '601532bafab41b6b8fbaa31ed581484c44c6450ec782e13536d911cd5ec6f502'
AND original_filename <> '55578854c56626cc4bd9a672dcd0efd73fe761ef.jpg';

UPDATE media_asset SET original_filename = '98588c1e9f26040d4eb1fbb39aa68f7d9dc42dec.jpg' WHERE sha256 = 'f3f76ea6b46bcafe74694744e254ec03d9fcd7ecefd08d29a0cc75d3629530dc'
AND original_filename <> '98588c1e9f26040d4eb1fbb39aa68f7d9dc42dec.jpg';

UPDATE media_asset SET original_filename = 'fc0970759f72de47a2301b5875c794df6b5306eb.jpg' WHERE sha256 = 'cbeb2540b428648630530ada95b0b1a143ebffc9904e84967f8483f6a5d8451c'
AND original_filename <> 'fc0970759f72de47a2301b5875c794df6b5306eb.jpg';

UPDATE media_asset SET original_filename = 'a520ec6c48e741c45090d49661cda9308776e060.jpg' WHERE sha256 = 'f58fb1bffee55d1443d54bde4b377a32a40ec0cea59149d6f98d6a0f1944f06d'
AND original_filename <> 'a520ec6c48e741c45090d49661cda9308776e060.jpg';

UPDATE media_asset SET original_filename = '7ac505a134f994fe851d0e42f66c17f70d10c21c.jpg' WHERE sha256 = 'c801401ec356b0b3a6bdbbe5851e5c6ec98c2a7ba736134df811e98dd63fcc5d'
AND original_filename <> '7ac505a134f994fe851d0e42f66c17f70d10c21c.jpg';

UPDATE media_asset SET original_filename = '6e3bcd91de7e784da32e73105323160a327bf4b0.jpg' WHERE sha256 = 'ca2e8046b3e262adba5a2e1d2c9db6c3567ea062a95003d59eda0cca9bba848a'
AND original_filename <> '6e3bcd91de7e784da32e73105323160a327bf4b0.jpg';

UPDATE media_asset SET original_filename = '312fcfc91ed58d9bed7ffb60f99aaed6d20cea86.jpg' WHERE sha256 = '92a172f396222050d149baabcbea1a79c83d111757406e8c72cf374b58e5e760'
AND original_filename <> '312fcfc91ed58d9bed7ffb60f99aaed6d20cea86.jpg';

UPDATE media_asset SET original_filename = '108c7d9a0f7590c877780b84dcad52aadeee4c49.jpg' WHERE sha256 = '1543a653c5f6f0fb7c0e799cb2d3027d8d44d73ace59df7938cdb66fd5d03657'
AND original_filename <> '108c7d9a0f7590c877780b84dcad52aadeee4c49.jpg';

UPDATE media_asset SET original_filename = '4e59e3a81926b13864686e57eab08282dbb7d568.jpg' WHERE sha256 = 'ef6c86483ca2d64c39670398807dfc0b3d709d738aa6bf7e41baef2d777de54f'
AND original_filename <> '4e59e3a81926b13864686e57eab08282dbb7d568.jpg';

UPDATE media_asset SET original_filename = 'cea9065093c70a880e703899994043f0e89f63db.jpg' WHERE sha256 = '73cfc362c0937af771679cc46dc3bcc100590351faaa404369a674121216d28e'
AND original_filename <> 'cea9065093c70a880e703899994043f0e89f63db.jpg';

COMMIT;
