-- Normalize legacy-news media display filenames. Generated by scripts/build_legacy_news_seed.py.
SET NAMES utf8mb4;
START TRANSACTION;

UPDATE media_asset SET original_filename = '外墙隔热保温改造完成，奥飞气凝胶涂料显著提升节能性能-视频-1.mp4' WHERE sha256 = '2f41fc38696f7f3c7a8ddf7b590e79b2c5e9a77fb2d528015036592994691fcc'
AND original_filename <> '外墙隔热保温改造完成，奥飞气凝胶涂料显著提升节能性能-视频-1.mp4';

UPDATE media_asset SET original_filename = '长沙屋顶隔热保温望城区山与墅项目圆满完工，奥飞涂料助力清凉过夏-视频-1.mp4' WHERE sha256 = '981448f2b52ae4642b5ac325fa8bb515655192c1ccee0f71cab9e33f85f227f7'
AND original_filename <> '长沙屋顶隔热保温望城区山与墅项目圆满完工，奥飞涂料助力清凉过夏-视频-1.mp4';

UPDATE media_asset SET original_filename = '为迎接93大阅兵，停工半日，邀请全员工停下脚步，缅怀历史-视频-1.mp4' WHERE sha256 = 'ae0e98eda3e42b1cb798dd76b0cb16364079ec1aaab009458f2cc434d7b285cd'
AND original_filename <> '为迎接93大阅兵，停工半日，邀请全员工停下脚步，缅怀历史-视频-1.mp4';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶固废产品处理产业化技术-图片-1.jpg' WHERE sha256 = '4c81252b7c535b2760eeb7d4656e42de3078cb99ddc394d35ee4a7d12a76de2b'
AND original_filename <> 'SiO₂气凝胶固废产品处理产业化技术-图片-1.jpg';

UPDATE media_asset SET original_filename = '气凝胶涂料产业化技术-图片-1.jpg' WHERE sha256 = '8d357c9b181fa398e839bbe312ab1d35a69d70d3e5f41055edf5e674bed09755'
AND original_filename <> '气凝胶涂料产业化技术-图片-1.jpg';

UPDATE media_asset SET original_filename = '气凝胶涂料产业化技术-图片-2.jpg' WHERE sha256 = '80153eab04f13ec7fa411df83572338c9671f16ddc54375c71ea4ba1f484077f'
AND original_filename <> '气凝胶涂料产业化技术-图片-2.jpg';

UPDATE media_asset SET original_filename = '气凝胶涂料产业化技术-图片-3.jpg' WHERE sha256 = 'caed9aebcce512c2ebfcd83d8a9bf146899817ff7e0be9e0c9786fef0f6e5625'
AND original_filename <> '气凝胶涂料产业化技术-图片-3.jpg';

UPDATE media_asset SET original_filename = '气凝胶涂料产业化技术-图片-4.jpg' WHERE sha256 = '9efdfef4d48b13084250f75d33b16d41ae072eb717787783f8561edf4fd9f793'
AND original_filename <> '气凝胶涂料产业化技术-图片-4.jpg';

UPDATE media_asset SET original_filename = '高性能SiO₂气凝胶产业化技术-图片-1.jpg' WHERE sha256 = '3b6608077d06aa72b9da2c52092344be794acbc191063e0b62dc925aea07475b'
AND original_filename <> '高性能SiO₂气凝胶产业化技术-图片-1.jpg';

UPDATE media_asset SET original_filename = 'C919国产大飞机产业链-图片-1.jpg' WHERE sha256 = 'c92d58ee914d0100519eeec8c9c852144f03a2d03525a6aa7c99635163c5cede'
AND original_filename <> 'C919国产大飞机产业链-图片-1.jpg';

UPDATE media_asset SET original_filename = 'C919国产大飞机产业链-图片-2.jpg' WHERE sha256 = '08d386558b565fdcfb2027d9762cf1622d34e48c34ff645a51bd27b4935af732'
AND original_filename <> 'C919国产大飞机产业链-图片-2.jpg';

UPDATE media_asset SET original_filename = 'C919国产大飞机产业链-图片-3.jpg' WHERE sha256 = '4147e12059d04af84878a7bb1cfa8bc1479a247e61ed4b108dd3e14e88ab7508'
AND original_filename <> 'C919国产大飞机产业链-图片-3.jpg';

UPDATE media_asset SET original_filename = 'C919国产大飞机产业链-图片-4.jpg' WHERE sha256 = 'cb37cbda5504b2c19d50259d6a79e2740aa07a17b0d238465e0050329442c3b9'
AND original_filename <> 'C919国产大飞机产业链-图片-4.jpg';

UPDATE media_asset SET original_filename = 'C919国产大飞机产业链-图片-5.jpg' WHERE sha256 = '5081b594ad156f5fe220e5884319a014d457bc339b79e51985ea1deb8dc2ba34'
AND original_filename <> 'C919国产大飞机产业链-图片-5.jpg';

UPDATE media_asset SET original_filename = 'C919国产大飞机产业链-图片-6.jpg' WHERE sha256 = '7dc6bcd540264bd1aa3afa6a290874b52bd103aa68126392c08fffcfb637a935'
AND original_filename <> 'C919国产大飞机产业链-图片-6.jpg';

UPDATE media_asset SET original_filename = 'C919国产大飞机产业链-图片-7.jpg' WHERE sha256 = '88ebd0b3c1b36f7edec6d9101afbc606758a00efc9d8fb95e4880013bc3e9710'
AND original_filename <> 'C919国产大飞机产业链-图片-7.jpg';

UPDATE media_asset SET original_filename = 'C919国产大飞机产业链-图片-8.jpg' WHERE sha256 = '6d106efb6b1eb70d28b7c8c835cf5b5c3627e533dde126173302f006a24b18b5'
AND original_filename <> 'C919国产大飞机产业链-图片-8.jpg';

UPDATE media_asset SET original_filename = 'C919国产大飞机产业链-图片-9.jpg' WHERE sha256 = '9a1fe5b7e2ece8b7ca6032208980e026a38af41c8976d82c1b8bf346962428e0'
AND original_filename <> 'C919国产大飞机产业链-图片-9.jpg';

UPDATE media_asset SET original_filename = '中南大学携手三一集团举办气凝胶材料研讨会 推动新材料创新应用-图片-1.jpg' WHERE sha256 = '04e633ca88a7aec6ba1b81f384670cb552c0c5a270eefd26711e201c47a49441'
AND original_filename <> '中南大学携手三一集团举办气凝胶材料研讨会 推动新材料创新应用-图片-1.jpg';

UPDATE media_asset SET original_filename = '中南大学携手三一集团举办气凝胶材料研讨会 推动新材料创新应用-图片-2.jpg' WHERE sha256 = 'bf56adf56022a8653b9464431ab319eeb0d1ff87c15cff5e5e06bd4dc9a412e5'
AND original_filename <> '中南大学携手三一集团举办气凝胶材料研讨会 推动新材料创新应用-图片-2.jpg';

UPDATE media_asset SET original_filename = '中南大学携手三一集团举办气凝胶材料研讨会 推动新材料创新应用-图片-3.jpg' WHERE sha256 = '98d5611875a71a58030cceb6d7109e99435f7deb24748b82a49388898aaa22ae'
AND original_filename <> '中南大学携手三一集团举办气凝胶材料研讨会 推动新材料创新应用-图片-3.jpg';

UPDATE media_asset SET original_filename = '为何气凝胶逐渐替代传统保温系统？-图片-1.jpg' WHERE sha256 = '39f3ecf508092d208da622c6462231f8c98e16c48c65f9071aa381cbf6105042'
AND original_filename <> '为何气凝胶逐渐替代传统保温系统？-图片-1.jpg';

UPDATE media_asset SET original_filename = '为何气凝胶逐渐替代传统保温系统？-图片-2.jpg' WHERE sha256 = '8144562611f4f88a6875d5dfbbd6443c06a295087669d3bb31ff73301800954e'
AND original_filename <> '为何气凝胶逐渐替代传统保温系统？-图片-2.jpg';

UPDATE media_asset SET original_filename = '为迎接93大阅兵，停工半日，邀请全员工停下脚步，缅怀历史-图片-1.webp' WHERE sha256 = '92dc806c820fa9204db68c200635641c2657e207336a2b103dac56d9ec99bc5e'
AND original_filename <> '为迎接93大阅兵，停工半日，邀请全员工停下脚步，缅怀历史-图片-1.webp';

UPDATE media_asset SET original_filename = '为迎接93大阅兵，停工半日，邀请全员工停下脚步，缅怀历史-图片-2.webp' WHERE sha256 = '179e1e7a06ffdc1956618130dc2be4b1fb82e5c10914514ecb0dc45ededef472'
AND original_filename <> '为迎接93大阅兵，停工半日，邀请全员工停下脚步，缅怀历史-图片-2.webp';

UPDATE media_asset SET original_filename = '为迎接93大阅兵，停工半日，邀请全员工停下脚步，缅怀历史-图片-3.webp' WHERE sha256 = 'f12f3af66d2b494b3b25347440803ed71cd0aa15436b4ebf2371661a9066b1b9'
AND original_filename <> '为迎接93大阅兵，停工半日，邀请全员工停下脚步，缅怀历史-图片-3.webp';

UPDATE media_asset SET original_filename = '从隔热原理到隔热效果计算，一文带你全面把控建筑气凝胶隔热涂料的卓越能力！-图片-1.jpg' WHERE sha256 = '9a5044ffcc80fda8e9c5a1c9b527a9ac86f950b0aa5e159c8c5d476255db7994'
AND original_filename <> '从隔热原理到隔热效果计算，一文带你全面把控建筑气凝胶隔热涂料的卓越能力！-图片-1.jpg';

UPDATE media_asset SET original_filename = '从隔热原理到隔热效果计算，一文带你全面把控建筑气凝胶隔热涂料的卓越能力！-图片-2.jpg' WHERE sha256 = 'a88e74443e8d2ef593915e286fe6e9d062ea040b622dda6daed375b2762e134f'
AND original_filename <> '从隔热原理到隔热效果计算，一文带你全面把控建筑气凝胶隔热涂料的卓越能力！-图片-2.jpg';

UPDATE media_asset SET original_filename = '从隔热原理到隔热效果计算，一文带你全面把控建筑气凝胶隔热涂料的卓越能力！-图片-3.jpg' WHERE sha256 = '162eff092bb955bdaa72b96038e77e57d493b32ad38c1ea556eaa909bab833c4'
AND original_filename <> '从隔热原理到隔热效果计算，一文带你全面把控建筑气凝胶隔热涂料的卓越能力！-图片-3.jpg';

UPDATE media_asset SET original_filename = '从隔热原理到隔热效果计算，一文带你全面把控建筑气凝胶隔热涂料的卓越能力！-图片-4.jpg' WHERE sha256 = '6f4b5e0c898c931a1aeee9ca56dc412da869d40f827b943b184036533f256778'
AND original_filename <> '从隔热原理到隔热效果计算，一文带你全面把控建筑气凝胶隔热涂料的卓越能力！-图片-4.jpg';

UPDATE media_asset SET original_filename = '从隔热原理到隔热效果计算，一文带你全面把控建筑气凝胶隔热涂料的卓越能力！-图片-5.jpg' WHERE sha256 = 'b36f8de1b138080f1b4643fba1bfbe542c6b69420bd09294ebb101e6aa333bd0'
AND original_filename <> '从隔热原理到隔热效果计算，一文带你全面把控建筑气凝胶隔热涂料的卓越能力！-图片-5.jpg';

UPDATE media_asset SET original_filename = '从隔热原理到隔热效果计算，一文带你全面把控建筑气凝胶隔热涂料的卓越能力！-图片-6.jpg' WHERE sha256 = '40719704d453e4866752edece0ced389882742491b0125736310786dbd6cb9cd'
AND original_filename <> '从隔热原理到隔热效果计算，一文带你全面把控建筑气凝胶隔热涂料的卓越能力！-图片-6.jpg';

UPDATE media_asset SET original_filename = '从隔热原理到隔热效果计算，一文带你全面把控建筑气凝胶隔热涂料的卓越能力！-图片-7.jpg' WHERE sha256 = '63b9188a6cf11da6d6fea9d5775e75d6ecfc0b8114f14313f70be16274619fdb'
AND original_filename <> '从隔热原理到隔热效果计算，一文带你全面把控建筑气凝胶隔热涂料的卓越能力！-图片-7.jpg';

UPDATE media_asset SET original_filename = '从隔热原理到隔热效果计算，一文带你全面把控建筑气凝胶隔热涂料的卓越能力！-图片-8.jpg' WHERE sha256 = '8116d998386e6e1611f0a87388b40592c3a215e3380194055b2e89795a6e99ee'
AND original_filename <> '从隔热原理到隔热效果计算，一文带你全面把控建筑气凝胶隔热涂料的卓越能力！-图片-8.jpg';

UPDATE media_asset SET original_filename = '住房和城乡建设部党组书记、部长部长倪虹发文，房地产发展方向明确！-图片-1.jpg' WHERE sha256 = '13d782f5ab0475069c511580291aa742ea8513abb319d40c2b06c0b7f09201d6'
AND original_filename <> '住房和城乡建设部党组书记、部长部长倪虹发文，房地产发展方向明确！-图片-1.jpg';

UPDATE media_asset SET original_filename = '南大学孙正明、张培根、苏州纳米所王锦ChemSusChem：具有优异热稳定性和固有阻燃性的超轻M5气凝胶-图片-1.jpg' WHERE sha256 = '9885ea9580c93ddc6417dfb754da7aa456acc31cd54446db3b76e192a278c2e0'
AND original_filename <> '南大学孙正明、张培根、苏州纳米所王锦ChemSusChem：具有优异热稳定性和固有阻燃性的超轻M5气凝胶-图片-1.jpg';

UPDATE media_asset SET original_filename = '南大学孙正明、张培根、苏州纳米所王锦ChemSusChem：具有优异热稳定性和固有阻燃性的超轻M5气凝胶-图片-2.jpg' WHERE sha256 = '76052bf8b6173514e21c5d67f5bb27cc8d1d0adfa70cdf7a37d7abd4a0e529c6'
AND original_filename <> '南大学孙正明、张培根、苏州纳米所王锦ChemSusChem：具有优异热稳定性和固有阻燃性的超轻M5气凝胶-图片-2.jpg';

UPDATE media_asset SET original_filename = '南大学孙正明、张培根、苏州纳米所王锦ChemSusChem：具有优异热稳定性和固有阻燃性的超轻M5气凝胶-图片-3.jpg' WHERE sha256 = 'cf042c0caacd5141c0f4240cfef2fa2da3e35dfd903116cd536fbe4a1b9fb18e'
AND original_filename <> '南大学孙正明、张培根、苏州纳米所王锦ChemSusChem：具有优异热稳定性和固有阻燃性的超轻M5气凝胶-图片-3.jpg';

UPDATE media_asset SET original_filename = '南大学孙正明、张培根、苏州纳米所王锦ChemSusChem：具有优异热稳定性和固有阻燃性的超轻M5气凝胶-图片-4.jpg' WHERE sha256 = '3e44e75465ab6f1108018cbdac493f49aecc958cba1a2c251d5a7f0adcb6d873'
AND original_filename <> '南大学孙正明、张培根、苏州纳米所王锦ChemSusChem：具有优异热稳定性和固有阻燃性的超轻M5气凝胶-图片-4.jpg';

UPDATE media_asset SET original_filename = '奥飞新材宋淼教授与张丁日博士亮相2025建筑低碳涂料产业发展大会，推动建筑行业绿色转型-图片-1.jpg' WHERE sha256 = '54188c152ecfd61f2821d95ad6da946f2e02d89bddcd963c3071079772c9e501'
AND original_filename <> '奥飞新材宋淼教授与张丁日博士亮相2025建筑低碳涂料产业发展大会，推动建筑行业绿色转型-图片-1.jpg';

UPDATE media_asset SET original_filename = '奥飞新材宋淼教授与张丁日博士亮相2025建筑低碳涂料产业发展大会，推动建筑行业绿色转型-图片-2.jpg' WHERE sha256 = '22d5fe340efac51b3abb5edfd002e58ef7424abc4da85c3476e423c9efa2e7eb'
AND original_filename <> '奥飞新材宋淼教授与张丁日博士亮相2025建筑低碳涂料产业发展大会，推动建筑行业绿色转型-图片-2.jpg';

UPDATE media_asset SET original_filename = '奥飞新材宋淼教授与张丁日博士亮相2025建筑低碳涂料产业发展大会，推动建筑行业绿色转型-图片-3.jpg' WHERE sha256 = 'e3031aecc7d6a4cd49b59ae390b21a333b0c3e038111fe1a57dc20d4c44e55c4'
AND original_filename <> '奥飞新材宋淼教授与张丁日博士亮相2025建筑低碳涂料产业发展大会，推动建筑行业绿色转型-图片-3.jpg';

UPDATE media_asset SET original_filename = '奥飞新材宋淼教授与张丁日博士亮相2025建筑低碳涂料产业发展大会，推动建筑行业绿色转型-图片-4.jpg' WHERE sha256 = '8db0ada5a32ea82e30ae92f52951de37c563484b6a0febcb4961526ea158384c'
AND original_filename <> '奥飞新材宋淼教授与张丁日博士亮相2025建筑低碳涂料产业发展大会，推动建筑行业绿色转型-图片-4.jpg';

UPDATE media_asset SET original_filename = '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-1.jpg' WHERE sha256 = 'e831bf2a320799c8cfa1ab21cfdaefd4f12638c4e255da563f92dd83edde2829'
AND original_filename <> '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-1.jpg';

UPDATE media_asset SET original_filename = '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-2.jpg' WHERE sha256 = '02a81b767e7dacdc93dc6a7ed183079edc624afc538e4191de70c14303a344d3'
AND original_filename <> '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-2.jpg';

UPDATE media_asset SET original_filename = '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-3.jpg' WHERE sha256 = 'b15d11a0665253237f85b500e1c0abf39fae40fcc2628ee7432d3accd5ecbad8'
AND original_filename <> '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-3.jpg';

UPDATE media_asset SET original_filename = '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-4.jpg' WHERE sha256 = 'c33981e96e6a73ea9bbc9a6c0466171f8db3e7e9fac80c81bb8595dad3128a80'
AND original_filename <> '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-4.jpg';

UPDATE media_asset SET original_filename = '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-5.jpg' WHERE sha256 = 'ff2ea9c9eb697bbaf7c04d59638fa720ff9d8feae6ca16b4854af25f3d45b682'
AND original_filename <> '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-5.jpg';

UPDATE media_asset SET original_filename = '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-6.jpg' WHERE sha256 = '571c747b44691cb6136be03c1047d10e99c16c76d4c7e262e960aa29a8f155ef'
AND original_filename <> '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-6.jpg';

UPDATE media_asset SET original_filename = '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-7.jpg' WHERE sha256 = '3867ea32342d804f49b9ebad6c76d83b7e48781027e12a173c7120e9218b2fbe'
AND original_filename <> '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-7.jpg';

UPDATE media_asset SET original_filename = '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-8.jpg' WHERE sha256 = '3bbfd92f9c79e0479eb0cf15b2b3b1c6a9b3a9b259e8f3c5e4d6a7433d5568f5'
AND original_filename <> '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-8.jpg';

UPDATE media_asset SET original_filename = '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-9.jpg' WHERE sha256 = 'a54e35c5aed01bc5464ab1e5243055ad8d7c5bf0ea6f07464fe8e75cad1eeae2'
AND original_filename <> '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-9.jpg';

UPDATE media_asset SET original_filename = '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-10.jpg' WHERE sha256 = '20a7a7218a6a9993a6b537d0268f40738ed4e9c1069e2f36714d2fe301d1980c'
AND original_filename <> '奥飞新材携手中南大学、立邦中国、三一筑工共同打造气凝胶产业化应用深度融合新范式-图片-10.jpg';

UPDATE media_asset SET original_filename = '奥飞新材携手中建八局南方公司开展气凝胶技术专题交流-图片-1.jpg' WHERE sha256 = '6f2930b1badf2b02eec34500ca11320c08d95b4e1c260281409f661bb4d2de70'
AND original_filename <> '奥飞新材携手中建八局南方公司开展气凝胶技术专题交流-图片-1.jpg';

UPDATE media_asset SET original_filename = '奥飞新材携手中建八局南方公司开展气凝胶技术专题交流-图片-2.jpg' WHERE sha256 = 'cfb4d2d7e2cba96f1a844a2070ecb03f37f42c22d6330c6145f4e3cec15ce55d'
AND original_filename <> '奥飞新材携手中建八局南方公司开展气凝胶技术专题交流-图片-2.jpg';

UPDATE media_asset SET original_filename = '奥飞新材积极参与长沙市“AI赋能新质生产力”培训，助力企业科技创新升级-图片-1.jpg' WHERE sha256 = '240327f0701a173d042f3e6bf688ad250c40a0d7f65015e6b93718c07d91bd82'
AND original_filename <> '奥飞新材积极参与长沙市“AI赋能新质生产力”培训，助力企业科技创新升级-图片-1.jpg';

UPDATE media_asset SET original_filename = '奥飞气凝胶涂料：以创新科技助力-好房子-建设新赛道-图片-1.jpg' WHERE sha256 = 'de17c7ce84d40d2b98fe2185031303981cc5deb8e8dbda493ea8cd172d3a9703'
AND original_filename <> '奥飞气凝胶涂料：以创新科技助力-好房子-建设新赛道-图片-1.jpg';

UPDATE media_asset SET original_filename = '感谢气凝胶：守护电动车安全，奥飞新材引领低成本创新-图片-1.jpg' WHERE sha256 = '50ef60e4bd151be342a13c39867b3bba438e2d7e9b860f744c66b4f873c50f7f'
AND original_filename <> '感谢气凝胶：守护电动车安全，奥飞新材引领低成本创新-图片-1.jpg';

UPDATE media_asset SET original_filename = '感谢气凝胶：守护电动车安全，奥飞新材引领低成本创新-图片-2.jpg' WHERE sha256 = '41e69929821a034ebf01ef8352a307cd308e8aa3799bffae46efec98713a9b5c'
AND original_filename <> '感谢气凝胶：守护电动车安全，奥飞新材引领低成本创新-图片-2.jpg';

UPDATE media_asset SET original_filename = '感谢气凝胶：守护电动车安全，奥飞新材引领低成本创新-图片-3.jpg' WHERE sha256 = 'de8d83c2ad31f6b920f2b9e8759785433fd26fd578abaec5e5b8be2198980408'
AND original_filename <> '感谢气凝胶：守护电动车安全，奥飞新材引领低成本创新-图片-3.jpg';

UPDATE media_asset SET original_filename = '感谢气凝胶：守护电动车安全，奥飞新材引领低成本创新-图片-4.jpg' WHERE sha256 = '8418a050bbc0d7c6b5a346a23a2d2dc88e6ce5ff0e7aca7133f6090c7649f4c3'
AND original_filename <> '感谢气凝胶：守护电动车安全，奥飞新材引领低成本创新-图片-4.jpg';

UPDATE media_asset SET original_filename = '感谢气凝胶：守护电动车安全，奥飞新材引领低成本创新-图片-5.jpg' WHERE sha256 = '6aac77bd0615ad2fe68dbd5a47e85add894591f8f4a54cbc7ac1782c0b9628a6'
AND original_filename <> '感谢气凝胶：守护电动车安全，奥飞新材引领低成本创新-图片-5.jpg';

UPDATE media_asset SET original_filename = '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-1.jpg' WHERE sha256 = 'fb580cce639fa0ec2890bb98431c08f5b8138c19ec4cd44f58240faa74b988c4'
AND original_filename <> '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-1.jpg';

UPDATE media_asset SET original_filename = '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-2.jpg' WHERE sha256 = '0967948faa2dd2db272dfd38a257aab293fadf9d0437acf23ceabc087db3e033'
AND original_filename <> '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-2.jpg';

UPDATE media_asset SET original_filename = '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-3.jpg' WHERE sha256 = '0e7aa80a83cd56c14f8dc8819e6e5912c8ad824aad0eb513cc7d63b6266f929d'
AND original_filename <> '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-3.jpg';

UPDATE media_asset SET original_filename = '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-4.jpg' WHERE sha256 = '22347afe66acc3f2a3970b2197611a51a1ddd1373dddd39dce1b9cd964183c85'
AND original_filename <> '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-4.jpg';

UPDATE media_asset SET original_filename = '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-5.jpg' WHERE sha256 = 'b222718ee8eb4bf50ce3e4045c766d2f20fe487288d9c51e5b2576f2c46f3a8e'
AND original_filename <> '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-5.jpg';

UPDATE media_asset SET original_filename = '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-6.jpg' WHERE sha256 = '35be60653a1a8c11de7a79225f20bc6808fbbd2d2c2c357982acc3cd7aea912f'
AND original_filename <> '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-6.jpg';

UPDATE media_asset SET original_filename = '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-7.jpg' WHERE sha256 = 'd3960254f6f14b7a6a1833d2d916173519c5a36fba90d56ed03b81e25c9796ac'
AND original_filename <> '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-7.jpg';

UPDATE media_asset SET original_filename = '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-8.jpg' WHERE sha256 = '2caa863d178b2f72535819c830117d4614f69901482e9b907102dcf33f213db4'
AND original_filename <> '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-8.jpg';

UPDATE media_asset SET original_filename = '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-9.jpg' WHERE sha256 = '40578a6d973dd49361dcc8e5ae4585220439d4652d7aa774d50a64a2b4e2654b'
AND original_filename <> '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-9.jpg';

UPDATE media_asset SET original_filename = '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-10.jpg' WHERE sha256 = '596d986bad092e0f5668d0818886f86bdbe55cd6bf8f43e3046ae47e33145cf3'
AND original_filename <> '技术赋能·跨域共生‖2026年先进制造技术总师交流活动（第一期）成功举办-图片-10.jpg';

UPDATE media_asset SET original_filename = '探秘气凝胶：建筑领域的“绿色新宠”，奥飞新材气凝胶涂料助力绿色建筑-图片-1.jpg' WHERE sha256 = '2fa658386565db34d45fa26798ed5c9dc1a260c05b22282ba215ceacbae797aa'
AND original_filename <> '探秘气凝胶：建筑领域的“绿色新宠”，奥飞新材气凝胶涂料助力绿色建筑-图片-1.jpg';

UPDATE media_asset SET original_filename = '探秘气凝胶：建筑领域的“绿色新宠”，奥飞新材气凝胶涂料助力绿色建筑-图片-2.jpg' WHERE sha256 = 'db2c29022a773680202c0709342373eed298b02359ebb0a38d2bbc929ade88fd'
AND original_filename <> '探秘气凝胶：建筑领域的“绿色新宠”，奥飞新材气凝胶涂料助力绿色建筑-图片-2.jpg';

UPDATE media_asset SET original_filename = '探秘气凝胶：建筑领域的“绿色新宠”，奥飞新材气凝胶涂料助力绿色建筑-图片-3.jpg' WHERE sha256 = '84f5799c042bd025fd2ff1b512f19caea799eedab9c81a0fc1ca44467e34d14f'
AND original_filename <> '探秘气凝胶：建筑领域的“绿色新宠”，奥飞新材气凝胶涂料助力绿色建筑-图片-3.jpg';

UPDATE media_asset SET original_filename = '气凝胶材料如何由航天专供转向日常民用-图片-1.jpg' WHERE sha256 = '2b9e65f83cf1244db1cb43cdd66b2a73ced7c356e68137c918ed6272c28ac34a'
AND original_filename <> '气凝胶材料如何由航天专供转向日常民用-图片-1.jpg';

UPDATE media_asset SET original_filename = '气凝胶材料如何由航天专供转向日常民用-图片-2.jpg' WHERE sha256 = '0ae35d38ad61929290854a5139c5d1c118a4392bcca3e8c5197bbfd09948dab0'
AND original_filename <> '气凝胶材料如何由航天专供转向日常民用-图片-2.jpg';

UPDATE media_asset SET original_filename = '气凝胶材料如何由航天专供转向日常民用-图片-3.jpg' WHERE sha256 = '3ab0c2c4276bed949121b5524f52797f19996dc0aa5de1bbad0a0dd462a3440f'
AND original_filename <> '气凝胶材料如何由航天专供转向日常民用-图片-3.jpg';

UPDATE media_asset SET original_filename = '气凝胶材料如何由航天专供转向日常民用-图片-4.jpg' WHERE sha256 = '94a34b95caff1b763254ed4ae7d493b0eea0164c83b8278d01268b571f5e2dd3'
AND original_filename <> '气凝胶材料如何由航天专供转向日常民用-图片-4.jpg';

UPDATE media_asset SET original_filename = '气凝胶材料如何由航天专供转向日常民用-图片-5.jpg' WHERE sha256 = '329e160e75b91b9eb2aa4cfd9ae36ba3e7b213ec7fae325b06cdbb153c803be5'
AND original_filename <> '气凝胶材料如何由航天专供转向日常民用-图片-5.jpg';

UPDATE media_asset SET original_filename = '气凝胶材料如何由航天专供转向日常民用-图片-6.jpg' WHERE sha256 = '7d2e67eb730d476f5e4dabeb8e133afc645655e06a30193017a5c8430c47e774'
AND original_filename <> '气凝胶材料如何由航天专供转向日常民用-图片-6.jpg';

UPDATE media_asset SET original_filename = '气凝胶涂料 地下室防潮防结露终极解决方案【权威解析】-图片-1.jpg' WHERE sha256 = 'ac1f5256f68fba13981237b8cff4940025e945df4143bd9101d6430d722e12d8'
AND original_filename <> '气凝胶涂料 地下室防潮防结露终极解决方案【权威解析】-图片-1.jpg';

UPDATE media_asset SET original_filename = '气凝胶涂料 地下室防潮防结露终极解决方案【权威解析】-图片-2.jpg' WHERE sha256 = '612846ae45a345062e38f2381a022c7935cddde722549692a8b59b159e6a7ef5'
AND original_filename <> '气凝胶涂料 地下室防潮防结露终极解决方案【权威解析】-图片-2.jpg';

UPDATE media_asset SET original_filename = '气凝胶涂料 地下室防潮防结露终极解决方案【权威解析】-图片-3.jpg' WHERE sha256 = '69164e7c01be9da3161263f1e276c4c94be4df6e3656ce985f5d1f3333aaf93d'
AND original_filename <> '气凝胶涂料 地下室防潮防结露终极解决方案【权威解析】-图片-3.jpg';

UPDATE media_asset SET original_filename = '气凝胶涂料 地下室防潮防结露终极解决方案【权威解析】-图片-4.jpg' WHERE sha256 = '813c22954c4ce7876d86ab7fa8ed31a8712381620ae0d8a2bc969b43a76d67bd'
AND original_filename <> '气凝胶涂料 地下室防潮防结露终极解决方案【权威解析】-图片-4.jpg';

UPDATE media_asset SET original_filename = '气凝胶涂料如何在建筑领域领跑！-图片-1.jpg' WHERE sha256 = 'f6ea61d4949c9c4f91720871df89b8cee4911e5b71242e8a3892628b3a526714'
AND original_filename <> '气凝胶涂料如何在建筑领域领跑！-图片-1.jpg';

UPDATE media_asset SET original_filename = '气凝胶涂料如何在建筑领域领跑！-图片-2.jpg' WHERE sha256 = 'b87e26308c1748d67c235fa6d87dc9f1abfc5d8d1035fb6af7221a89a592d65d'
AND original_filename <> '气凝胶涂料如何在建筑领域领跑！-图片-2.jpg';

UPDATE media_asset SET original_filename = '水凝胶与气凝胶的制作和区别-图片-1.jpg' WHERE sha256 = '982291b9eb1ae67c0f1599db194bfa0168b19d6a18cfbb1ea16c43f1c8af6cd2'
AND original_filename <> '水凝胶与气凝胶的制作和区别-图片-1.jpg';

UPDATE media_asset SET original_filename = '水凝胶与气凝胶的制作和区别-图片-2.jpg' WHERE sha256 = 'b303e6124ce25850cf7559081a30988f5e783b72ccfe2f8d27e9ab4a6c932b2c'
AND original_filename <> '水凝胶与气凝胶的制作和区别-图片-2.jpg';

UPDATE media_asset SET original_filename = '水凝胶与气凝胶的制作和区别-图片-3.jpg' WHERE sha256 = '605f907c146bc64e24b6f9675c58e5c02018404c06bb94e4a27f6f697e2bf12b'
AND original_filename <> '水凝胶与气凝胶的制作和区别-图片-3.jpg';

UPDATE media_asset SET original_filename = '水凝胶与气凝胶的制作和区别-图片-4.jpg' WHERE sha256 = 'e34b735886a91e4275d5eddc41f19fb864a2ae55b82ae7f9975f36bcd5c80cba'
AND original_filename <> '水凝胶与气凝胶的制作和区别-图片-4.jpg';

UPDATE media_asset SET original_filename = '水凝胶与气凝胶的制作和区别-图片-5.jpg' WHERE sha256 = '1903a369877ab932e2850ebe8494396b8c581ce4c743f69fbbadc71a0b82470a'
AND original_filename <> '水凝胶与气凝胶的制作和区别-图片-5.jpg';

UPDATE media_asset SET original_filename = '水泥自流平砂浆施工指南 - 垫层水泥自流平地坪完整施工作业书-图片-1.jpg' WHERE sha256 = '5a3d553817300d429c8973551f512c0b9896bc8938dccf434a1071b7323e1391'
AND original_filename <> '水泥自流平砂浆施工指南 - 垫层水泥自流平地坪完整施工作业书-图片-1.jpg';

UPDATE media_asset SET original_filename = '水泥自流平砂浆施工指南 - 垫层水泥自流平地坪完整施工作业书-图片-2.jpg' WHERE sha256 = '02ecba2bb5bd94f8cc0afb473edfe1a4b7281bc57eb6e3357c3b6d5967733cbe'
AND original_filename <> '水泥自流平砂浆施工指南 - 垫层水泥自流平地坪完整施工作业书-图片-2.jpg';

UPDATE media_asset SET original_filename = '水泥自流平砂浆施工指南 - 垫层水泥自流平地坪完整施工作业书-图片-3.jpg' WHERE sha256 = 'f07701c47084bb445e0445296fbc9b0385d88bd83e6315ca74e1d0d3f657a39c'
AND original_filename <> '水泥自流平砂浆施工指南 - 垫层水泥自流平地坪完整施工作业书-图片-3.jpg';

UPDATE media_asset SET original_filename = '湖南奥飞新材料有限公司入选湖南省动力工程学会候选理事单位，助力行业创新发展-图片-1.jpg' WHERE sha256 = '67dc4507e1d0ef398fb66adce2d947191242801d399b1a710f60d975b81637c7'
AND original_filename <> '湖南奥飞新材料有限公司入选湖南省动力工程学会候选理事单位，助力行业创新发展-图片-1.jpg';

UPDATE media_asset SET original_filename = '湖湘聚力 共襄兴湘——2025“校友回湘”大会圆满召开-图片-1.jpg' WHERE sha256 = 'fb7ae9ccef8d7e800dc516e05c386010e402c4e1f066d20ba8686bfe8ea01df8'
AND original_filename <> '湖湘聚力 共襄兴湘——2025“校友回湘”大会圆满召开-图片-1.jpg';

UPDATE media_asset SET original_filename = '湖湘聚力 共襄兴湘——2025“校友回湘”大会圆满召开-图片-2.jpg' WHERE sha256 = 'e558b8b006dcaaff65147b76b077a829767e841963f81a49b672958bbc7e4d3b'
AND original_filename <> '湖湘聚力 共襄兴湘——2025“校友回湘”大会圆满召开-图片-2.jpg';

UPDATE media_asset SET original_filename = '湖湘聚力 共襄兴湘——2025“校友回湘”大会圆满召开-图片-3.jpg' WHERE sha256 = '5a0f1b22815c4255eabdf39c276cc61d6065acb08322e59db90df67c8cfbc458'
AND original_filename <> '湖湘聚力 共襄兴湘——2025“校友回湘”大会圆满召开-图片-3.jpg';

UPDATE media_asset SET original_filename = '湖湘聚力 共襄兴湘——2025“校友回湘”大会圆满召开-图片-4.jpg' WHERE sha256 = 'b8f12b8db5202222d4cffa7c94916bbbfb07dc1a9ef48887e1bb999977c88f5e'
AND original_filename <> '湖湘聚力 共襄兴湘——2025“校友回湘”大会圆满召开-图片-4.jpg';

UPDATE media_asset SET original_filename = '筑牢城防屏障——奥飞AFJZ-WGF-B2外墙耐候隔热涂料确保安全度过极端大风天气-图片-1.jpg' WHERE sha256 = 'e67746bbf7927ea30285986f5779c32e1ef276a630d5db6a14d10f47630500ab'
AND original_filename <> '筑牢城防屏障——奥飞AFJZ-WGF-B2外墙耐候隔热涂料确保安全度过极端大风天气-图片-1.jpg';

UPDATE media_asset SET original_filename = '筑牢城防屏障——奥飞AFJZ-WGF-B2外墙耐候隔热涂料确保安全度过极端大风天气-图片-2.jpg' WHERE sha256 = 'f78cd1e55842942b40ff9e465a9cf7b21fb8822184f8c1efeb75858f89274b74'
AND original_filename <> '筑牢城防屏障——奥飞AFJZ-WGF-B2外墙耐候隔热涂料确保安全度过极端大风天气-图片-2.jpg';

UPDATE media_asset SET original_filename = '筑牢城防屏障——奥飞AFJZ-WGF-B2外墙耐候隔热涂料确保安全度过极端大风天气-图片-3.jpg' WHERE sha256 = 'cd3960c6d00acc4e657328b3351a4c079a06cd3245ba704c0f7b87de715dc50b'
AND original_filename <> '筑牢城防屏障——奥飞AFJZ-WGF-B2外墙耐候隔热涂料确保安全度过极端大风天气-图片-3.jpg';

UPDATE media_asset SET original_filename = '羽盾新材——新型隔热降噪 SiO2气凝胶柔性复合涂料获奖-图片-1.jpg' WHERE sha256 = '386df77f066d206150f46909f8a6e8f5895d79555f218ab5316d43c5d777d7b6'
AND original_filename <> '羽盾新材——新型隔热降噪 SiO2气凝胶柔性复合涂料获奖-图片-1.jpg';

UPDATE media_asset SET original_filename = '耐高温防腐涂料的介绍-图片-1.jpg' WHERE sha256 = '0fe5240cfa27b1345f3ceb0fd86b5bd5449189df14cd031d350561ee60f154db'
AND original_filename <> '耐高温防腐涂料的介绍-图片-1.jpg';

UPDATE media_asset SET original_filename = '辐射制冷涂料的研究进展-图片-1.jpg' WHERE sha256 = '69d36d5afdb8fb591920428faae86410ecd35b7e6af8373869d0c461ccb4de28'
AND original_filename <> '辐射制冷涂料的研究进展-图片-1.jpg';

UPDATE media_asset SET original_filename = '辐射制冷涂料的研究进展-图片-2.jpg' WHERE sha256 = '0c3ab5ac28dae3568bbb82114ae22cbc88fb24f4e4114ecd994565390262a9f9'
AND original_filename <> '辐射制冷涂料的研究进展-图片-2.jpg';

UPDATE media_asset SET original_filename = '长沙气温飙至45℃体感！还没用上气凝胶隔热涂料，你家墙体“正在发烧”！-图片-1.jpg' WHERE sha256 = 'adaeabf73cbaaec23155f6a4e50cbe06fa22e25e62a42b2a62611410809b35cd'
AND original_filename <> '长沙气温飙至45℃体感！还没用上气凝胶隔热涂料，你家墙体“正在发烧”！-图片-1.jpg';

UPDATE media_asset SET original_filename = '长沙气温飙至45℃体感！还没用上气凝胶隔热涂料，你家墙体“正在发烧”！-图片-5.jpg' WHERE sha256 = '1f026beb67630abcdbc341651b1c17591aa76261296a9fb118793765964eb4e9'
AND original_filename <> '长沙气温飙至45℃体感！还没用上气凝胶隔热涂料，你家墙体“正在发烧”！-图片-5.jpg';

UPDATE media_asset SET original_filename = '长沙气温飙至45℃体感！还没用上气凝胶隔热涂料，你家墙体“正在发烧”！-图片-9.jpg' WHERE sha256 = '8f3e1ed0c50094e78b87910e5652f2d456d17e3a62b1fa049d9db4989c957f65'
AND original_filename <> '长沙气温飙至45℃体感！还没用上气凝胶隔热涂料，你家墙体“正在发烧”！-图片-9.jpg';

UPDATE media_asset SET original_filename = '长沙气温飙至45℃体感！还没用上气凝胶隔热涂料，你家墙体“正在发烧”！-图片-10.jpg' WHERE sha256 = '2cd037cce2c3c16c3d33b1fbe4d9d46206633af2f8b4e082cea209c56a3e8b56'
AND original_filename <> '长沙气温飙至45℃体感！还没用上气凝胶隔热涂料，你家墙体“正在发烧”！-图片-10.jpg';

UPDATE media_asset SET original_filename = '2025年中国涂料行业发展展望：稳中求进，绿色创新引领未来-图片-1.jpg' WHERE sha256 = 'edbe15f5bc4fc31b2dcf407c850c2c7fdd1d5338a3483c0094d5a98f35bcb402'
AND original_filename <> '2025年中国涂料行业发展展望：稳中求进，绿色创新引领未来-图片-1.jpg';

UPDATE media_asset SET original_filename = '2025年中国路标漆行业发展现状及趋势分析：下游市场需求稳定增长，行业发展前景广阔-图片-1.jpg' WHERE sha256 = '65f60ba3af5e4009b04894590f1d6b6658ac444836607498d89992faef4a7f68'
AND original_filename <> '2025年中国路标漆行业发展现状及趋势分析：下游市场需求稳定增长，行业发展前景广阔-图片-1.jpg';

UPDATE media_asset SET original_filename = '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-1.jpg' WHERE sha256 = '01d2f7ab2f35448805f23bd66b325233013dd63613e87c02085484865b4c0336'
AND original_filename <> '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-1.jpg';

UPDATE media_asset SET original_filename = '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-2.jpg' WHERE sha256 = '3297621019cd796a57722fa84454ca0ec599d798d59aeb6fddea441e4ea383d3'
AND original_filename <> '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-2.jpg';

UPDATE media_asset SET original_filename = '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-3.jpg' WHERE sha256 = '40afb25449cd6f45d113468d70d29209972fbcfa89e2a1e372b0ee927e9e6149'
AND original_filename <> '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-3.jpg';

UPDATE media_asset SET original_filename = '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-4.jpg' WHERE sha256 = '2a82a2852b4b13a9d538747686c8da31bbf771717dd3fbc75b5687acf1a16c04'
AND original_filename <> '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-4.jpg';

UPDATE media_asset SET original_filename = '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-5.jpg' WHERE sha256 = '8c75f56dc1f65d0704363df110e8988e950020ad68ff611b28d83e6af5c5bf50'
AND original_filename <> '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-5.jpg';

UPDATE media_asset SET original_filename = '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-6.jpg' WHERE sha256 = '2950bdcf4d25b081dc6e32f20ca3e63a30013d0ea3f29ebe9d318a7a273732ae'
AND original_filename <> '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-6.jpg';

UPDATE media_asset SET original_filename = '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-7.jpg' WHERE sha256 = 'b5f6e946a4739632c3ff6fa5601b41944d9f2e3e37e69f0c548e98c36518cfc8'
AND original_filename <> '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-7.jpg';

UPDATE media_asset SET original_filename = '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-8.jpg' WHERE sha256 = 'be3509872165de3ed4ce52d53ea2e8d29791582a5c9243a3612dd723537d7634'
AND original_filename <> '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-8.jpg';

UPDATE media_asset SET original_filename = '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-9.jpg' WHERE sha256 = '6d41c48f0f2f76a61dab2ebb8178802403264904c2b732d0df8e13de9ae6c90f'
AND original_filename <> '2025年第一届岳麓先进材料论坛暨湖南省研究生创新论坛顺利举办-图片-9.jpg';

UPDATE media_asset SET original_filename = '2025年第一届岳麓先进材料论坛邀您参与-图片-1.jpg' WHERE sha256 = '1cb42714f8e63a830f7438e74e1fb3e15d0cf71158b96a04e85e253c45d61679'
AND original_filename <> '2025年第一届岳麓先进材料论坛邀您参与-图片-1.jpg';

UPDATE media_asset SET original_filename = 'HPLC、GC-MS与LC-MS的区别-图片-1.jpg' WHERE sha256 = '503f8da4bac1eff068fd94cc423320fb476d0219e617fcaf3316d2cc3b681d72'
AND original_filename <> 'HPLC、GC-MS与LC-MS的区别-图片-1.jpg';

UPDATE media_asset SET original_filename = 'Pd氢化金属烯气凝胶晶格氢参与实现高效析氢反应-图片-1.jpg' WHERE sha256 = '570116b43db3d19af81e3fe901ff1f074273ec3d767ed5d2e0c19ed33b211bf4'
AND original_filename <> 'Pd氢化金属烯气凝胶晶格氢参与实现高效析氢反应-图片-1.jpg';

UPDATE media_asset SET original_filename = 'Pd氢化金属烯气凝胶晶格氢参与实现高效析氢反应-图片-2.jpg' WHERE sha256 = 'da689db6c1b672e61a9043aced0c245acce1025220b1b924782b4e4c0105e177'
AND original_filename <> 'Pd氢化金属烯气凝胶晶格氢参与实现高效析氢反应-图片-2.jpg';

UPDATE media_asset SET original_filename = 'Pd氢化金属烯气凝胶晶格氢参与实现高效析氢反应-图片-3.jpg' WHERE sha256 = 'a2813608280549205e99877d4aae63a3ad673d28329fad8cf8fc299fd58d8ea0'
AND original_filename <> 'Pd氢化金属烯气凝胶晶格氢参与实现高效析氢反应-图片-3.jpg';

UPDATE media_asset SET original_filename = 'Pd氢化金属烯气凝胶晶格氢参与实现高效析氢反应-图片-4.jpg' WHERE sha256 = 'c1537f3ce97b47a9ad281091248476b917ad113a6098be790d0a933ef4d24c93'
AND original_filename <> 'Pd氢化金属烯气凝胶晶格氢参与实现高效析氢反应-图片-4.jpg';

UPDATE media_asset SET original_filename = 'Pd氢化金属烯气凝胶晶格氢参与实现高效析氢反应-图片-5.jpg' WHERE sha256 = '95f29c0a4d96b96a58212016a46d8698016d3c8ccbea92ca72ac4e94c52f49d4'
AND original_filename <> 'Pd氢化金属烯气凝胶晶格氢参与实现高效析氢反应-图片-5.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-1.jpg' WHERE sha256 = 'b68af51de145c200d9e63a74b5a142efd5205f57f452b4873f8e95cdac4abaa2'
AND original_filename <> 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-1.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-2.jpg' WHERE sha256 = '2810636c5c549a6bbda70c5d60b4a75b7e84f2949be60703069fb04a65110da2'
AND original_filename <> 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-2.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-3.jpg' WHERE sha256 = '34db8330ecf6852dfb0020789cba46f647255388ffa4644c498934b2067e4e74'
AND original_filename <> 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-3.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-4.jpg' WHERE sha256 = 'dee57025a7319a6f776a8c4ae7aec5ac45f92df199e6a37fd27693bb6bbe80ac'
AND original_filename <> 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-4.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-5.jpg' WHERE sha256 = '0f651b80cce969ca62ed7c9744e4cafacffa9c23fb5ffe690f09d59b0e3ae6fb'
AND original_filename <> 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-5.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-6.jpg' WHERE sha256 = '15d8c1dfbcc99f4c3d708037c2c7702e3b786919134208921cb6ef024b4df127'
AND original_filename <> 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-6.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-7.jpg' WHERE sha256 = 'efa453189b974e5d7ad6ae483e92e6d58f890470c6fb4f32825adaeb8f31beec'
AND original_filename <> 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-7.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-8.jpg' WHERE sha256 = '6641b97ba65050a0fcda40921c60c4248f5c32a0d1748936d500eebedc72d794'
AND original_filename <> 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-8.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-9.jpg' WHERE sha256 = 'cd97208cd397799fc961c721b3a4c64ed7e894a524be4722e7023268373dd478'
AND original_filename <> 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-9.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-10.jpg' WHERE sha256 = '8a4aebde9ac405f4ade0644d94c16530a7067201ec9fe8d0d656f5b7cddcdf76'
AND original_filename <> 'SiO₂气凝胶复合材料在航空航天领域的研究进展与应用前景-图片-10.jpg';

UPDATE media_asset SET original_filename = 'WMC分会介绍丨A02-Energy Storage and Catalytic Materials-图片-1.jpg' WHERE sha256 = 'b6c4a852ee76a57c0b4406b428cfe60b48d0eb5ed83a769fd17310b57ec0d85c'
AND original_filename <> 'WMC分会介绍丨A02-Energy Storage and Catalytic Materials-图片-1.jpg';

UPDATE media_asset SET original_filename = '中南大学与中建集团签署战略合作框架协议-图片-1.jpg' WHERE sha256 = '67333e01eb22054a6577f383b5575965065bb867bc9e1ca6fe00e4dc6b67c731'
AND original_filename <> '中南大学与中建集团签署战略合作框架协议-图片-1.jpg';

UPDATE media_asset SET original_filename = '中南大学物理学院2024年度湖南省重点实验室学术委员会联合会议顺利举行-图片-1.jpg' WHERE sha256 = '8e51654699db0544b721eaf58621d1cc335601aad8c556fc416c51fd0f56800d'
AND original_filename <> '中南大学物理学院2024年度湖南省重点实验室学术委员会联合会议顺利举行-图片-1.jpg';

UPDATE media_asset SET original_filename = '中南大学物理学院2024年度湖南省重点实验室学术委员会联合会议顺利举行-图片-2.jpg' WHERE sha256 = '65f4575674b4608ee269612765597e212ebe8420f60a157101762c9998ef7daa'
AND original_filename <> '中南大学物理学院2024年度湖南省重点实验室学术委员会联合会议顺利举行-图片-2.jpg';

UPDATE media_asset SET original_filename = '中国材料大会2025在厦门举办-图片-1.jpg' WHERE sha256 = '4c10fc60cf3fb832b63800717a700ca6601a3021d4bb118be10505d99c50f958'
AND original_filename <> '中国材料大会2025在厦门举办-图片-1.jpg';

UPDATE media_asset SET original_filename = '中国材料大会2025在厦门举办-图片-2.jpg' WHERE sha256 = '57e164fae66a6d6aa514873b61870bd64313223f9163288f3f354251e0938562'
AND original_filename <> '中国材料大会2025在厦门举办-图片-2.jpg';

UPDATE media_asset SET original_filename = '中国材料大会2025在厦门举办-图片-3.jpg' WHERE sha256 = 'a0c5ae262c74094bad472e61f976b08a065f3ff85cf1a28a54167a6d2e000cc4'
AND original_filename <> '中国材料大会2025在厦门举办-图片-3.jpg';

UPDATE media_asset SET original_filename = '中国科大研制超弹性硬碳气凝胶-图片-1.jpg' WHERE sha256 = '6885322521f8e09cda920a5bbcd247c76a8afc1f71a86fe25bb49da0f66ef916'
AND original_filename <> '中国科大研制超弹性硬碳气凝胶-图片-1.jpg';

UPDATE media_asset SET original_filename = '中国科大研制超弹性硬碳气凝胶-图片-2.jpg' WHERE sha256 = '272dba75b520ee21a0ccf2b7dc3c60d6b4a304aeb6d6f8a51018092d4c76ae71'
AND original_filename <> '中国科大研制超弹性硬碳气凝胶-图片-2.jpg';

UPDATE media_asset SET original_filename = '为什么有些材料传热那么慢？-图片-1.jpg' WHERE sha256 = '576616aeb78f1f5e2bc15525f2809021d3299b44ea9a023d5b35e76c06da6903'
AND original_filename <> '为什么有些材料传热那么慢？-图片-1.jpg';

UPDATE media_asset SET original_filename = '为什么有些材料传热那么慢？-图片-2.jpg' WHERE sha256 = '0e35ea8e416a23e58067156345f94c173f15a056d8bcdace4e598505a494f960'
AND original_filename <> '为什么有些材料传热那么慢？-图片-2.jpg';

UPDATE media_asset SET original_filename = '亚纳米孔疏水超薄膜：低温膜蒸馏淡化中的一种新路径-图片-1.jpg' WHERE sha256 = '0ed274f765b09c382ff3c0ba44fd7a9c5c17ecea74538ed4a570aa8b457d709d'
AND original_filename <> '亚纳米孔疏水超薄膜：低温膜蒸馏淡化中的一种新路径-图片-1.jpg';

UPDATE media_asset SET original_filename = '亚纳米孔疏水超薄膜：低温膜蒸馏淡化中的一种新路径-图片-2.jpg' WHERE sha256 = '07bded19b59021c7e09f6aca19d81e4eb10fe125619323417478cc218d1b47fc'
AND original_filename <> '亚纳米孔疏水超薄膜：低温膜蒸馏淡化中的一种新路径-图片-2.jpg';

UPDATE media_asset SET original_filename = '亚纳米孔疏水超薄膜：低温膜蒸馏淡化中的一种新路径-图片-3.jpg' WHERE sha256 = '4f0c9457fd6298ea4c217c1b4395574e679c3f17d7a49de8d806644a56749983'
AND original_filename <> '亚纳米孔疏水超薄膜：低温膜蒸馏淡化中的一种新路径-图片-3.jpg';

UPDATE media_asset SET original_filename = '什么是“吸附”？-图片-1.jpg' WHERE sha256 = '832ff496b5d738b4bca460f893d4fa998a8b7705b7e00fc4e4a246c7172f9f9d'
AND original_filename <> '什么是“吸附”？-图片-1.jpg';

UPDATE media_asset SET original_filename = '什么是“吸附”？-图片-2.jpg' WHERE sha256 = 'dd3417ff41824dd61b8d1e9d416cbcc4ee78879b6102d7c6b06e15ac2bee4524'
AND original_filename <> '什么是“吸附”？-图片-2.jpg';

UPDATE media_asset SET original_filename = '什么是“吸附”？-图片-3.jpg' WHERE sha256 = '6420c158445c3f125c28e939709986f44d559f0808830cd2e1b8b6d12f726718'
AND original_filename <> '什么是“吸附”？-图片-3.jpg';

UPDATE media_asset SET original_filename = '什么是“吸附”？-图片-4.jpg' WHERE sha256 = 'e7004cbdc2d4dcb64c5d8e5a08596469db1df527030149983e28dd819556b2e5'
AND original_filename <> '什么是“吸附”？-图片-4.jpg';

UPDATE media_asset SET original_filename = '什么是“吸附”？-图片-5.jpg' WHERE sha256 = 'b167c26557bdfb73f3f8a675c68c5fd2ac76f19d93173ea0ff1ef83239fc9943'
AND original_filename <> '什么是“吸附”？-图片-5.jpg';

UPDATE media_asset SET original_filename = '什么是“吸附”？-图片-6.jpg' WHERE sha256 = '0e71a82093433dc2bf4ac5691d0796f9addd14d0f2dfffa8e6eccf4145800756'
AND original_filename <> '什么是“吸附”？-图片-6.jpg';

UPDATE media_asset SET original_filename = '什么是“吸附”？-图片-7.jpg' WHERE sha256 = 'df43b79ebfe6c51f36a451a12cadf57c63bc011b9b25c45a9411b28179d428af'
AND original_filename <> '什么是“吸附”？-图片-7.jpg';

UPDATE media_asset SET original_filename = '什么是“吸附”？-图片-8.jpg' WHERE sha256 = '7d851d4b879e60d9d0bb91f67cf8c430107f2b34c683b53ec2b818ed8c5ecbc8'
AND original_filename <> '什么是“吸附”？-图片-8.jpg';

UPDATE media_asset SET original_filename = '从水凝胶到干凝胶：干燥过程中的结构崩塌与热质演变-图片-1.jpg' WHERE sha256 = '60b0b77dc5d657deffe5c9cf6c69440e8e5bdc8f99350160975eada6d659bf4d'
AND original_filename <> '从水凝胶到干凝胶：干燥过程中的结构崩塌与热质演变-图片-1.jpg';

UPDATE media_asset SET original_filename = '从水凝胶到干凝胶：干燥过程中的结构崩塌与热质演变-图片-2.jpg' WHERE sha256 = '4d36c83b39673e6fcf32c98b4d39defe05d7e8c6a94560a1f4da64e5124ef000'
AND original_filename <> '从水凝胶到干凝胶：干燥过程中的结构崩塌与热质演变-图片-2.jpg';

UPDATE media_asset SET original_filename = '会“流”的固体？水凝胶中的热量怎么传导-图片-1.jpg' WHERE sha256 = '7f656d32c8c84488b96a047f9c004c3735d94deab97d05dc250988a459c4bae0'
AND original_filename <> '会“流”的固体？水凝胶中的热量怎么传导-图片-1.jpg';

UPDATE media_asset SET original_filename = '会“流”的固体？水凝胶中的热量怎么传导-图片-2.jpg' WHERE sha256 = 'c12e9d17354ef683fe90a62944a8810eea629b3e6412a72d4480a02c7f6548b4'
AND original_filename <> '会“流”的固体？水凝胶中的热量怎么传导-图片-2.jpg';

UPDATE media_asset SET original_filename = '全国人大代表莫鼎革-加快气凝胶材料推广应用-图片-1.jpg' WHERE sha256 = '6b888a94a6c2d65de193771f8582f348305a330de81d89ce03b49cb77ff933fe'
AND original_filename <> '全国人大代表莫鼎革-加快气凝胶材料推广应用-图片-1.jpg';

UPDATE media_asset SET original_filename = '具有超低反射性能的非对称结构MXene-PBO气凝胶用于高性能电磁干扰屏蔽-图片-1.jpg' WHERE sha256 = '6901371be338f0d95b33898576b86c0bfb63ad80fc2f26800d351b4ae0be20c6'
AND original_filename <> '具有超低反射性能的非对称结构MXene-PBO气凝胶用于高性能电磁干扰屏蔽-图片-1.jpg';

UPDATE media_asset SET original_filename = '具有超低反射的高性能电磁干扰屏蔽用不对称结构MXene-PBO气凝胶-图片-1.jpg' WHERE sha256 = 'fc28b92248bebf01a53e3abec338cf8e1925f019dda63f9172b4e81a615e5f0c'
AND original_filename <> '具有超低反射的高性能电磁干扰屏蔽用不对称结构MXene-PBO气凝胶-图片-1.jpg';

UPDATE media_asset SET original_filename = '具有超低反射的高性能电磁干扰屏蔽用不对称结构MXene-PBO气凝胶-图片-2.jpg' WHERE sha256 = 'b4d857438b1dea381361ad32d245a7c2fc79c6fbd28495494a45caa2dd387f7c'
AND original_filename <> '具有超低反射的高性能电磁干扰屏蔽用不对称结构MXene-PBO气凝胶-图片-2.jpg';

UPDATE media_asset SET original_filename = '具有超低反射的高性能电磁干扰屏蔽用不对称结构MXene-PBO气凝胶-图片-3.jpg' WHERE sha256 = '4b358431828e78d547f8c39684e1c20aa899d660ad0eb03b8dc923cc55e7d98e'
AND original_filename <> '具有超低反射的高性能电磁干扰屏蔽用不对称结构MXene-PBO气凝胶-图片-3.jpg';

UPDATE media_asset SET original_filename = '具有超低反射的高性能电磁干扰屏蔽用不对称结构MXene-PBO气凝胶-图片-4.jpg' WHERE sha256 = '7c77c37ce1fba5eb82397fe418ebfb57ddb8718b0122b7fa3e55da86109f22f4'
AND original_filename <> '具有超低反射的高性能电磁干扰屏蔽用不对称结构MXene-PBO气凝胶-图片-4.jpg';

UPDATE media_asset SET original_filename = '具有超低反射的高性能电磁干扰屏蔽用不对称结构MXene-PBO气凝胶-图片-5.jpg' WHERE sha256 = '5350c394bc8859eabf63c374938ec2ec6e08cf26b833be4f28a50b0e12a3c963'
AND original_filename <> '具有超低反射的高性能电磁干扰屏蔽用不对称结构MXene-PBO气凝胶-图片-5.jpg';

UPDATE media_asset SET original_filename = '具有超低反射的高性能电磁干扰屏蔽用不对称结构MXene-PBO气凝胶-图片-6.jpg' WHERE sha256 = '3d23bb67745d4f7e565dd00897154a5e4df1040931918b3872bc6d51833f950d'
AND original_filename <> '具有超低反射的高性能电磁干扰屏蔽用不对称结构MXene-PBO气凝胶-图片-6.jpg';

UPDATE media_asset SET original_filename = '具有超大拉伸性和拉伸不敏感隔热性能的高屈曲纳米纤维陶瓷气凝胶-图片-1.jpg' WHERE sha256 = 'b0bdfaf2bed52f0c6bb954295e453ea5e057a5668621f5d26d1b68dafa0dca73'
AND original_filename <> '具有超大拉伸性和拉伸不敏感隔热性能的高屈曲纳米纤维陶瓷气凝胶-图片-1.jpg';

UPDATE media_asset SET original_filename = '具有超大拉伸性和拉伸不敏感隔热性能的高屈曲纳米纤维陶瓷气凝胶-图片-2.jpg' WHERE sha256 = '685211e588da57d3ec3606fa48c68a7321670ae55f4657434a7187575570ca7e'
AND original_filename <> '具有超大拉伸性和拉伸不敏感隔热性能的高屈曲纳米纤维陶瓷气凝胶-图片-2.jpg';

UPDATE media_asset SET original_filename = '具有超大拉伸性和拉伸不敏感隔热性能的高屈曲纳米纤维陶瓷气凝胶-图片-3.jpg' WHERE sha256 = 'ab967b9e70d9fe5f3737ea96e37a6f3a9925f166af8f8fbd402bc907d0358fa1'
AND original_filename <> '具有超大拉伸性和拉伸不敏感隔热性能的高屈曲纳米纤维陶瓷气凝胶-图片-3.jpg';

UPDATE media_asset SET original_filename = '具有超大拉伸性和拉伸不敏感隔热性能的高屈曲纳米纤维陶瓷气凝胶-图片-4.jpg' WHERE sha256 = 'c3a6329733d0cc53cc0104bae7506a77a80d671f3c8953f3f5b1120af26c0015'
AND original_filename <> '具有超大拉伸性和拉伸不敏感隔热性能的高屈曲纳米纤维陶瓷气凝胶-图片-4.jpg';

UPDATE media_asset SET original_filename = '具有超大拉伸性和拉伸不敏感隔热性能的高屈曲纳米纤维陶瓷气凝胶-图片-5.jpg' WHERE sha256 = 'bb1790bbb629b092ec881aabbdaed3438789e2100af38f5fe5b01aa8f4297880'
AND original_filename <> '具有超大拉伸性和拉伸不敏感隔热性能的高屈曲纳米纤维陶瓷气凝胶-图片-5.jpg';

UPDATE media_asset SET original_filename = '凝胶成型过程中的界面能调节与形貌定向导控方法-图片-1.jpg' WHERE sha256 = '1a5853b0e1fd0d044461f6766f21209d2ef0950595461cee083ba47fe07970d8'
AND original_filename <> '凝胶成型过程中的界面能调节与形貌定向导控方法-图片-1.jpg';

UPDATE media_asset SET original_filename = '凝胶成型过程中的界面能调节与形貌定向导控方法-图片-2.jpg' WHERE sha256 = '83e6e1d8c6a4f5469f49f51d5b018aa67bc4f7e90094377f3d6a08905f65e2d7'
AND original_filename <> '凝胶成型过程中的界面能调节与形貌定向导控方法-图片-2.jpg';

UPDATE media_asset SET original_filename = '发改委拟推广的绿色技术：气凝胶保温隔热涂料的多功能应用-图片-1.jpg' WHERE sha256 = 'ceac23b459a816475f7ae60257e6e76b768682fbcc4ee48475583c48a15d17ed'
AND original_filename <> '发改委拟推广的绿色技术：气凝胶保温隔热涂料的多功能应用-图片-1.jpg';

UPDATE media_asset SET original_filename = '发改委拟推广的绿色技术：气凝胶保温隔热涂料的多功能应用-图片-2.jpg' WHERE sha256 = 'f406e835dd0badd3b51140c08a958e5afa4b9a7a815223d452fee795638c0d9f'
AND original_filename <> '发改委拟推广的绿色技术：气凝胶保温隔热涂料的多功能应用-图片-2.jpg';

UPDATE media_asset SET original_filename = '发改委拟推广的绿色技术：气凝胶保温隔热涂料的多功能应用-图片-3.jpg' WHERE sha256 = 'a94adf464c1c4d1fc166fb9f82128fa82f797e438bd3786e2e0d7ef9b82dd3e0'
AND original_filename <> '发改委拟推广的绿色技术：气凝胶保温隔热涂料的多功能应用-图片-3.jpg';

UPDATE media_asset SET original_filename = '发改委拟推广的绿色技术：气凝胶保温隔热涂料的多功能应用-图片-4.jpg' WHERE sha256 = 'd624dda298b1286e84586ffb04c5a14759ae24c3a8a73d9db24048edc6dba14c'
AND original_filename <> '发改委拟推广的绿色技术：气凝胶保温隔热涂料的多功能应用-图片-4.jpg';

UPDATE media_asset SET original_filename = '响应性凝胶材料的多尺度结构控制策略-图片-1.jpg' WHERE sha256 = '789e224f0a9433a6433b10c3501507c6b0dba510603485546e774a83c595f195'
AND original_filename <> '响应性凝胶材料的多尺度结构控制策略-图片-1.jpg';

UPDATE media_asset SET original_filename = '在微重力环境下，表面张力变成了主角-图片-1.jpg' WHERE sha256 = '11a40459b0c9cbd19e2ff3b839b99cd71d6970824cd2498fcd429a79f2523c6a'
AND original_filename <> '在微重力环境下，表面张力变成了主角-图片-1.jpg';

UPDATE media_asset SET original_filename = '基于专利信息的水性聚氨酯全球发展现状及对策分析-图片-1.jpg' WHERE sha256 = 'db0816f2ef782c7acb638c79f26be2c95a4f763782809afa70f0cfc7f52da388'
AND original_filename <> '基于专利信息的水性聚氨酯全球发展现状及对策分析-图片-1.jpg';

UPDATE media_asset SET original_filename = '基于专利信息的水性聚氨酯全球发展现状及对策分析-图片-2.jpg' WHERE sha256 = '643ee781568dcfd81c421dbcde890011267b84082aa336f99773c39712f07059'
AND original_filename <> '基于专利信息的水性聚氨酯全球发展现状及对策分析-图片-2.jpg';

UPDATE media_asset SET original_filename = '声波强化传热传质与蒸发冷凝-图片-1.jpg' WHERE sha256 = 'b736b935b1bed76ad67120d9016b16cb64cc64272e166588e212f57e69fcb786'
AND original_filename <> '声波强化传热传质与蒸发冷凝-图片-1.jpg';

UPDATE media_asset SET original_filename = '声波强化传热传质与蒸发冷凝-图片-2.jpg' WHERE sha256 = 'f56a948551e9fce925e0aff59fbbbfcf125592c37327e24a246ac52817206e9f'
AND original_filename <> '声波强化传热传质与蒸发冷凝-图片-2.jpg';

UPDATE media_asset SET original_filename = '多功能各向异性碳气凝胶用于智能电磁波吸收-图片-1.jpg' WHERE sha256 = 'edf775df0b2e571107c69c2da1acc65a82e94522de55ae789b82e45d4f6ff2ab'
AND original_filename <> '多功能各向异性碳气凝胶用于智能电磁波吸收-图片-1.jpg';

UPDATE media_asset SET original_filename = '多功能各向异性碳气凝胶用于智能电磁波吸收-图片-2.jpg' WHERE sha256 = '34ca672ca52a14ba646e3ad96dcf712aa1188a6198fdbbc20e51304d7f06ff18'
AND original_filename <> '多功能各向异性碳气凝胶用于智能电磁波吸收-图片-2.jpg';

UPDATE media_asset SET original_filename = '多功能各向异性碳气凝胶用于智能电磁波吸收-图片-3.jpg' WHERE sha256 = 'a93b03d1bebc140793e0a4ab46c3dbb3acbf1fe04406667643f94ed55ff7f932'
AND original_filename <> '多功能各向异性碳气凝胶用于智能电磁波吸收-图片-3.jpg';

UPDATE media_asset SET original_filename = '多功能各向异性碳气凝胶用于智能电磁波吸收-图片-4.jpg' WHERE sha256 = 'e3c7875dfc0213d88b3a19b4c9cf3be100275fa59e1484bfbf1a77c358cd91a3'
AND original_filename <> '多功能各向异性碳气凝胶用于智能电磁波吸收-图片-4.jpg';

UPDATE media_asset SET original_filename = '多功能各向异性碳气凝胶用于智能电磁波吸收-图片-5.jpg' WHERE sha256 = 'b84b7bbe2e9ef55dffc71776d917d9dab03431e31a5df0b3c69e15de5e17a233'
AND original_filename <> '多功能各向异性碳气凝胶用于智能电磁波吸收-图片-5.jpg';

UPDATE media_asset SET original_filename = '多功能各向异性碳气凝胶用于智能电磁波吸收-图片-6.jpg' WHERE sha256 = '48c39a003074c77571b855480e05afb1cbbb4d0f98b4faecf863484cfe6395c0'
AND original_filename <> '多功能各向异性碳气凝胶用于智能电磁波吸收-图片-6.jpg';

UPDATE media_asset SET original_filename = '多孔液体是什么？它们能做什么？-图片-1.jpg' WHERE sha256 = 'bb969d941cb48b7fc24b169c7830b066cb434bd912592cd50786dc314d31eba1'
AND original_filename <> '多孔液体是什么？它们能做什么？-图片-1.jpg';

UPDATE media_asset SET original_filename = '多孔液体的制备和应用-图片-1.jpg' WHERE sha256 = '7d17dad30e42df6f6370703ff6acf823a957ccd27c212c6992315277b9f8b7f1'
AND original_filename <> '多孔液体的制备和应用-图片-1.jpg';

UPDATE media_asset SET original_filename = '大寒，是我国大部分地区一年中最冷的时候。那它是如何影响2026经济？-图片-1.jpg' WHERE sha256 = '5e5944e5aabbdc1f2d9475ffc754ed4656fefdda602c7f9c018d49f8551196d0'
AND original_filename <> '大寒，是我国大部分地区一年中最冷的时候。那它是如何影响2026经济？-图片-1.jpg';

UPDATE media_asset SET original_filename = '大寒，是我国大部分地区一年中最冷的时候。那它是如何影响2026经济？-图片-2.jpg' WHERE sha256 = '383a664d04f2cda6d250ccfde778a8250aef5a8d6064a4e84804991d82e97094'
AND original_filename <> '大寒，是我国大部分地区一年中最冷的时候。那它是如何影响2026经济？-图片-2.jpg';

UPDATE media_asset SET original_filename = '大寒，是我国大部分地区一年中最冷的时候。那它是如何影响2026经济？-图片-3.jpg' WHERE sha256 = '7f8a7e222122dee385f12108ac9eec8ed2a52fb947b7f57ec5ee7e9bc9707d8f'
AND original_filename <> '大寒，是我国大部分地区一年中最冷的时候。那它是如何影响2026经济？-图片-3.jpg';

UPDATE media_asset SET original_filename = '大寒，是我国大部分地区一年中最冷的时候。那它是如何影响2026经济？-图片-4.jpg' WHERE sha256 = 'abfb05a5f788de10c2f441f17556adc37ea3dc7738b0d2aac4f946476e2dbb49'
AND original_filename <> '大寒，是我国大部分地区一年中最冷的时候。那它是如何影响2026经济？-图片-4.jpg';

UPDATE media_asset SET original_filename = '大寒，是我国大部分地区一年中最冷的时候。那它是如何影响2026经济？-图片-5.jpg' WHERE sha256 = '3a383586cfcc8e8db21d78c44232bee301d56109f3917371e3a1c4320d5db879'
AND original_filename <> '大寒，是我国大部分地区一年中最冷的时候。那它是如何影响2026经济？-图片-5.jpg';

UPDATE media_asset SET original_filename = '大寒，是我国大部分地区一年中最冷的时候。那它是如何影响2026经济？-图片-6.jpg' WHERE sha256 = '4e012ec9ab9255ae369afb465b3145bc9ac1dac41153f3b00dfe5a54c790d4a1'
AND original_filename <> '大寒，是我国大部分地区一年中最冷的时候。那它是如何影响2026经济？-图片-6.jpg';

UPDATE media_asset SET original_filename = '大寒，是我国大部分地区一年中最冷的时候。那它是如何影响2026经济？-图片-7.jpg' WHERE sha256 = '4cf16a59f462fb36c4bebab3fefca3d5352fcd2df369b11523317b925a9040d3'
AND original_filename <> '大寒，是我国大部分地区一年中最冷的时候。那它是如何影响2026经济？-图片-7.jpg';

UPDATE media_asset SET original_filename = '奥飞气凝胶技术节能降碳贡献大，降本增效效果好-图片-1.jpg' WHERE sha256 = '4b6b0233ce8c8823b3cbfec4f2d78b34eb995e8ded5008f3eae1f1b736b7c014'
AND original_filename <> '奥飞气凝胶技术节能降碳贡献大，降本增效效果好-图片-1.jpg';

UPDATE media_asset SET original_filename = '宋淼：靶向狙击的J人导师-图片-1.jpg' WHERE sha256 = '3b38c4392cd04969434eed331994d610d1dce408c1c9d831733516ff5fc13f39'
AND original_filename <> '宋淼：靶向狙击的J人导师-图片-1.jpg';

UPDATE media_asset SET original_filename = '宋淼：靶向狙击的J人导师-图片-2.jpg' WHERE sha256 = 'e2b1637b7012788b80888fcec309a25c92f2c9ac39ea07c43d68cecfadc59dde'
AND original_filename <> '宋淼：靶向狙击的J人导师-图片-2.jpg';

UPDATE media_asset SET original_filename = '宋淼：靶向狙击的J人导师-图片-3.jpg' WHERE sha256 = 'bf696819b108daa06623f18a966892446178cfd0d2d47a54c8987c179122de8e'
AND original_filename <> '宋淼：靶向狙击的J人导师-图片-3.jpg';

UPDATE media_asset SET original_filename = '宋淼：靶向狙击的J人导师-图片-4.jpg' WHERE sha256 = '5489d96b61292163e6c97c94eb0bfa56848d971853eb74b11fee4383eb3e94ac'
AND original_filename <> '宋淼：靶向狙击的J人导师-图片-4.jpg';

UPDATE media_asset SET original_filename = '宋淼：靶向狙击的J人导师-图片-5.jpg' WHERE sha256 = 'c329709d7cd9f8e26cf32ee716fa16737caf77cf269857a5acdd28e3d31e9992'
AND original_filename <> '宋淼：靶向狙击的J人导师-图片-5.jpg';

UPDATE media_asset SET original_filename = '宋淼：靶向狙击的J人导师-图片-6.jpg' WHERE sha256 = 'd249b7258e37d5d6a865a08a9fa95638e99fe2309874dcc211e09b2d375a99e6'
AND original_filename <> '宋淼：靶向狙击的J人导师-图片-6.jpg';

UPDATE media_asset SET original_filename = '宋淼：靶向狙击的J人导师-图片-7.jpg' WHERE sha256 = '769b77decbfe54c4ef0416bc9f5c2c3661c9cb544a39a57142b6745424126e48'
AND original_filename <> '宋淼：靶向狙击的J人导师-图片-7.jpg';

UPDATE media_asset SET original_filename = '宋淼：靶向狙击的J人导师-图片-8.jpg' WHERE sha256 = '0fa34da0c47716fdb5d13c793cbb8e2a521c92e5aadc19b046fee01c24f34075'
AND original_filename <> '宋淼：靶向狙击的J人导师-图片-8.jpg';

UPDATE media_asset SET original_filename = '宋淼：靶向狙击的J人导师-图片-9.jpg' WHERE sha256 = 'c7df782e2eb2ecc26c55f4784a203628d9195b7c3be72de7ab65455a8b30240f'
AND original_filename <> '宋淼：靶向狙击的J人导师-图片-9.jpg';

UPDATE media_asset SET original_filename = '接触角从哪里来？表面张力与界面能的几何平衡-图片-1.jpg' WHERE sha256 = '6339709215be5a1bcd3ab01c27a9b5d737841905a007be40fdbe979a390a81da'
AND original_filename <> '接触角从哪里来？表面张力与界面能的几何平衡-图片-1.jpg';

UPDATE media_asset SET original_filename = '接触角从哪里来？表面张力与界面能的几何平衡-图片-2.jpg' WHERE sha256 = 'f2a1b0452bb181c73f3356f31bebc3fa7c8ecf0b978afd1bb6cc792367e43f7a'
AND original_filename <> '接触角从哪里来？表面张力与界面能的几何平衡-图片-2.jpg';

UPDATE media_asset SET original_filename = '推动气凝胶产业落地，共建新材料发展高地——奥飞新材携手望城经开区与中南大学共商合作新篇章-图片-1.jpg' WHERE sha256 = '561195bdddf55d63f67f35ef52ff07f487aa46d2672075e46398297710b3c0d0'
AND original_filename <> '推动气凝胶产业落地，共建新材料发展高地——奥飞新材携手望城经开区与中南大学共商合作新篇章-图片-1.jpg';

UPDATE media_asset SET original_filename = '最新动力电池安全标准发布，要求2小时内不起火、不爆炸-图片-1.jpg' WHERE sha256 = 'e472b24c3b5d03263bcb5a270b6e7a8d9bf5766410e1e9b403fb0a1debb4cb05'
AND original_filename <> '最新动力电池安全标准发布，要求2小时内不起火、不爆炸-图片-1.jpg';

UPDATE media_asset SET original_filename = '望城与中南大学粉末冶金全国重点实验室、立邦中国签订合作协议 共同推动相关项目建设-图片-1.jpg' WHERE sha256 = 'efc80ffd0f0da39044655158c2de4238305abb2262eea0e5513941d015e5b4ae'
AND original_filename <> '望城与中南大学粉末冶金全国重点实验室、立邦中国签订合作协议 共同推动相关项目建设-图片-1.jpg';

UPDATE media_asset SET original_filename = '极端环境下的多孔液体：挑战与潜力-图片-1.jpg' WHERE sha256 = '30edfc51773ca59a6874178e3af3717ba4d8db00cabc79d14823d9c648ff98f0'
AND original_filename <> '极端环境下的多孔液体：挑战与潜力-图片-1.jpg';

UPDATE media_asset SET original_filename = '毛细现象是怎么产生的？从液柱上升到毛细驱动器-图片-1.jpg' WHERE sha256 = '00e798e4ac8fc8495adf3cee47a97f019644d489c1eebdd29f6235fce081c17d'
AND original_filename <> '毛细现象是怎么产生的？从液柱上升到毛细驱动器-图片-1.jpg';

UPDATE media_asset SET original_filename = '气凝胶与水凝胶如何“应对湿气”-图片-1.jpg' WHERE sha256 = '81e5e66804ba725ab4521831e2b142baa9cff8995f53933a36e673065e2a4e99'
AND original_filename <> '气凝胶与水凝胶如何“应对湿气”-图片-1.jpg';

UPDATE media_asset SET original_filename = '气凝胶与水凝胶如何“应对湿气”-图片-2.jpg' WHERE sha256 = '9e211700ee87d2c25637f0c25e949652c76420bb8a9d22abeaf3ba03ed25447a'
AND original_filename <> '气凝胶与水凝胶如何“应对湿气”-图片-2.jpg';

UPDATE media_asset SET original_filename = '气凝胶为什么是-绝热之王-？从微孔结构看热量如何被-卡住-图片-1.jpg' WHERE sha256 = 'c2ce8508cd946518ed9a326b07b585180bf3b1d7b02ee1ea2343269184f408c1'
AND original_filename <> '气凝胶为什么是-绝热之王-？从微孔结构看热量如何被-卡住-图片-1.jpg';

UPDATE media_asset SET original_filename = '气凝胶为什么是-绝热之王-？从微孔结构看热量如何被-卡住-图片-2.jpg' WHERE sha256 = 'c499b6100730b856894d9f1e93dfa647792d071a94902a035a8712a7c8e10569'
AND original_filename <> '气凝胶为什么是-绝热之王-？从微孔结构看热量如何被-卡住-图片-2.jpg';

UPDATE media_asset SET original_filename = '气凝胶为什么这么“绝热”？从多孔结构看热流如何被限制-图片-1.jpg' WHERE sha256 = '1e56c6d01ac9a285d705dc433d9ee3395fef226247ead3ed39063928466e4fb8'
AND original_filename <> '气凝胶为什么这么“绝热”？从多孔结构看热流如何被限制-图片-1.jpg';

UPDATE media_asset SET original_filename = '气凝胶为什么这么“绝热”？从多孔结构看热流如何被限制-图片-2.jpg' WHERE sha256 = '9990fb64d461fd9caada9b0e9bf12b13b6ab142f96a44d19feaa3c43888a3f22'
AND original_filename <> '气凝胶为什么这么“绝热”？从多孔结构看热流如何被限制-图片-2.jpg';

UPDATE media_asset SET original_filename = '气凝胶保温材料：建筑节能领域的“隐形战神”-图片-1.jpg' WHERE sha256 = '46652e8009a0c72c1bf3d845a367ccf26489cc4c5ac630922b77c3179138d0d9'
AND original_filename <> '气凝胶保温材料：建筑节能领域的“隐形战神”-图片-1.jpg';

UPDATE media_asset SET original_filename = '气凝胶在潮湿环境下的热质性能演变-图片-1.jpg' WHERE sha256 = '57f2998ddf7ff76ed310b92d9b247a12d0604e682209a536a665a1f6c1d5949f'
AND original_filename <> '气凝胶在潮湿环境下的热质性能演变-图片-1.jpg';

UPDATE media_asset SET original_filename = '气凝胶在潮湿环境下的热质性能演变-图片-2.jpg' WHERE sha256 = '6d769527df20283aa4723dadba1eb58c2f8b90acf84c4b70df0c99f786d6a375'
AND original_filename <> '气凝胶在潮湿环境下的热质性能演变-图片-2.jpg';

UPDATE media_asset SET original_filename = '气凝胶在纳米通道里的传质行为解析-图片-1.jpg' WHERE sha256 = 'fbc33a9e58a1fae94c815243735ea2bcd25e2ef9d9e68b54d3cd364314ba649c'
AND original_filename <> '气凝胶在纳米通道里的传质行为解析-图片-1.jpg';

UPDATE media_asset SET original_filename = '气凝胶在纳米通道里的传质行为解析-图片-2.jpg' WHERE sha256 = 'cbca691d8524631ea09afa0efe2a3ffcaf9f353b84b1688c374b181387b232fa'
AND original_filename <> '气凝胶在纳米通道里的传质行为解析-图片-2.jpg';

UPDATE media_asset SET original_filename = '气凝胶复合材料在建筑领域的应用-图片-1.jpg' WHERE sha256 = '7768ae131d30a8e92049b8a9774c182ea30f519f42974af4bf9b17c4361c7b81'
AND original_filename <> '气凝胶复合材料在建筑领域的应用-图片-1.jpg';

UPDATE media_asset SET original_filename = '气相二氧化硅在涂料中的应用及相关标准简介-图片-1.jpg' WHERE sha256 = '63d4c0133d58598b61b0d998d4d2e5123e7ce6176c8b5097dbc7e520a17db36f'
AND original_filename <> '气相二氧化硅在涂料中的应用及相关标准简介-图片-1.jpg';

UPDATE media_asset SET original_filename = '气相二氧化硅在涂料中的应用及相关标准简介-图片-2.jpg' WHERE sha256 = 'a205612def04220f2cc40289eb8e471ec24b55aecd7204e213e8d3028db36911'
AND original_filename <> '气相二氧化硅在涂料中的应用及相关标准简介-图片-2.jpg';

UPDATE media_asset SET original_filename = '水凝胶与气凝胶是怎样制作的？-图片-1.jpg' WHERE sha256 = 'c74c98f7d509da283637f7ec76d1a308551484029ad1a1e14eb8281c5dbf235f'
AND original_filename <> '水凝胶与气凝胶是怎样制作的？-图片-1.jpg';

UPDATE media_asset SET original_filename = '水凝胶与气凝胶是怎样制作的？-图片-2.jpg' WHERE sha256 = '1e96cf59ce431d2bfde2692756a849598187fe7a98f89ba1b806999d0022db37'
AND original_filename <> '水凝胶与气凝胶是怎样制作的？-图片-2.jpg';

UPDATE media_asset SET original_filename = '水凝胶与气凝胶的区别-图片-1.jpg' WHERE sha256 = 'ba081a06dc8ae1ac5efb440619a7752a86d0342eb3dec5d976e2c5f263a730d1'
AND original_filename <> '水凝胶与气凝胶的区别-图片-1.jpg';

UPDATE media_asset SET original_filename = '水凝胶与气凝胶的区别-图片-2.jpg' WHERE sha256 = 'f83c581c2941b65f70b624eb613509f68c9faf79ed14e5894c5ab39454f5d649'
AND original_filename <> '水凝胶与气凝胶的区别-图片-2.jpg';

UPDATE media_asset SET original_filename = '水凝胶中的温度驱动传质现象-图片-1.jpg' WHERE sha256 = 'c7f3e94682d34726b3543563a28beffe17c0a139b3d85ef0e16b569aad14b3e1'
AND original_filename <> '水凝胶中的温度驱动传质现象-图片-1.jpg';

UPDATE media_asset SET original_filename = '水凝胶中的温度驱动传质现象-图片-2.jpg' WHERE sha256 = '4002e4bec88c9885e47f9aa63e701a6309a1ff9a6a672f3f843fd0101dd714f7'
AND original_filename <> '水凝胶中的温度驱动传质现象-图片-2.jpg';

UPDATE media_asset SET original_filename = '水凝胶电解质传导微观机制-图片-1.jpg' WHERE sha256 = '4510b41ccfc2f52094209f1220d258ffb105d965e17aee95bbc2df371b95b2a5'
AND original_filename <> '水凝胶电解质传导微观机制-图片-1.jpg';

UPDATE media_asset SET original_filename = '水凝胶电解质传导微观机制-图片-2.jpg' WHERE sha256 = 'a568840f654a247ae5fdbfb6b8de7ed6d6950f7286e290f68d1ad352836409c2'
AND original_filename <> '水凝胶电解质传导微观机制-图片-2.jpg';

UPDATE media_asset SET original_filename = '水凝胶电解质传导微观机制-图片-3.jpg' WHERE sha256 = '9ec35e46c27db799e43a08bd2a3c4353d51a0c037f8bdbbc63684f7fefbb0cc0'
AND original_filename <> '水凝胶电解质传导微观机制-图片-3.jpg';

UPDATE media_asset SET original_filename = '水凝胶电解质传导微观机制-图片-4.jpg' WHERE sha256 = 'e58ddc2d8362ab4ad1f925102971c34ca1df75c75a4c6823ca625d31def445f8'
AND original_filename <> '水凝胶电解质传导微观机制-图片-4.jpg';

UPDATE media_asset SET original_filename = '水凝胶电解质传导微观机制-图片-5.jpg' WHERE sha256 = 'd3a6d0c18f6887f771aa3cd51db375e7a9588e1af63801cc100cd9bcc5bccaac'
AND original_filename <> '水凝胶电解质传导微观机制-图片-5.jpg';

UPDATE media_asset SET original_filename = '水凝胶电解质传导微观机制-图片-6.jpg' WHERE sha256 = '98bf884f79a76a7028d252e63c5b93fea4b0d17ad276eaf0f2c8904cbd7f8189'
AND original_filename <> '水凝胶电解质传导微观机制-图片-6.jpg';

UPDATE media_asset SET original_filename = '浅析热反射涂料的机理、组成与发展方向-图片-1.jpg' WHERE sha256 = '277fded4030dbb69659d784418ef078f6c8045195dd136a51a1a7543be576c39'
AND original_filename <> '浅析热反射涂料的机理、组成与发展方向-图片-1.jpg';

UPDATE media_asset SET original_filename = '浅析热反射涂料的机理、组成与发展方向-图片-2.jpg' WHERE sha256 = 'ca9b0f28bc3efda8c4c0b2674389266af4d18561cd7660c048c941b20aeadbd7'
AND original_filename <> '浅析热反射涂料的机理、组成与发展方向-图片-2.jpg';

UPDATE media_asset SET original_filename = '浅析热反射涂料的机理、组成与发展方向-图片-3.jpg' WHERE sha256 = 'a49f167263951f5aae962ddcc400f73350e6ae8bdde8eb75e4047c9b9c7128c5'
AND original_filename <> '浅析热反射涂料的机理、组成与发展方向-图片-3.jpg';

UPDATE media_asset SET original_filename = '浅析热反射涂料的机理、组成与发展方向-图片-4.jpg' WHERE sha256 = '98218f054e0f6bea9ada378e638c668fefc8fb5bbeec7c9a1de572baa8405c50'
AND original_filename <> '浅析热反射涂料的机理、组成与发展方向-图片-4.jpg';

UPDATE media_asset SET original_filename = '浅析热反射涂料的机理、组成与发展方向-图片-5.jpg' WHERE sha256 = '6a0306f14f2da85a8fb4b02d38016d34d79e504cfcb2de83f2293cf60faaffb5'
AND original_filename <> '浅析热反射涂料的机理、组成与发展方向-图片-5.jpg';

UPDATE media_asset SET original_filename = '涂料拉开法附着力检测标准简介-图片-1.jpg' WHERE sha256 = '63e99c17b711978e9db3eb920cfeaca8a21d663cad8344a237f5a192b5b2dd06'
AND original_filename <> '涂料拉开法附着力检测标准简介-图片-1.jpg';

UPDATE media_asset SET original_filename = '涂料拉开法附着力检测标准简介-图片-2.jpg' WHERE sha256 = '3a8c4b08755d83476e69afbccc9c593a86cda36baca18264f05d4bed84bfb177'
AND original_filename <> '涂料拉开法附着力检测标准简介-图片-2.jpg';

UPDATE media_asset SET original_filename = '涂料玻璃化转变温度及其标准简介-图片-1.jpg' WHERE sha256 = '89f00be3e14f084f8d355786968286ed400d41f7c6b5f617f1bcef9efc1c2c2b'
AND original_filename <> '涂料玻璃化转变温度及其标准简介-图片-1.jpg';

UPDATE media_asset SET original_filename = '涂料玻璃化转变温度及其标准简介-图片-2.jpg' WHERE sha256 = '04bea55cb7f14f2b080140e8f677534baf9193a3d38331445de816de2ab2f04e'
AND original_filename <> '涂料玻璃化转变温度及其标准简介-图片-2.jpg';

UPDATE media_asset SET original_filename = '涂料玻璃化转变温度及其标准简介-图片-3.jpg' WHERE sha256 = '59b14900dfd574736e775ff70ed47e3ba1c04808e6f978dbd8380f905d6b99b9'
AND original_filename <> '涂料玻璃化转变温度及其标准简介-图片-3.jpg';

UPDATE media_asset SET original_filename = '涂料结皮性及标准简介-图片-1.jpg' WHERE sha256 = 'e05ed72cf8ec1b8223e259fe77cf218dc4c59072f37e700f49376e536aa0db4b'
AND original_filename <> '涂料结皮性及标准简介-图片-1.jpg';

UPDATE media_asset SET original_filename = '涂料结皮性及标准简介-图片-2.jpg' WHERE sha256 = '4280007539ccfd22758ef57c3c34c4acde14e1948fb79990b352981762cb8c49'
AND original_filename <> '涂料结皮性及标准简介-图片-2.jpg';

UPDATE media_asset SET original_filename = '液滴为什么成球？——从表面张力到最小表面积原理-图片-1.jpg' WHERE sha256 = 'b7495d358f1180a0378ca594776e36addfe17880d97e5fa1cea471eaa7099c0d'
AND original_filename <> '液滴为什么成球？——从表面张力到最小表面积原理-图片-1.jpg';

UPDATE media_asset SET original_filename = '液滴为什么成球？——从表面张力到最小表面积原理-图片-2.jpg' WHERE sha256 = '7a0cea632f2316f6dfa56ac75046d4109f3fc5845b664493855c0e4428154884'
AND original_filename <> '液滴为什么成球？——从表面张力到最小表面积原理-图片-2.jpg';

UPDATE media_asset SET original_filename = '湖北“老改好”引领旧房改造 —— 科技创新助力绿色改造-图片-1.jpg' WHERE sha256 = '7ea371bc8e6be007f373ca00a8da411e98d47e391ddfc272bb2fd29ea4f30bbe'
AND original_filename <> '湖北“老改好”引领旧房改造 —— 科技创新助力绿色改造-图片-1.jpg';

UPDATE media_asset SET original_filename = '湖北“老改好”引领旧房改造 —— 科技创新助力绿色改造-图片-2.jpg' WHERE sha256 = '499383b217427b3e0c79d8e69526fd4332481467e44c2f36f4eee0c3e82d5e0b'
AND original_filename <> '湖北“老改好”引领旧房改造 —— 科技创新助力绿色改造-图片-2.jpg';

UPDATE media_asset SET original_filename = '热界面材料市场规模 - 按材料类型、热导率、应用，未来10年预测-图片-1.jpg' WHERE sha256 = '713aa9160283096b30b85bfa869de44c855fd93e8c4a5cc7b856058fd94a55aa'
AND original_filename <> '热界面材料市场规模 - 按材料类型、热导率、应用，未来10年预测-图片-1.jpg';

UPDATE media_asset SET original_filename = '热界面材料市场规模 - 按材料类型、热导率、应用，未来10年预测-图片-2.jpg' WHERE sha256 = '7b35cfefbc475ff17a94c0ea83e3cc9a6ffc397aa32ea2fe43fadc9a4fe29ce0'
AND original_filename <> '热界面材料市场规模 - 按材料类型、热导率、应用，未来10年预测-图片-2.jpg';

UPDATE media_asset SET original_filename = '热界面材料市场规模 - 按材料类型、热导率、应用，未来10年预测-图片-3.jpg' WHERE sha256 = '19d37bcfbada349f738d0c38993f83683c5bf7326a94df13a1b7cf7a644c7fd6'
AND original_filename <> '热界面材料市场规模 - 按材料类型、热导率、应用，未来10年预测-图片-3.jpg';

UPDATE media_asset SET original_filename = '特大地磁暴发生！-图片-1.jpg' WHERE sha256 = '194723f75d0b5f869c0519b3bdbfc51ed54fd9188cb7ee117bbd91e208c90d54'
AND original_filename <> '特大地磁暴发生！-图片-1.jpg';

UPDATE media_asset SET original_filename = '特大地磁暴发生！-图片-2.jpg' WHERE sha256 = '6c53afad043cb04553ec67e616042502081ec5647a5bc1dd361d36cbf44aa3bd'
AND original_filename <> '特大地磁暴发生！-图片-2.jpg';

UPDATE media_asset SET original_filename = '特大地磁暴发生！-图片-3.jpg' WHERE sha256 = 'e6d787827c105d4b701cebc27d8cea662241f76bdc20e847c5b61e120cabb143'
AND original_filename <> '特大地磁暴发生！-图片-3.jpg';

UPDATE media_asset SET original_filename = '特大地磁暴发生！-图片-4.jpg' WHERE sha256 = '365602d08dbd2c6cae6f1bd1b6d04d82f45983c582625ffc043a0a285282cca6'
AND original_filename <> '特大地磁暴发生！-图片-4.jpg';

UPDATE media_asset SET original_filename = '科研显微镜全景对比：光学、电子到原子级别-图片-1.jpg' WHERE sha256 = 'edda64e2571ef6b9f47dd49f3e15e3230e6e8e7ac1e590a1ad26650dcce0b4fb'
AND original_filename <> '科研显微镜全景对比：光学、电子到原子级别-图片-1.jpg';

UPDATE media_asset SET original_filename = '第六届中国新材料产业发展大会粉末冶金先进材料与制造技术分会成功举办-图片-1.jpg' WHERE sha256 = '21fbc8c181391bc92805ca39a8ebc130bb19e7daec9a6a3bba31ba88fe79fea1'
AND original_filename <> '第六届中国新材料产业发展大会粉末冶金先进材料与制造技术分会成功举办-图片-1.jpg';

UPDATE media_asset SET original_filename = '第六届中国新材料产业发展大会粉末冶金先进材料与制造技术分会成功举办-图片-2.jpg' WHERE sha256 = 'bfd40cbaf23118a85c82f6a61f9142f6451b9ddd86d378c837ef202972d9f2dc'
AND original_filename <> '第六届中国新材料产业发展大会粉末冶金先进材料与制造技术分会成功举办-图片-2.jpg';

UPDATE media_asset SET original_filename = '第六届中国新材料产业发展大会粉末冶金先进材料与制造技术分会成功举办-图片-3.jpg' WHERE sha256 = 'b221e6d4f762eaf71188f8db4ddb4ecaab33f08da0a4bb0d027339c853f3c5f4'
AND original_filename <> '第六届中国新材料产业发展大会粉末冶金先进材料与制造技术分会成功举办-图片-3.jpg';

UPDATE media_asset SET original_filename = '第六届中国新材料产业发展大会粉末冶金先进材料与制造技术分会成功举办-图片-4.jpg' WHERE sha256 = '7dd2b4e64e599e8d05f6d9866488d721643098e9f4640546294218bf276adac6'
AND original_filename <> '第六届中国新材料产业发展大会粉末冶金先进材料与制造技术分会成功举办-图片-4.jpg';

UPDATE media_asset SET original_filename = '红外光谱和拉曼光谱的区别-图片-1.jpg' WHERE sha256 = 'bc58ebd3bb84bdf36c8cf64f28f83d59b9781d12322486894d8e296e2e4884a3'
AND original_filename <> '红外光谱和拉曼光谱的区别-图片-1.jpg';

UPDATE media_asset SET original_filename = '耐高温隔热氧化物气凝胶研究进展-图片-1.jpg' WHERE sha256 = 'ecce2148f56c80e6bacfd48e9987eb6ae37b9a3b73ef801656af0d2d53fd6d7e'
AND original_filename <> '耐高温隔热氧化物气凝胶研究进展-图片-1.jpg';

UPDATE media_asset SET original_filename = '耐高温隔热氧化物气凝胶研究进展-图片-2.jpg' WHERE sha256 = '2537868b5ed84b26b4abcd541664c26bdd7c5a12807b59bc16cd67ef4be4206c'
AND original_filename <> '耐高温隔热氧化物气凝胶研究进展-图片-2.jpg';

UPDATE media_asset SET original_filename = '耐高温隔热氧化物气凝胶研究进展-图片-3.jpg' WHERE sha256 = 'c41abb8a5bc366623622c8066a5730c0bda187a48c4afb63064db71db76da5be'
AND original_filename <> '耐高温隔热氧化物气凝胶研究进展-图片-3.jpg';

UPDATE media_asset SET original_filename = '耐高温隔热氧化物气凝胶研究进展-图片-4.jpg' WHERE sha256 = 'acf4beb14a7981ecd93877dcf220e1d9beb5b615260e3b46c0e94a96f18a75f5'
AND original_filename <> '耐高温隔热氧化物气凝胶研究进展-图片-4.jpg';

UPDATE media_asset SET original_filename = '耐高温隔热氧化物气凝胶研究进展-图片-5.jpg' WHERE sha256 = 'ccbb2baf7ad809024bc7a98aaa8e8ba3318cd383adf19e0ba403aa20bb8d9a96'
AND original_filename <> '耐高温隔热氧化物气凝胶研究进展-图片-5.jpg';

UPDATE media_asset SET original_filename = '耐高温隔热氧化物气凝胶研究进展-图片-6.jpg' WHERE sha256 = '1131b01c8bea8a680eaa6239d0c2fd6db4cbbac1f68e4bc0ed860e7a75a11087'
AND original_filename <> '耐高温隔热氧化物气凝胶研究进展-图片-6.jpg';

UPDATE media_asset SET original_filename = '耐高温隔热氧化物气凝胶研究进展-图片-7.jpg' WHERE sha256 = '974fce087010d1ca96c9021b020aa6c1bb2376b13006987798dd9ab9c3cbd4ff'
AND original_filename <> '耐高温隔热氧化物气凝胶研究进展-图片-7.jpg';

UPDATE media_asset SET original_filename = '耐高温隔热氧化物气凝胶研究进展-图片-8.jpg' WHERE sha256 = '2d96d97a28052655dccfa1308ddbbe4452d754da97ba79a62bf6336f3c92fc4b'
AND original_filename <> '耐高温隔热氧化物气凝胶研究进展-图片-8.jpg';

UPDATE media_asset SET original_filename = '耐高温隔热氧化物气凝胶研究进展-图片-9.jpg' WHERE sha256 = 'ee4cdf4ae46fd8b7da6546c33d8bedc6c4b0f94b8ebdbda1511c7552ec58c650'
AND original_filename <> '耐高温隔热氧化物气凝胶研究进展-图片-9.jpg';

UPDATE media_asset SET original_filename = '耐高温隔热氧化物气凝胶研究进展-图片-10.jpg' WHERE sha256 = '57766e14f96cf09e7dce178c1d0547219d4bba8d85031b50aa6350993f51481f'
AND original_filename <> '耐高温隔热氧化物气凝胶研究进展-图片-10.jpg';

UPDATE media_asset SET original_filename = '耐高温隔热氧化物气凝胶研究进展-图片-11.jpg' WHERE sha256 = 'd233e41f97c222e8f62a8dc17bd0c64d1a02f1d60f96c808ad7d2bbabd1ece8d'
AND original_filename <> '耐高温隔热氧化物气凝胶研究进展-图片-11.jpg';

UPDATE media_asset SET original_filename = '耐高温隔热氧化物气凝胶研究进展-图片-12.jpg' WHERE sha256 = 'a6cdcc347ac2d85a2ed06e6d02ff8d5bd14144811906f2c2fa7b691ed2f70a28'
AND original_filename <> '耐高温隔热氧化物气凝胶研究进展-图片-12.jpg';

UPDATE media_asset SET original_filename = '表面张力与界面张力的区别：从微观机制到宏观现象-图片-1.jpg' WHERE sha256 = 'b17046a6024f4f42920b21eb9b29b92019c1125e715235141d267f57f5cf36d3'
AND original_filename <> '表面张力与界面张力的区别：从微观机制到宏观现象-图片-1.jpg';

UPDATE media_asset SET original_filename = '表面张力与界面张力的区别：从微观机制到宏观现象-图片-2.jpg' WHERE sha256 = 'd80acc73cdf4ae7f4bdae9a31c5ceb9d76af9ee874fee3b7749d9eb0257a83f4'
AND original_filename <> '表面张力与界面张力的区别：从微观机制到宏观现象-图片-2.jpg';

UPDATE media_asset SET original_filename = '表面张力大或小，有什么影响？-图片-1.jpg' WHERE sha256 = '876839ac515c581fc8f37e3c0f4611054931c88b69e4786b034eaa6a9ad3dcdd'
AND original_filename <> '表面张力大或小，有什么影响？-图片-1.jpg';

UPDATE media_asset SET original_filename = '表面张力大或小，有什么影响？-图片-2.jpg' WHERE sha256 = '287b75062c9e078fb43b1634b69ff2d08fba58c12e722171d91769056ba7ffc7'
AND original_filename <> '表面张力大或小，有什么影响？-图片-2.jpg';

UPDATE media_asset SET original_filename = '表面活性剂是怎么工作的？-图片-1.jpg' WHERE sha256 = 'b471a736db91911199aaab9623d7660034ac5e0239ba25f06b7c55bbc3f3814d'
AND original_filename <> '表面活性剂是怎么工作的？-图片-1.jpg';

UPDATE media_asset SET original_filename = '让飞机不再结冰：基于微界面能调控的智能抗冰涂层解决方案-图片-1.jpg' WHERE sha256 = '2a4fcaebc582ebf936c9f629b7cca9d0bcd2fa0e5b21f31c856cb48653916b69'
AND original_filename <> '让飞机不再结冰：基于微界面能调控的智能抗冰涂层解决方案-图片-1.jpg';

UPDATE media_asset SET original_filename = '阻燃剂标准及其在涂料中的应用简介-图片-1.jpg' WHERE sha256 = 'e3198357344bfc4e77fd254b1904d1822fe8895fcfc54181a1bfa677fa247ffd'
AND original_filename <> '阻燃剂标准及其在涂料中的应用简介-图片-1.jpg';

UPDATE media_asset SET original_filename = '阻燃剂标准及其在涂料中的应用简介-图片-2.jpg' WHERE sha256 = '17b5348e73c7258b73f08a70ea69224574672078a2057e0f1bdc04ba99dc389e'
AND original_filename <> '阻燃剂标准及其在涂料中的应用简介-图片-2.jpg';

UPDATE media_asset SET original_filename = '阻燃剂标准及其在涂料中的应用简介-图片-3.jpg' WHERE sha256 = 'e50e20cf082da2c1589eaa430c74b3cb14fd6d5c4c11fd4bdba5827f4734e0d6'
AND original_filename <> '阻燃剂标准及其在涂料中的应用简介-图片-3.jpg';

UPDATE media_asset SET original_filename = '阻燃剂标准及其在涂料中的应用简介-图片-4.jpg' WHERE sha256 = 'ee0ca27945cde07551899a088436579e212a95cc40b7b93493f8856b16e17141'
AND original_filename <> '阻燃剂标准及其在涂料中的应用简介-图片-4.jpg';

UPDATE media_asset SET original_filename = '阻燃剂标准及其在涂料中的应用简介-图片-5.jpg' WHERE sha256 = '01d6f3359d256b5f0cbe0771dc59ef5dadc5d9066592102094359cbee43bf4d4'
AND original_filename <> '阻燃剂标准及其在涂料中的应用简介-图片-5.jpg';

UPDATE media_asset SET original_filename = '高强度高韧性的透明芳纶纳米纤维气凝胶薄膜用于被动加热节能窗户-图片-1.jpg' WHERE sha256 = '30d56d79b014ddd3a43d6995ffc77235e0e1801ad9bd0aa1071eb8f1d57292cd'
AND original_filename <> '高强度高韧性的透明芳纶纳米纤维气凝胶薄膜用于被动加热节能窗户-图片-1.jpg';

UPDATE media_asset SET original_filename = '高强度高韧性的透明芳纶纳米纤维气凝胶薄膜用于被动加热节能窗户-图片-2.jpg' WHERE sha256 = 'a0d5cb6b5ae9deed21b40a8c668c2443d5adbfa1614501f20f23229d418344b3'
AND original_filename <> '高强度高韧性的透明芳纶纳米纤维气凝胶薄膜用于被动加热节能窗户-图片-2.jpg';

UPDATE media_asset SET original_filename = '高强度高韧性的透明芳纶纳米纤维气凝胶薄膜用于被动加热节能窗户-图片-3.jpg' WHERE sha256 = '09bf283bcf1090c00d369b7e14ebb4cc28377f1dad1601d1dd5cca1c7061bd37'
AND original_filename <> '高强度高韧性的透明芳纶纳米纤维气凝胶薄膜用于被动加热节能窗户-图片-3.jpg';

UPDATE media_asset SET original_filename = '高强度高韧性的透明芳纶纳米纤维气凝胶薄膜用于被动加热节能窗户-图片-4.jpg' WHERE sha256 = 'a2cfd0de987a93565f977dbdedde249ca5b2543ba7ff6c889f9a1572a35ffc3f'
AND original_filename <> '高强度高韧性的透明芳纶纳米纤维气凝胶薄膜用于被动加热节能窗户-图片-4.jpg';

UPDATE media_asset SET original_filename = '高强度高韧性的透明芳纶纳米纤维气凝胶薄膜用于被动加热节能窗户-图片-5.jpg' WHERE sha256 = '7a42933d45f3bda83b498d4ce8ec5ab49b7619f30753219605f2a5737d7bb1ea'
AND original_filename <> '高强度高韧性的透明芳纶纳米纤维气凝胶薄膜用于被动加热节能窗户-图片-5.jpg';

UPDATE media_asset SET original_filename = '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-1.webp' WHERE sha256 = '88c948b04cd56882316b51ad18b00bb36108c7e4b446dd2f0e0fb15d2ed137ff'
AND original_filename <> '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-1.webp';

UPDATE media_asset SET original_filename = '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-2.webp' WHERE sha256 = '03e63e2b7a01b2ccc5e8a5ac6063e3bda7deca2cf44092e2e56084f6c2829dcc'
AND original_filename <> '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-2.webp';

UPDATE media_asset SET original_filename = '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-3.webp' WHERE sha256 = '8a4507b8f609b4100a1ae6fe11ce76ccc1c1f4814e8538252ae3ea2d7e33251f'
AND original_filename <> '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-3.webp';

UPDATE media_asset SET original_filename = '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-4.webp' WHERE sha256 = 'd2fc139dc0fe81f01b98e92a108b5ee3b4025ac131cd28e05a30432c80d5fbbd'
AND original_filename <> '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-4.webp';

UPDATE media_asset SET original_filename = '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-5.webp' WHERE sha256 = 'a2dec51fc17e11a9bc5a49be7a2cd278ee193b8a2fe0a28d3ac419d6a54c6d67'
AND original_filename <> '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-5.webp';

UPDATE media_asset SET original_filename = '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-6.webp' WHERE sha256 = '4058fbbc907d2d4468c1ad12b8dacebcb615538beef11579e28941067de911a1'
AND original_filename <> '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-6.webp';

UPDATE media_asset SET original_filename = '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-7.webp' WHERE sha256 = '736abbf22a9c9bce392a08c72602cd39b30fa28d42651a06fccd7e99288bb526'
AND original_filename <> '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-7.webp';

UPDATE media_asset SET original_filename = '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-8.webp' WHERE sha256 = '0928dbb1dcf0c0281bdae6a641aabfcc964a3ac5c9c88f2e79545435a33b43c2'
AND original_filename <> '奥飞新材透明气凝胶涂料在长沙湘江壹号项目案例-图片-8.webp';

UPDATE media_asset SET original_filename = '安徽某贡酒厂白酒提纯冷却管道防结露解决方案-图片-1.webp' WHERE sha256 = '2ed425714054202183fe8a886832ddb3d85e19b70d3d81da6a2867e50a4d5c6a'
AND original_filename <> '安徽某贡酒厂白酒提纯冷却管道防结露解决方案-图片-1.webp';

UPDATE media_asset SET original_filename = '安徽某贡酒厂白酒提纯冷却管道防结露解决方案-图片-2.webp' WHERE sha256 = '948276c6ec6dcf3e303bcbe9f2ac56ed564c766ae642e6b0dcf8d8bca1c47162'
AND original_filename <> '安徽某贡酒厂白酒提纯冷却管道防结露解决方案-图片-2.webp';

UPDATE media_asset SET original_filename = '安徽某贡酒厂白酒提纯冷却管道防结露解决方案-图片-3.webp' WHERE sha256 = '49a87123837a3a96b48d6b40b9bab94de4a11fd36ee28c516da05ea9fdc63d33'
AND original_filename <> '安徽某贡酒厂白酒提纯冷却管道防结露解决方案-图片-3.webp';

UPDATE media_asset SET original_filename = '安徽淮南国家电投湖面光伏变电房隔热改造项目-图片-1.webp' WHERE sha256 = '234ecf58935ab492ff69db43b354d99810ea1a44095046d2faef0ba6bacffcc3'
AND original_filename <> '安徽淮南国家电投湖面光伏变电房隔热改造项目-图片-1.webp';

UPDATE media_asset SET original_filename = '安徽淮南国家电投湖面光伏变电房隔热改造项目-图片-2.webp' WHERE sha256 = '4cd0dde96b80233e4e1b5ed8bc3fb0907e2eeb4005036b7ed3b99c35478cd5b3'
AND original_filename <> '安徽淮南国家电投湖面光伏变电房隔热改造项目-图片-2.webp';

UPDATE media_asset SET original_filename = '明和产业园新建建筑气凝胶外墙保温案例-图片-1.webp' WHERE sha256 = 'e0ae6b5823e81eeca65cf18f025ce9dfb92c806c594d40f2f3019df46561bc99'
AND original_filename <> '明和产业园新建建筑气凝胶外墙保温案例-图片-1.webp';

UPDATE media_asset SET original_filename = '某大坝碾压混凝土保温抗渗系统应用案例-图片-1.webp' WHERE sha256 = '1d051645aed356308a474f016215c245901e18de5d0d283f9c8e4fe829280c4f'
AND original_filename <> '某大坝碾压混凝土保温抗渗系统应用案例-图片-1.webp';

UPDATE media_asset SET original_filename = '某钢铁水罐车表面防腐及气凝胶节能防烫案例-图片-1.webp' WHERE sha256 = 'd4717899d12619bc1a9cf933fd597a21efa1bc7b803a11233fef7c9d2a4e79a5'
AND original_filename <> '某钢铁水罐车表面防腐及气凝胶节能防烫案例-图片-1.webp';

UPDATE media_asset SET original_filename = '某钢铁水罐车表面防腐及气凝胶节能防烫案例-图片-2.webp' WHERE sha256 = '1432a2c42eb0aa62cdd6ba2c417f41c549ec04f087aa6222aa0470b1ff0a058e'
AND original_filename <> '某钢铁水罐车表面防腐及气凝胶节能防烫案例-图片-2.webp';

UPDATE media_asset SET original_filename = '某陶瓷企业双孔窑炉节能改造案例-图片-1.webp' WHERE sha256 = 'd1dd14d740d027046e8acab4fdd588aefcb425ff9ae582890ea61aa8dab0fd00'
AND original_filename <> '某陶瓷企业双孔窑炉节能改造案例-图片-1.webp';

UPDATE media_asset SET original_filename = '某陶瓷企业双孔窑炉节能改造案例-图片-2.webp' WHERE sha256 = '954700af40b6515a3c19bbca4140587c8269fce8a2ac5197877964c1deb6218c'
AND original_filename <> '某陶瓷企业双孔窑炉节能改造案例-图片-2.webp';

UPDATE media_asset SET original_filename = '某陶瓷企业双孔窑炉节能改造案例-图片-3.webp' WHERE sha256 = 'c689633ceebf649dfaf4eea0c293228441ffe2e3ffb971cb623c0b88bc8ac7b1'
AND original_filename <> '某陶瓷企业双孔窑炉节能改造案例-图片-3.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-1.webp' WHERE sha256 = '71e9698a300a56e3e97c5e6b6ce5af97816b2f5becd4d66b1bc954c1fb9c874a'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-1.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-2.webp' WHERE sha256 = '3cdf4c4e43033ee50b478a2122db3d6bb39d75d064f03f1ef2f944d98a805a4e'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-2.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-3.webp' WHERE sha256 = '6269919c231b9f5e2008d42cdf00d69f686c72d212f7fdba9556796794563563'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-3.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-4.webp' WHERE sha256 = 'b87e4243bf90423913700580d38eba09196cab48bde5c422184fa988fbfc2e2c'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-4.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-5.webp' WHERE sha256 = '7ccb0677f492e97bfc1d93d5f5c92acca7f49a942c3929e5e64c87cb2504747f'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-5.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-6.webp' WHERE sha256 = 'f06ad6c833e1adf2a844bb9226fd741e3eaa9690de6fbfd184ca6735a5080f9f'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-6.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-7.webp' WHERE sha256 = '32206f27b9cbb1a4f3337440d5fc219e67f132227e7158685997c785f30d59bd'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-7.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-8.webp' WHERE sha256 = 'f24cd24b525cc024b906cdc67a8fdf6c7030cb304f2165abe0f8546db58715c1'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-8.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-9.webp' WHERE sha256 = '32924f7b84ec7639627cfc96a7771dc54a81d8a652da1093fa8f3de234de5a26'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-9.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-10.webp' WHERE sha256 = 'ba1b14ea308feaffb150d397dc8a87d26ba763a7515e68910d0b57ab558d35f5'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-10.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-11.webp' WHERE sha256 = 'fa4841c8c387d58f0f5460825fb0d9a4054aa1fa58c55baf74b028a50a11aa47'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-11.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-12.webp' WHERE sha256 = 'acd57c4ec60f9d155941a0fbe44acfb79fa7a1d1c187d551cd8ab279b747f699'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-12.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-13.webp' WHERE sha256 = 'f85b0ca5470b645b85a675a4f4b3b0645462e933d5aeabfe83aa204c5649426f'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-13.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-14.webp' WHERE sha256 = 'cb484b39220f83b9cc64181483e01a67bd7387733faaa7811a17744c043dbc04'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-14.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-15.webp' WHERE sha256 = '43b60801b2d298febe710b106de3b3df01112a45eb6c49d9bd862b3ec99d2dbb'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-15.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-16.webp' WHERE sha256 = '53ccff189d17806993eb61e78e7ea110c6caab2457b8039c282edf043d553907'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-16.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-17.webp' WHERE sha256 = '848271881a33d12a41341410a72688eb119a7f0d33fe6f4891e4677934254eef'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-17.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-18.webp' WHERE sha256 = '9aee615b6346432a6a5d6c1a2a15a89d838ff8e74c4a5cf2884cc5796dbe7ddb'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-18.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-19.webp' WHERE sha256 = 'b5e102918a9177056f0046ba60eafa424e933c4e00170f4a7ea28bf19f82e9fb'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-19.webp';

UPDATE media_asset SET original_filename = '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-23.webp' WHERE sha256 = 'd8e9bca7ff3d49ceb9a2a40da47b3c3e169871b7544e7d4b0edade12ea2a0153'
AND original_filename <> '染缸-染色机缸体表面保温哪种材料效果好？气凝胶涂料实测优选！-图片-23.webp';

UPDATE media_asset SET original_filename = '气凝胶涂料在某新建染厂染缸系统中的应用案例-图片-1.webp' WHERE sha256 = '2e71cca1e78a78172904a676705c217fa6f09f674690ced9407574844fc9b3ad'
AND original_filename <> '气凝胶涂料在某新建染厂染缸系统中的应用案例-图片-1.webp';

UPDATE media_asset SET original_filename = '长沙屋顶隔热保温望城区山与墅项目圆满完工，奥飞涂料助力清凉过夏-图片-1.webp' WHERE sha256 = '31456a8bf43b02edcbe26435571fd4dfc3b67b9ce86035a29c25285bcb60fbbd'
AND original_filename <> '长沙屋顶隔热保温望城区山与墅项目圆满完工，奥飞涂料助力清凉过夏-图片-1.webp';

UPDATE media_asset SET original_filename = '长沙屋顶隔热保温望城区山与墅项目圆满完工，奥飞涂料助力清凉过夏-图片-2.webp' WHERE sha256 = '3d4e84f50b0866f8226b7ff8a56feb94321c3ba989ddc67b4c20f4471f69b9a5'
AND original_filename <> '长沙屋顶隔热保温望城区山与墅项目圆满完工，奥飞涂料助力清凉过夏-图片-2.webp';

UPDATE media_asset SET original_filename = '长沙屋顶隔热保温望城区山与墅项目圆满完工，奥飞涂料助力清凉过夏-图片-3.webp' WHERE sha256 = '7d72a62541c4a9ac8cd105d3196f86c4d38585a1db028f637e19beaaef1ca41c'
AND original_filename <> '长沙屋顶隔热保温望城区山与墅项目圆满完工，奥飞涂料助力清凉过夏-图片-3.webp';

UPDATE media_asset SET original_filename = '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-1.webp' WHERE sha256 = 'fe4985514248356206a07a8f4e26408c9384c5f0545c364a9988c903e5d185c7'
AND original_filename <> '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-1.webp';

UPDATE media_asset SET original_filename = '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-2.webp' WHERE sha256 = '97c1487169dd2e464e91e47032e6091f48bbeee318d46df78228ae08103d9183'
AND original_filename <> '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-2.webp';

UPDATE media_asset SET original_filename = '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-3.webp' WHERE sha256 = '4a1809dd9e9c112adc370773e4c36f390d3dd41343a3ee27470bc229f25d891d'
AND original_filename <> '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-3.webp';

UPDATE media_asset SET original_filename = '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-5.webp' WHERE sha256 = '6c5d8d0d2a50d46705ded07ecf71b27257059ceca43b55ad898b051c71f15701'
AND original_filename <> '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-5.webp';

UPDATE media_asset SET original_filename = '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-6.webp' WHERE sha256 = '78bedf7736b4352ed3ae875ad494c6e5ce3f470e0e6c8f3a87b83c77d4f640a7'
AND original_filename <> '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-6.webp';

UPDATE media_asset SET original_filename = '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-7.webp' WHERE sha256 = '847490d95458b17648eba5c5cc84ddbbeab72fd0ff888618d4e4def7166927c3'
AND original_filename <> '长沙山与墅屋顶隔热工程正式开工，奥飞气凝胶涂料助力打造耐热节能建筑-图片-7.webp';

UPDATE media_asset SET original_filename = '长沙某公寓内墙气凝胶内墙涂料应用案例-图片-1.webp' WHERE sha256 = '8feacdc286b3cd3ea263dcca9f9ce9e4cba64d5ce90c6604baf471d6ae345f31'
AND original_filename <> '长沙某公寓内墙气凝胶内墙涂料应用案例-图片-1.webp';

UPDATE media_asset SET original_filename = '长沙某公寓内墙气凝胶内墙涂料应用案例-图片-2.webp' WHERE sha256 = 'e7cb8341f9eb73304ffbea9940ae79b892701cdd7d51e922fdf5726db9b94f9a'
AND original_filename <> '长沙某公寓内墙气凝胶内墙涂料应用案例-图片-2.webp';

UPDATE media_asset SET original_filename = '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-1.webp' WHERE sha256 = '615b9a98a14807e25d9be8d2ee81af31e7765763cdd17210c7ca18a8d9c28d1a'
AND original_filename <> '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-1.webp';

UPDATE media_asset SET original_filename = '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-2.webp' WHERE sha256 = 'a762a34450c80d839fb27047da7c32c4a829fb2bcabcbf8ee6a9c8f6983790d4'
AND original_filename <> '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-2.webp';

UPDATE media_asset SET original_filename = '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-3.webp' WHERE sha256 = '9a11076483e3110b9fb9164e9ed92542c7b3c3d583197d9bc38b38c2e71f7c15'
AND original_filename <> '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-3.webp';

UPDATE media_asset SET original_filename = '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-4.webp' WHERE sha256 = '083279e5f0e6f2a3a0c424d868f2fb93e7dd663fe3bac16546cad606b399b105'
AND original_filename <> '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-4.webp';

UPDATE media_asset SET original_filename = '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-5.webp' WHERE sha256 = 'e7ee90b6d5c64978e3db10bc0e449edbf9f5adef261196a17bf21af6986a6ed5'
AND original_filename <> '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-5.webp';

UPDATE media_asset SET original_filename = '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-6.webp' WHERE sha256 = '56830bb910f23e9dcda4d06a9c5134c4b7fd57e9dd5008756ade0fcf45dd4cfd'
AND original_filename <> '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-6.webp';

UPDATE media_asset SET original_filename = '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-7.webp' WHERE sha256 = 'f2e810cd73a143e232bfc85662a0ccc2cec1a2ff6d77f1bf259109d5c14eb0c1'
AND original_filename <> '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-7.webp';

UPDATE media_asset SET original_filename = '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-8.webp' WHERE sha256 = '5d33ff143abd783733846472cd1fea16b1b102288680dc98e5d0a61343a52cde'
AND original_filename <> '高校旧楼焕新，气凝胶涂料助力节能升级——奥飞新材宿舍翻新改造案例-图片-8.webp';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-1.jpg' WHERE sha256 = '8c07c8785b15b9263e1cd0a91784aa2f4f66639dc8a8b1a36900448213e1193f'
AND original_filename <> 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-1.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-2.jpg' WHERE sha256 = '99df4641a00a428344d09a3236592718f3a3d2bbc688dd2b87a29f6116ea8313'
AND original_filename <> 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-2.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-3.jpg' WHERE sha256 = '5de418c0c69454254a034f5b0375cc1ba5d77012e3df73187265c25db023bcdc'
AND original_filename <> 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-3.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-4.jpg' WHERE sha256 = '5e1bf69557f0cadc7e1ccc286e9307e51af3d7198a85bf44ff379fca849c025b'
AND original_filename <> 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-4.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-5.jpg' WHERE sha256 = '2259cdb4025c405ca9dc117fcd79844aff6a7213fdb7ee8385656c40e7832b8d'
AND original_filename <> 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-5.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-6.jpg' WHERE sha256 = '700145a159397296945fdd69ef886020e7dde78afba1810fdd1daab9320507aa'
AND original_filename <> 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-6.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-7.jpg' WHERE sha256 = '421a33f92ddc4616cf2418944ad556c04f85e8196e46d892cc33050d4c845a5d'
AND original_filename <> 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-7.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-8.jpg' WHERE sha256 = '601532bafab41b6b8fbaa31ed581484c44c6450ec782e13536d911cd5ec6f502'
AND original_filename <> 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-8.jpg';

UPDATE media_asset SET original_filename = 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-9.jpg' WHERE sha256 = 'f3f76ea6b46bcafe74694744e254ec03d9fcd7ecefd08d29a0cc75d3629530dc'
AND original_filename <> 'SiO₂气凝胶柔性复合材料的制备及性能研究-图片-9.jpg';

UPDATE media_asset SET original_filename = '奥飞新材宋淼教授分享高性能低成本硅基气凝胶常压干燥技术，推动产业化发展-图片-1.jpg' WHERE sha256 = 'cbeb2540b428648630530ada95b0b1a143ebffc9904e84967f8483f6a5d8451c'
AND original_filename <> '奥飞新材宋淼教授分享高性能低成本硅基气凝胶常压干燥技术，推动产业化发展-图片-1.jpg';

UPDATE media_asset SET original_filename = '奥飞新材宋淼教授分享高性能低成本硅基气凝胶常压干燥技术，推动产业化发展-图片-2.jpg' WHERE sha256 = 'f58fb1bffee55d1443d54bde4b377a32a40ec0cea59149d6f98d6a0f1944f06d'
AND original_filename <> '奥飞新材宋淼教授分享高性能低成本硅基气凝胶常压干燥技术，推动产业化发展-图片-2.jpg';

UPDATE media_asset SET original_filename = '气凝胶柔性复合材料技术-图片-1.jpg' WHERE sha256 = 'c801401ec356b0b3a6bdbbe5851e5c6ec98c2a7ba736134df811e98dd63fcc5d'
AND original_filename <> '气凝胶柔性复合材料技术-图片-1.jpg';

UPDATE media_asset SET original_filename = '界面主导构型调控：Ag–Cu 金属气凝胶实现高选择性、长稳态 CO₂ 电还原-图片-1.jpg' WHERE sha256 = 'ca2e8046b3e262adba5a2e1d2c9db6c3567ea062a95003d59eda0cca9bba848a'
AND original_filename <> '界面主导构型调控：Ag–Cu 金属气凝胶实现高选择性、长稳态 CO₂ 电还原-图片-1.jpg';

UPDATE media_asset SET original_filename = '金属气凝胶技术-图片-1.jpg' WHERE sha256 = '92a172f396222050d149baabcbea1a79c83d111757406e8c72cf374b58e5e760'
AND original_filename <> '金属气凝胶技术-图片-1.jpg';

UPDATE media_asset SET original_filename = '金属气凝胶技术-图片-2.jpg' WHERE sha256 = '1543a653c5f6f0fb7c0e799cb2d3027d8d44d73ace59df7938cdb66fd5d03657'
AND original_filename <> '金属气凝胶技术-图片-2.jpg';

UPDATE media_asset SET original_filename = '金属气凝胶技术-图片-3.jpg' WHERE sha256 = 'ef6c86483ca2d64c39670398807dfc0b3d709d738aa6bf7e41baef2d777de54f'
AND original_filename <> '金属气凝胶技术-图片-3.jpg';

UPDATE media_asset SET original_filename = '金属气凝胶技术-图片-4.jpg' WHERE sha256 = '73cfc362c0937af771679cc46dc3bcc100590351faaa404369a674121216d28e'
AND original_filename <> '金属气凝胶技术-图片-4.jpg';

COMMIT;
